My Project: Cyg_Scheduler Class Reference
Cyg_Scheduler Class Reference
#include <sched.hxx>
Public Member Functions
void thread_entry (Cyg_Thread *thread)
Public Member Functions inherited from Cyg_Scheduler_Implementation
void set_idle_thread (Cyg_Thread *thread, HAL_SMP_CPU_TYPE cpu)
void timeslice ()
void timeslice_cpu ()
Static Public Member Functions
static
CYGDBG_DEFINE_CHECK_THIS void lock ()
static void unlock ()
static void reschedule ()
static void unlock_reschedule ()
static void unlock_simple ()
static void start () CYGBLD_ATTRIB_NORET
static void start_cpu () CYGBLD_ATTRIB_NORET
Static Public Attributes
static Cyg_Scheduler scheduler CYGBLD_ANNOTATE_VARIABLE_SCHED
Static Private Member Functions
static void unlock_inner (cyg_uint32 new_lock=0)
Friends
class Cyg_Thread
Additional Inherited Members
Protected Member Functions inherited from Cyg_Scheduler_Implementation
Cyg_Scheduler_Implementation ()
Cyg_Thread * schedule ()
void add_thread (Cyg_Thread *thread)
void rem_thread (Cyg_Thread *thread)
void register_thread (Cyg_Thread *thread)
void deregister_thread (Cyg_Thread *thread)
cyg_bool unique (cyg_priority priority)
Static Protected Member Functions inherited from Cyg_Scheduler_Implementation
static void set_need_reschedule (Cyg_Thread *thread)
static void set_need_reschedule ()
Static Protected Attributes inherited from Cyg_Scheduler_Implementation
static cyg_ucount32
timeslice_count[CYGNUM_KERNEL_CPU_MAX] CYGBLD_ANNOTATE_VARIABLE_SCHED
Detailed Description
Definition at line 140 of file sched.hxx.
Member Function Documentation
void Cyg_Scheduler::lock () inline static
Definition at line 68 of file sched.inl.
References Cyg_Scheduler_Base::get_sched_lock(), and Cyg_Scheduler_SchedLock::inc_sched_lock().
Referenced by Cyg_ThreadTimer::alarm(), Cyg_Thread::cancel_counted_wake(), Cyg_Thread::counted_sleep(), Cyg_Thread::counted_wake(), Cyg_Thread::delay(), Cyg_Alarm::disable(), Cyg_Alarm::enable(), Cyg_Thread::exit(), Cyg_Thread::force_resume(), Cyg_Alarm::get_times(), Cyg_Alarm::initialize(), Cyg_Thread::kill(), Cyg_Thread::release(), Cyg_Thread::resume(), Cyg_SchedThread_Implementation::rotate_queue(), Cyg_Thread::set_priority(), Cyg_Thread::sleep(), Cyg_Thread::suspend(), Cyg_Counter::tick(), Cyg_SchedThread_Implementation::to_queue_head(), Cyg_Thread::wake(), and Cyg_SchedThread_Implementation::yield().
 {
     // We do not need to do a read-modify-write sequence here because
     // the scheduler lock is strictly nesting. Even if we are interrupted
     // partway through the increment, the lock will be returned to the same
     // value before we are resumed/rescheduled.
     HAL_REORDER_BARRIER();
     inc_sched_lock();
     HAL_REORDER_BARRIER();
     CYG_INSTRUMENT_SCHED(LOCK,get_sched_lock(),0);
 };
void Cyg_Scheduler::reschedule () inline static
Definition at line 105 of file sched.inl.
References Cyg_Scheduler_Base::get_sched_lock(), and unlock_inner().
Referenced by Cyg_Thread::counted_sleep(), and Cyg_Thread::exit().
 {
     // This function performs the equivalent of calling unlock() and
     // lock() is succession. Unlike that pair, however, it does not
     // leave a brief window between the calls when the lock is unclaimed
     // by the current thread.
     CYG_INSTRUMENT_SCHED(RESCHEDULE,get_sched_lock(),0);
     unlock_inner( get_sched_lock() );
 }
void Cyg_Scheduler::start () static
Definition at line 329 of file sched.cxx.
References CYG_REPORT_FUNCTION, and start_cpu().
 {
     CYG_REPORT_FUNCTION();
     start_cpu();
 }
void Cyg_Scheduler::start_cpu () static
Definition at line 340 of file sched.cxx.
References Cyg_Scheduler_Base::clear_need_reschedule(), CYG_REFERENCE_OBJECT, CYG_REPORT_FUNCTION, Cyg_Clock::real_time_clock, Cyg_Scheduler_Base::set_current_thread(), and Cyg_HardwareThread::stack_ptr.
Referenced by start().
 {
     CYG_REPORT_FUNCTION();
     // Get the first thread to run from scheduler
     register Cyg_Thread *next = scheduler.schedule();
     CYG_ASSERTCLASS( next, "Bad initial thread" );
     clear_need_reschedule();            // finished rescheduling
     set_current_thread(next);           // restore current thread pointer
 #ifdef CYGVAR_KERNEL_COUNTERS_CLOCK
     // Reference the real time clock. This ensures that at least one
     // reference to the kernel_clock.o object exists, without which
     // the object will not be included while linking.
     CYG_REFERENCE_OBJECT( Cyg_Clock::real_time_clock );
 #endif
     // Load the first thread. This will also enable interrupts since
     // the initial state of all threads is to have interrupts enabled.
     HAL_THREAD_LOAD_CONTEXT( &next->stack_ptr );
 }
void Cyg_Scheduler::thread_entry (Cyg_Thread * thread)
Definition at line 306 of file sched.cxx.
References Cyg_Scheduler_Base::clear_need_reschedule(), Cyg_Scheduler_Base::get_sched_lock(), Cyg_Scheduler_Base::set_current_thread(), Cyg_SchedThread_Implementation::timeslice_reset(), Cyg_SchedThread_Implementation::timeslice_restore(), and unlock().
 {
     clear_need_reschedule();            // finished rescheduling
     set_current_thread(thread);         // restore current thread pointer
     CYG_INSTRUMENT_THREAD(ENTER,thread,0);
     thread->timeslice_reset();
     thread->timeslice_restore();
     // Finally unlock the scheduler. As well as clearing the scheduler
     // lock this allows any pending DSRs to execute. The new thread
     // must start with a lock of zero, so we keep unlocking until the
     // lock reaches zero.
     while( get_sched_lock() != 0 )
         unlock();
 }
void Cyg_Scheduler::unlock () inline static
Definition at line 84 of file sched.inl.
References Cyg_Scheduler_Base::get_sched_lock(), Cyg_Scheduler_SchedLock::set_sched_lock(), and unlock_inner().
Referenced by Cyg_ThreadTimer::alarm(), Cyg_Thread::cancel_counted_wake(), Cyg_Thread::counted_sleep(), Cyg_Thread::counted_wake(), Cyg_Thread::delay(), Cyg_Alarm::disable(), Cyg_Alarm::enable(), Cyg_Thread::force_resume(), Cyg_Alarm::get_times(), Cyg_Alarm::initialize(), Cyg_Thread::kill(), Cyg_Thread::release(), Cyg_Thread::resume(), Cyg_SchedThread_Implementation::rotate_queue(), Cyg_Thread::set_priority(), Cyg_Thread::sleep(), Cyg_Thread::suspend(), thread_entry(), Cyg_Counter::tick(), Cyg_SchedThread_Implementation::to_queue_head(), Cyg_Thread::wake(), and Cyg_SchedThread_Implementation::yield().
 {
     // This is an inline wrapper for the real scheduler unlock function in
     // Cyg_Scheduler::unlock_inner().
     // Only do anything if the lock is about to go zero, otherwise we simply
     // decrement and return. As with lock() we do not need any special code
     // to decrement the lock counter.
     CYG_INSTRUMENT_SCHED(UNLOCK,get_sched_lock(),0);
     HAL_REORDER_BARRIER();
     cyg_ucount32 __lock = get_sched_lock() - 1;
     if( __lock == 0 ) unlock_inner(0);
     else set_sched_lock(__lock);
     HAL_REORDER_BARRIER();
 }
void Cyg_Scheduler::unlock_inner (cyg_uint32 new_lock = 0) static private
Definition at line 130 of file sched.cxx.
References Cyg_Scheduler_Base::clear_need_reschedule(), CYG_CHECK_DATA_PTR, CYG_FAIL, CYG_KERNEL_CPU_THIS, CYG_PRECONDITION, CYG_REPORT_FUNCTION, CYG_REPORT_RETURN, Cyg_Scheduler_Base::get_current_thread(), Cyg_Scheduler_Base::get_need_reschedule(), Cyg_Scheduler_Base::get_sched_lock(), Cyg_Scheduler_SchedLock::inc_sched_lock(), Cyg_Thread::RUNNING, Cyg_Scheduler_SchedLock::set_sched_lock(), Cyg_HardwareThread::stack_ptr, Cyg_Thread::state, Cyg_SchedThread_Implementation::timeslice_restore(), Cyg_SchedThread_Implementation::timeslice_save(), and Cyg_Scheduler_SchedLock::zero_sched_lock().
Referenced by reschedule(), unlock(), and unlock_reschedule().
 {
 #ifdef CYGDBG_KERNEL_TRACE_UNLOCK_INNER
     CYG_REPORT_FUNCTION();
 #endif
     do {
         //
         //0
         //>=0
         CYG_PRECONDITION( new_lock==0 ? get_sched_lock() == 1 :
                           ((get_sched_lock() == new_lock) || (get_sched_lock() == new_lock+1)),
                           "sched_lock not at expected value" );
 #ifdef CYGIMP_KERNEL_INTERRUPTS_DSRS
         // Call any pending DSRs. Do this here to ensure that any
         // threads that get awakened are properly scheduled.
         //endingDSR
         if( new_lock == 0 && Cyg_Interrupt::DSRs_pending() )
             Cyg_Interrupt::call_pending_DSRs();
 #endif
         //currentnlock_inner()
         Cyg_Thread *current = get_current_thread();
         //
         CYG_ASSERTCLASS( current, "Bad current thread" );
 //
 #ifdef CYGFUN_KERNEL_ALL_THREADS_STACK_CHECKING
         // should have  CYGVAR_KERNEL_THREADS_LIST
         //
         //current
         current = Cyg_Thread::get_list_head();
         while ( current ) {
             current->check_stack();
             current = current->get_list_next();
         }
         //current
         current = get_current_thread();
 #endif
 #ifdef CYGFUN_KERNEL_THREADS_STACK_CHECKING
         current->check_stack();
 #endif
         // If the current thread is going to sleep, or someone
         // wants a reschedule, choose another thread to run
         //
         //unning
         //unlock_inner()pu
         if( current->state != Cyg_Thread::RUNNING || get_need_reschedule() ) {
             //
             CYG_INSTRUMENT_SCHED(RESCHEDULE,0,0);
             // Get the next thread to run from scheduler
             //scheduler
             Cyg_Thread *next = scheduler.schedule();
             //next
             CYG_CHECK_DATA_PTR( next, "Invalid next thread pointer");
             CYG_ASSERTCLASS( next, "Bad next thread" );
             //exturrent
             //nlock_inner()pu
             //chedulerext
             if( current != next )
             {
                 CYG_INSTRUMENT_THREAD(SWITCH,current,next);
                 // Count this thread switch
                 //thread_switchescpu
                 thread_switches[CYG_KERNEL_CPU_THIS()]++;
                 //
 #ifdef CYGFUN_KERNEL_THREADS_STACK_CHECKING
                 next->check_stack(); // before running it
 #endif
                 //
                 //
                 current->timeslice_save();
                 // Switch contexts
                 //HAL
                 HAL_THREAD_SWITCH_CONTEXT( &current->stack_ptr,
                                            &next->stack_ptr );
                 // Worry here about possible compiler
                 // optimizations across the above call that may try to
                 // propogate common subexpresions.  We would end up
                 // with the expression from one thread in its
                 // successor. This is only a worry if we do not save
                 // and restore the complete register set. We need a
                 // way of marking functions that return into a
                 // different context. A temporary fix would be to
                 // disable CSE (-fdisable-cse) in the compiler.
                 // We return here only when the current thread is
                 // rescheduled.  There is a bit of housekeeping to do
                 // here before we are allowed to go on our way.
                 CYG_CHECK_DATA_PTR( current, "Invalid current thread pointer");
                 CYG_ASSERTCLASS( current, "Bad current thread" );
                 //current_threadurrent
                 current_thread[CYG_KERNEL_CPU_THIS()] = current;   // restore current thread pointer
                 //
                 current->timeslice_restore();
             }
             //rescheduling
             //eed_reschedule
             clear_need_reschedule();    // finished rescheduling
         }
         //
         if( new_lock == 0 )
         {
 //ASR
             //
             HAL_REORDER_BARRIER(); // Make sure everything above has happened
                                    // by this point
             //
             zero_sched_lock();     // Clear the lock
             HAL_REORDER_BARRIER();
 #ifdef CYGIMP_KERNEL_INTERRUPTS_DSRS
             // Now check whether any DSRs got posted during the thread
             // switch and if so, go around again. Making this test after
             // the lock has been zeroed avoids a race condition in which
             // a DSR could have been posted during a reschedule, but would
             // not be run until the _next_ time we release the sched lock.
             //DSR
             if( Cyg_Interrupt::DSRs_pending() ) {
                 inc_sched_lock();   // reclaim the lock
                 continue;           // go back to head of loop
             }
 #endif
             // Otherwise the lock is zero, we can return.
 //            CYG_POSTCONDITION( get_sched_lock() == 0, "sched_lock not zero" );
         }
         //
         else
         {
             // If new_lock is non-zero then we restore the sched_lock to
             // the value given.
             HAL_REORDER_BARRIER();
             //
             set_sched_lock(new_lock);
             HAL_REORDER_BARRIER();
         }
 #ifdef CYGDBG_KERNEL_TRACE_UNLOCK_INNER
         CYG_REPORT_RETURN();
 #endif
         return;
     } while( 1 );
     CYG_FAIL( "Should not be executed" );
 }
void Cyg_Scheduler::unlock_reschedule () inline static
Definition at line 117 of file sched.inl.
References Cyg_Scheduler_Base::get_sched_lock(), and unlock_inner().
Referenced by Cyg_SchedThread_Implementation::yield().
 {
     // This function decrements the scheduler lock and also looks for
     // a reschedule opportunity. When the lock is being decremented
     // from 1 to zero this function is equivalent to unlock. When the
     // lock is being decremented to a non-zero value, it is more or less
     // equivalent to reschedule() followed by unlock().
     CYG_INSTRUMENT_SCHED(UNLOCK,get_sched_lock(),0);
     unlock_inner( get_sched_lock() - 1 );
 }
void Cyg_Scheduler::unlock_simple () inline static
Definition at line 130 of file sched.inl.
References Cyg_Scheduler_Base::get_sched_lock(), Cyg_Scheduler_SchedLock::set_sched_lock(), and Cyg_Scheduler_SchedLock::zero_sched_lock().
 {
     // This function decrements the lock, but does not call unlock_inner().
     // Therefore does not immediately allow another thread to run:
     // merely makes it possible for some other thread to run at some
     // indeterminate future time.  This is mainly for use by
     // debuggers, it should not normally be used anywhere else.
     CYG_INSTRUMENT_SCHED(UNLOCK,get_sched_lock(),0);
     HAL_REORDER_BARRIER();
     if (get_sched_lock() > 1)
         set_sched_lock(get_sched_lock() - 1);
     else zero_sched_lock();
     HAL_REORDER_BARRIER();
 }
Friends And Related Function Documentation
friend class Cyg_Thread friend
Definition at line 143 of file sched.hxx.
Member Data Documentation
Cyg_Scheduler scheduler Cyg_Scheduler::CYGBLD_ANNOTATE_VARIABLE_SCHED static
Definition at line 184 of file sched.hxx.
The documentation for this class was generated from the following files:
C:/Users/barry/Documents/GitHub/VEROS/Xinrui/20130621_refined_thread/sched.hxx
C:/Users/barry/Documents/GitHub/VEROS/Xinrui/20130621_refined_thread/sched.cxx
C:/Users/barry/Documents/GitHub/VEROS/Xinrui/20130621_refined_thread/sched.inl