My Project: Cyg_DNode Class Reference
Cyg_DNode Class Reference
#include <clist.hxx>
Public Member Functions
Cyg_DNode ()
Cyg_DNode * get_next ()
Cyg_DNode * get_prev ()
cyg_bool in_list ()
void insert (Cyg_DNode *node)
void append (Cyg_DNode *node)
void unlink ()
~Cyg_DNode ()
Private Attributes
Cyg_DNode * next
Cyg_DNode * prev
Friends
class Cyg_CList
Detailed Description
Definition at line 90 of file clist.hxx.
Constructor & Destructor Documentation
Cyg_DNode::Cyg_DNode () inline
Definition at line 99 of file clist.hxx.
References next, and prev.
     {
         // Initialize pointers to point here
         next = prev = this;
     };
Cyg_DNode::~Cyg_DNode () inline
Definition at line 140 of file clist.hxx.
References next, and unlink().
     {
         // If this node is still linked, unlink it.
         if( next != this )
             unlink();
     };
Member Function Documentation
void Cyg_DNode::append (Cyg_DNode * node) inline
Definition at line 123 of file clist.hxx.
References next, and prev.
Referenced by Cyg_ThreadQueue_Implementation::enqueue().
     {
         node->prev = this;
         node->next = next;
         next->prev = node;
         next = node;
     };
Cyg_DNode* Cyg_DNode::get_next () inline
Definition at line 106 of file clist.hxx.
References next.
Referenced by Cyg_DNode_T< Cyg_Thread >::get_next().
 { return next; };
Cyg_DNode* Cyg_DNode::get_prev () inline
Definition at line 107 of file clist.hxx.
References prev.
Referenced by Cyg_DNode_T< Cyg_Thread >::get_prev().
 { return prev; };
cyg_bool Cyg_DNode::in_list () inline
Definition at line 108 of file clist.hxx.
References next.
Referenced by Cyg_SchedThread_Implementation::to_queue_head().
 { return next != this; };
void Cyg_DNode::insert (Cyg_DNode * node) inline
Definition at line 113 of file clist.hxx.
References next, and prev.
Referenced by Cyg_CList::add_head(), Cyg_CList::add_tail(), Cyg_ThreadQueue_Implementation::enqueue(), and Cyg_CList::insert().
     {
         node->next = this;
         node->prev = prev;
         prev->next = node;
         prev = node;
     };
void Cyg_DNode::unlink () inline
Definition at line 133 of file clist.hxx.
References next, and prev.
Referenced by Cyg_CList::rem_head(), Cyg_CList::rem_tail(), and ~Cyg_DNode().
     {
         next->prev = prev;
         prev->next = next;
         next = prev = this;
     };
Friends And Related Function Documentation
friend class Cyg_CList friend
Definition at line 92 of file clist.hxx.
Member Data Documentation
Cyg_DNode* Cyg_DNode::next private
Definition at line 94 of file clist.hxx.
Referenced by append(), Cyg_DNode(), get_next(), in_list(), insert(), Cyg_CList::merge(), Cyg_CList::rem_head(), Cyg_CList::rotate(), unlink(), and ~Cyg_DNode().
Cyg_DNode* Cyg_DNode::prev private
Definition at line 95 of file clist.hxx.
Referenced by append(), Cyg_DNode(), get_prev(), Cyg_CList::get_tail(), insert(), Cyg_CList::merge(), Cyg_CList::rem_tail(), and unlink().
The documentation for this class was generated from the following file:
C:/Users/barry/Documents/GitHub/VEROS/Xinrui/20130621_refined_thread/clist.hxx