My Project: Cyg_Interrupt Class Reference
Cyg_Interrupt Class Reference
#include <intr.hxx>
Public Types
enum { HANDLED = 1, CALL_DSR = 2 }
Public Member Functions
Cyg_Interrupt (cyg_vector vector, cyg_priority priority, CYG_ADDRWORD data, cyg_ISR *isr, cyg_DSR *dsr)
~Cyg_Interrupt ()
void attach ()
void detach ()
cyg_vector get_vector ()
Static Public Member Functions
static void get_vsr (cyg_vector vector, cyg_VSR **vsr)
static void set_vsr (cyg_vector vector, cyg_VSR *vsr, cyg_VSR **old=NULL)
static void disable_interrupts ()
static void enable_interrupts ()
static cyg_bool interrupts_enabled ()
static void mask_interrupt (cyg_vector vector)
static void mask_interrupt_intunsafe (cyg_vector vector)
static void unmask_interrupt (cyg_vector vector)
static void unmask_interrupt_intunsafe (cyg_vector vector)
static void acknowledge_interrupt (cyg_vector vector)
static void configure_interrupt (cyg_vector vector, cyg_bool level, cyg_bool up)
Private Member Functions
void post_dsr ()
Static Private Member Functions
static cyg_bool DSRs_pending ()
static void call_pending_DSRs ()
static void call_pending_DSRs_inner ()
Private Attributes
cyg_vector vector
cyg_priority priority
cyg_ISR * isr
cyg_DSR * dsr
CYG_ADDRWORD data
Static Private Attributes
static volatile cyg_int32
disable_counter[CYGNUM_KERNEL_CPU_MAX] CYGBLD_ANNOTATE_VARIABLE_INTR
static Cyg_SpinLock
interrupt_disable_spinlock CYGBLD_ANNOTATE_VARIABLE_INTR
static CYG_INTERRUPT_STATE
interrupt_disable_state[CYGNUM_KERNEL_CPU_MAX] CYGBLD_ANNOTATE_VARIABLE_INTR
Friends
class Cyg_Scheduler
void interrupt_end (cyg_uint32, Cyg_Interrupt *, HAL_SavedRegisters *)
void cyg_interrupt_post_dsr (CYG_ADDRWORD intr_obj)
void cyg_interrupt_call_pending_DSRs (void)
Detailed Description
Definition at line 125 of file intr.hxx.
Member Enumeration Documentation
anonymous enum
Enumerator
HANDLED
CALL_DSR
Definition at line 283 of file intr.hxx.
          {
         HANDLED  = 1,                   // Interrupt was handled
         CALL_DSR = 2                    // Schedule DSR
     };
Constructor & Destructor Documentation
Cyg_Interrupt::Cyg_Interrupt (cyg_vector vector, cyg_priority priority, CYG_ADDRWORD data, cyg_ISR * isr, cyg_DSR * dsr)
Definition at line 77 of file intr.cxx.
References CYG_REPORT_FUNCARG5, CYG_REPORT_FUNCTION, CYG_REPORT_RETURN, data, dsr, isr, NULL, priority, and vector.
 {
     CYG_REPORT_FUNCTION();
     CYG_REPORT_FUNCARG5("vector=%d, priority=%d, data=%08x, isr=%08x, "
                         "dsr=%08x", vec, pri, d, ir, dr);
     vector      = vec;
     priority    = pri;
     isr         = ir;
     dsr         = dr;
     data        = d;
 #ifdef CYGIMP_KERNEL_INTERRUPTS_DSRS_LIST
     dsr_count   = 0;
     next_dsr    = NULL;
 #endif
 #ifdef CYGIMP_KERNEL_INTERRUPTS_CHAIN
     next        = NULL;
 #endif
     CYG_REPORT_RETURN();
 };
Cyg_Interrupt::~Cyg_Interrupt ()
Definition at line 114 of file intr.cxx.
References CYG_REPORT_FUNCTION, CYG_REPORT_RETURN, and detach().
 {
     CYG_REPORT_FUNCTION();
     detach();
     CYG_REPORT_RETURN();
 };
Member Function Documentation
void Cyg_Interrupt::acknowledge_interrupt (cyg_vector vector) static
Definition at line 754 of file intr.cxx.
References CYG_ASSERT.
 {
 //    CYG_REPORT_FUNCTION();
     CYG_ASSERT( vector >= CYGNUM_HAL_ISR_MIN, "Invalid vector");
     CYG_ASSERT( vector <= CYGNUM_HAL_ISR_MAX, "Invalid vector");
     CYG_INSTRUMENT_INTR(ACK, vector, 0);
     HAL_INTERRUPT_ACKNOWLEDGE( vector );
 }
void Cyg_Interrupt::attach (void)
Definition at line 449 of file intr.cxx.
References CYG_ASSERT, CYG_REPORT_FUNCTION, CYG_REPORT_RETURN, CYGBLD_ATTRIB_UNUSED, isr, NULL, and priority.
 {
     CYG_REPORT_FUNCTION();
     CYG_ASSERT( vector >= CYGNUM_HAL_ISR_MIN, "Invalid vector");
     CYG_ASSERT( vector <= CYGNUM_HAL_ISR_MAX, "Invalid vector");
     CYG_INSTRUMENT_INTR(ATTACH, vector, 0);
     HAL_INTERRUPT_SET_LEVEL( vector, priority );
 #ifdef CYGIMP_KERNEL_INTERRUPTS_CHAIN
     CYG_ASSERT( next == NULL , "Cyg_Interrupt already on a list");
     cyg_uint32 index;
     HAL_TRANSLATE_VECTOR( vector, index );
     if( chain_list[index] == NULL )
     {
         int in_use CYGBLD_ATTRIB_UNUSED;
         // First Interrupt on this chain, just assign it and register
         // the chain_isr with the HAL.
         chain_list[index] = this;
         HAL_INTERRUPT_IN_USE( vector, in_use );
         CYG_ASSERT( 0 == in_use, "Interrupt vector not free.");
         HAL_INTERRUPT_ATTACH( vector, chain_isr, &chain_list[index], NULL );
     }
     else
     {
         // There are already interrupts chained, add this one into the
         // chain in priority order.
         Cyg_Interrupt **p = &chain_list[index];
         while( *p != NULL )
         {
             Cyg_Interrupt *n = *p;
             if( n->priority < priority ) break;
             p = &n->next;
         }
         next = *p;
         *p = this;
     }
 #else
     {
         int in_use CYGBLD_ATTRIB_UNUSED;
         HAL_INTERRUPT_IN_USE( vector, in_use );
         CYG_ASSERT( 0 == in_use, "Interrupt vector not free.");
         HAL_INTERRUPT_ATTACH( vector, isr, data, this );
     }
 #endif
     CYG_REPORT_RETURN();
 }
void Cyg_Interrupt::call_pending_DSRs (void) static private
Definition at line 245 of file intr.cxx.
References CYG_ASSERT, Cyg_Scheduler_Base::get_sched_lock(), and HAL_INTERRUPT_STACK_CALL_PENDING_DSRS.
Referenced by Cyg_Scheduler::unlock_inner().
 {
     CYG_ASSERT( Cyg_Scheduler::get_sched_lock() == 1,
                 "DSRs being called with sched_lock not equal to 1");
     HAL_INTERRUPT_STACK_CALL_PENDING_DSRS();
 }
void Cyg_Interrupt::call_pending_DSRs_inner (void) static private
Definition at line 149 of file intr.cxx.
References CALL_DSR, CYG_ASSERT, CYG_KERNEL_CPU_THIS, data, dsr, HAL_SMP_CPU_TYPE, NULL, and vector.
Referenced by cyg_interrupt_call_pending_DSRs().
 {
 //    CYG_REPORT_FUNCTION();
     HAL_SMP_CPU_TYPE cpu = CYG_KERNEL_CPU_THIS();
 #ifdef CYGIMP_KERNEL_INTERRUPTS_DSRS_TABLE
     while( dsr_table_head[cpu] != dsr_table_tail[cpu] )
     {
         Cyg_Interrupt *intr = dsr_table[cpu][dsr_table_head[cpu]];
         dsr_table_head[cpu]++;
         if( dsr_table_head[cpu] >= CYGNUM_KERNEL_INTERRUPTS_DSRS_TABLE_SIZE )
             dsr_table_head[cpu] = 0;
         CYG_INSTRUMENT_INTR(CALL_DSR, intr->vector, 0);
         CYG_ASSERT( intr->dsr != NULL , "No DSR defined");
         intr->dsr( intr->vector, 1, (CYG_ADDRWORD)intr->data );
     }
 #endif
 #ifdef CYGIMP_KERNEL_INTERRUPTS_DSRS_LIST
 #  ifdef CYGSEM_KERNEL_INTERRUPTS_DSRS_LIST_FIFO
     cyg_uint32 old_intr;
     HAL_DISABLE_INTERRUPTS(old_intr);
     Cyg_Interrupt* intr = dsr_list[cpu];
     CYG_ASSERT(intr != 0, "No DSRs are pended");
     dsr_list[cpu] = 0;
     dsr_list_tail[cpu] = 0;
     while(true)
     {
         cyg_count32 count = intr->dsr_count;
         Cyg_Interrupt* next = intr->next_dsr;
         intr->dsr_count = 0;
         intr->next_dsr = 0;
         HAL_RESTORE_INTERRUPTS(old_intr);
         CYG_ASSERT(intr->dsr != 0, "No DSR defined");
         CYG_ASSERT(count > 0, "DSR posted but post count is zero");
         intr->dsr(intr->vector, count, (CYG_ADDRWORD)intr->data);
         if (!next)
             break;
         intr = next;
         HAL_DISABLE_INTERRUPTS(old_intr);
     }
 #  else // ! defined CYGSEM_KERNEL_INTERRUPTS_DSRS_LIST_FIFO
     while( dsr_list[cpu] != NULL )
     {
         Cyg_Interrupt* intr;
         cyg_uint32 old_intr;
         cyg_count32 count;
         HAL_DISABLE_INTERRUPTS(old_intr);
         intr = dsr_list[cpu];
         dsr_list[cpu] = intr->next_dsr;
         count = intr->dsr_count;
         intr->dsr_count = 0;
         HAL_RESTORE_INTERRUPTS(old_intr);
         CYG_ASSERT( intr->dsr != NULL , "No DSR defined");
         intr->dsr( intr->vector, count, (CYG_ADDRWORD)intr->data );
     }
 #  endif  // ! defined CYGSEM_KERNEL_INTERRUPTS_DSRS_LIST_FIFO
 #endif  // defined CYGIMP_KERNEL_INTERRUPTS_DSRS_LIST
 };
void Cyg_Interrupt::configure_interrupt (cyg_vector vector, cyg_bool level, cyg_bool up) static
Definition at line 770 of file intr.cxx.
References CYG_ASSERT, CYG_REPORT_FUNCARG3, CYG_REPORT_FUNCTION, and CYG_REPORT_RETURN.
 {
     CYG_REPORT_FUNCTION();
     CYG_REPORT_FUNCARG3("vector = %d, level = %d, up = %d", vector, level,
                         up);
     CYG_ASSERT( vector >= CYGNUM_HAL_ISR_MIN, "Invalid vector");
     CYG_ASSERT( vector <= CYGNUM_HAL_ISR_MAX, "Invalid vector");
     CYG_INSTRUMENT_INTR(CONFIGURE, vector, (level<<1)|up);
     HAL_INTERRUPT_CONFIGURE( vector, level, up );
     CYG_REPORT_RETURN();
 }
void Cyg_Interrupt::detach (void)
Definition at line 518 of file intr.cxx.
References CYG_ASSERT, CYG_REPORT_FUNCTION, CYG_REPORT_RETURN, isr, and NULL.
Referenced by ~Cyg_Interrupt().
 {
     CYG_REPORT_FUNCTION();
     CYG_ASSERT( vector >= CYGNUM_HAL_ISR_MIN, "Invalid vector");
     CYG_ASSERT( vector <= CYGNUM_HAL_ISR_MAX, "Invalid vector");
     CYG_INSTRUMENT_INTR(DETACH, vector, 0);
 #ifdef CYGIMP_KERNEL_INTERRUPTS_CHAIN
     // Remove the interrupt object from the vector chain.
     cyg_uint32 index;
     HAL_TRANSLATE_VECTOR( vector, index );
     Cyg_Interrupt **p = &chain_list[index];
     while( *p != NULL )
     {
         Cyg_Interrupt *n = *p;
         if( n == this )
         {
             *p = next;
             break;
         }
         p = &n->next;
     }
     // If this was the last one, detach the vector.
     if( chain_list[index] == NULL )
         HAL_INTERRUPT_DETACH( vector, chain_isr );
 #else
     HAL_INTERRUPT_DETACH( vector, isr );
 #endif
     CYG_REPORT_RETURN();
 }
void Cyg_Interrupt::disable_interrupts (void) static
Definition at line 615 of file intr.cxx.
References CYG_KERNEL_CPU_THIS, CYG_REPORT_FUNCTION, CYG_REPORT_RETURN, and HAL_SMP_CPU_TYPE.
 {
     CYG_REPORT_FUNCTION();
     CYG_INSTRUMENT_INTR(DISABLE, disable_counter[CYG_KERNEL_CPU_THIS()]+1, 0);
     HAL_SMP_CPU_TYPE cpu_this = CYG_KERNEL_CPU_THIS();
     // If the disable_counter is zero, disable interrupts and claim the spinlock.
     if( 0 == disable_counter[cpu_this] )
     {
         // Claim the spinlock and disable interrupts. We save the original interrupt
         // enable state to restore later.
         interrupt_disable_spinlock.spin_intsave(&interrupt_disable_state[cpu_this]);
     }
     // Now increment our disable counter.
     disable_counter[cpu_this]++;
     CYG_REPORT_RETURN();
 }
static cyg_bool Cyg_Interrupt::DSRs_pending () static private
Referenced by Cyg_Scheduler::unlock_inner().
void Cyg_Interrupt::enable_interrupts (void) static
Definition at line 644 of file intr.cxx.
References CYG_ASSERT, CYG_KERNEL_CPU_THIS, CYG_REPORT_FUNCTION, CYG_REPORT_RETURN, and HAL_SMP_CPU_TYPE.
 {
     CYG_REPORT_FUNCTION();
     CYG_INSTRUMENT_INTR(ENABLE, disable_counter[CYG_KERNEL_CPU_THIS()], 0);
     HAL_SMP_CPU_TYPE cpu_this = CYG_KERNEL_CPU_THIS();
     CYG_ASSERT( disable_counter[cpu_this] > 0 , "Disable counter not greater than zero");
     // If the disable counter goes to zero, then release the spinlock and restore
     // the previous interrupt state.
     if( --disable_counter[cpu_this] == 0 )
     {
         interrupt_disable_spinlock.clear_intsave(interrupt_disable_state[cpu_this]);
     }
     CYG_REPORT_RETURN();
 }
cyg_vector Cyg_Interrupt::get_vector () inline
Definition at line 324 of file intr.hxx.
References vector.
     {
         return vector;
     }
void Cyg_Interrupt::get_vsr (cyg_vector vector, cyg_VSR ** vsr) static
Definition at line 569 of file intr.cxx.
References CYG_ASSERT, CYG_REPORT_FUNCARG2, CYG_REPORT_FUNCTION, and CYG_REPORT_RETURN.
 {
     CYG_REPORT_FUNCTION();
     CYG_REPORT_FUNCARG2("vector = %d, mem to put VSR in is at %08x", vector,
                         vsr);
     CYG_ASSERT( vector >= CYGNUM_HAL_VSR_MIN, "Invalid vector");
     CYG_ASSERT( vector <= CYGNUM_HAL_VSR_MAX, "Invalid vector");
     HAL_VSR_GET( vector, vsr );
     CYG_REPORT_RETURN();
 }
static cyg_bool Cyg_Interrupt::interrupts_enabled () inline static
Definition at line 318 of file intr.hxx.
References CYG_KERNEL_CPU_THIS.
     {
         return (0 == disable_counter[CYG_KERNEL_CPU_THIS()]);
     }
void Cyg_Interrupt::mask_interrupt (cyg_vector vector) static
Definition at line 669 of file intr.cxx.
References CYG_ASSERT, CYG_REPORT_FUNCARG1, CYG_REPORT_FUNCTION, and CYG_REPORT_RETURN.
 {
     CYG_REPORT_FUNCTION();
     CYG_REPORT_FUNCARG1("vector=%d", vector);
     CYG_ASSERT( vector >= CYGNUM_HAL_ISR_MIN, "Invalid vector");
     CYG_ASSERT( vector <= CYGNUM_HAL_ISR_MAX, "Invalid vector");
     CYG_INSTRUMENT_INTR(MASK, vector, 0);
     CYG_INTERRUPT_STATE old_ints;
     HAL_DISABLE_INTERRUPTS(old_ints);
     HAL_INTERRUPT_MASK( vector );
     HAL_RESTORE_INTERRUPTS(old_ints);
     CYG_REPORT_RETURN();
 }
void Cyg_Interrupt::mask_interrupt_intunsafe (cyg_vector vector) static
Definition at line 692 of file intr.cxx.
References CYG_ASSERT, CYG_REPORT_FUNCARG1, CYG_REPORT_FUNCTION, and CYG_REPORT_RETURN.
 {
     CYG_REPORT_FUNCTION();
     CYG_REPORT_FUNCARG1("vector=%d", vector);
     CYG_ASSERT( vector >= CYGNUM_HAL_ISR_MIN, "Invalid vector");
     CYG_ASSERT( vector <= CYGNUM_HAL_ISR_MAX, "Invalid vector");
     CYG_INSTRUMENT_INTR(MASK, vector, 0);
     HAL_INTERRUPT_MASK( vector );
     CYG_REPORT_RETURN();
 }
void Cyg_Interrupt::post_dsr (void) private
Definition at line 256 of file intr.cxx.
References CYG_ASSERT, CYG_KERNEL_CPU_THIS, HAL_SMP_CPU_TYPE, and vector.
Referenced by cyg_interrupt_post_dsr(), and interrupt_end().
 {
 //    CYG_REPORT_FUNCTION();
     HAL_SMP_CPU_TYPE cpu = CYG_KERNEL_CPU_THIS();
     CYG_INSTRUMENT_INTR(POST_DSR, vector, 0);
     cyg_uint32 old_intr;
     // We need to disable interrupts during this part to
     // guard against nested interrupts.
     HAL_DISABLE_INTERRUPTS(old_intr);
 #ifdef CYGIMP_KERNEL_INTERRUPTS_DSRS_TABLE
     dsr_table[cpu][dsr_table_tail[cpu]++] = this;
     if( dsr_table_tail[cpu] >= CYGNUM_KERNEL_INTERRUPTS_DSRS_TABLE_SIZE )
         dsr_table_tail[cpu] = 0;
 #endif
 #ifdef CYGIMP_KERNEL_INTERRUPTS_DSRS_LIST
     // Only add the interrupt to the dsr list if this is
     // the first DSR call.
     if( dsr_count++ == 0 )
     {
 #  ifdef CYGSEM_KERNEL_INTERRUPTS_DSRS_LIST_FIFO
         // Add to the tail of the list.
         Cyg_Interrupt* tail = dsr_list_tail[cpu];
         dsr_list_tail[cpu] = this;
         if( tail )
         {
             CYG_ASSERT( 0 != dsr_list[cpu] ,
               "DSR list is not empty but its head is 0");
             tail->next_dsr = this;
         }
         else
         {
             CYG_ASSERT( 0 == dsr_list[cpu] ,
               "DSR list tail is 0 but its head is not");
             dsr_list[cpu] = this;
         }
 #  else   // ! defined CYGSEM_KERNEL_INTERRUPTS_DSRS_LIST_FIFO
         // At present DSRs are pushed onto the list and will be called
         // in reverse order. We do not define the order in which DSRs
         // are called, so this is acceptable.
         next_dsr = dsr_list[cpu];
         dsr_list[cpu] = this;
 #  endif  // ! defined CYGSEM_KERNEL_INTERRUPTS_DSRS_LIST_FIFO
     }
 #endif  // defined CYGIMP_KERNEL_INTERRUPTS_DSRS_LIST
     HAL_RESTORE_INTERRUPTS(old_intr);
 };
void Cyg_Interrupt::set_vsr (cyg_vector vector, cyg_VSR * vsr, cyg_VSR ** old = NULL) static
Definition at line 587 of file intr.cxx.
References CYG_ASSERT, CYG_REPORT_FUNCARG3, CYG_REPORT_FUNCTION, and CYG_REPORT_RETURN.
 {
     CYG_REPORT_FUNCTION();
     CYG_REPORT_FUNCARG3( "vector = %d, new vsr is at %08x, mem to put "
                          "old VSR in is at %08x", vector, vsr, old);
     CYG_INSTRUMENT_INTR(SET_VSR, vector, vsr);
     CYG_ASSERT( vector >= CYGNUM_HAL_VSR_MIN, "Invalid vector");
     CYG_ASSERT( vector <= CYGNUM_HAL_VSR_MAX, "Invalid vector");
     CYG_INTERRUPT_STATE old_ints;
     HAL_DISABLE_INTERRUPTS(old_ints);
     HAL_VSR_SET( vector, vsr, old );
     HAL_RESTORE_INTERRUPTS(old_ints);
     CYG_REPORT_RETURN();
 }
void Cyg_Interrupt::unmask_interrupt (cyg_vector vector) static
Definition at line 712 of file intr.cxx.
References CYG_ASSERT, CYG_REPORT_FUNCTION, and CYG_REPORT_RETURN.
 {
     CYG_REPORT_FUNCTION();
     CYG_ASSERT( vector >= CYGNUM_HAL_ISR_MIN, "Invalid vector");
     CYG_ASSERT( vector <= CYGNUM_HAL_ISR_MAX, "Invalid vector");
     CYG_INSTRUMENT_INTR(UNMASK, vector, 0);
     CYG_INTERRUPT_STATE old_ints;
     HAL_DISABLE_INTERRUPTS(old_ints);
     HAL_INTERRUPT_UNMASK( vector );
     HAL_RESTORE_INTERRUPTS(old_ints);
     CYG_REPORT_RETURN();
 }
void Cyg_Interrupt::unmask_interrupt_intunsafe (cyg_vector vector) static
Definition at line 735 of file intr.cxx.
References CYG_ASSERT, CYG_REPORT_FUNCTION, and CYG_REPORT_RETURN.
 {
     CYG_REPORT_FUNCTION();
     CYG_ASSERT( vector >= CYGNUM_HAL_ISR_MIN, "Invalid vector");
     CYG_ASSERT( vector <= CYGNUM_HAL_ISR_MAX, "Invalid vector");
     CYG_INSTRUMENT_INTR(UNMASK, vector, 0);
     HAL_INTERRUPT_UNMASK( vector );
     CYG_REPORT_RETURN();
 }
Friends And Related Function Documentation
void cyg_interrupt_call_pending_DSRs (void) friend
Definition at line 233 of file intr.cxx.
 {
     Cyg_Interrupt::call_pending_DSRs_inner();
 }
void cyg_interrupt_post_dsr (CYG_ADDRWORD intr_obj) friend
Definition at line 324 of file intr.cxx.
 {
     Cyg_Interrupt* intr = (Cyg_Interrupt*) intr_obj;
     intr->post_dsr ();
 }
friend class Cyg_Scheduler friend
Definition at line 128 of file intr.hxx.
void interrupt_end (cyg_uint32 , Cyg_Interrupt * , HAL_SavedRegisters *) friend
Definition at line 334 of file intr.cxx.
 {
 //    CYG_REPORT_FUNCTION();
 #ifdef CYGPKG_KERNEL_SMP_SUPPORT
     Cyg_Scheduler::lock();
 #endif
     // Sometimes we have a NULL intr object pointer.
     cyg_vector vector = (intr!=NULL)?intr->vector:0;
     CYG_INSTRUMENT_INTR(END, vector, isr_ret);
     CYG_UNUSED_PARAM( cyg_vector, vector ); // prevent compiler warning
 #ifndef CYGIMP_KERNEL_INTERRUPTS_CHAIN
     // Only do this if we are in a non-chained configuration.
     // If we are chained, then chain_isr below will do the DSR
     // posting.
     if( isr_ret & Cyg_Interrupt::CALL_DSR && intr != NULL ) intr->post_dsr();
 #endif
 #ifdef CYGDBG_KERNEL_DEBUG_GDB_THREAD_SUPPORT
     // If we have GDB support enabled, and there is the possibility
     // that this thread will be context switched as a result of this
     // interrupt, then save the pointer to the saved thread context in
     // the thread object so that GDB can get a meaningful context to
     // look at.
     Cyg_Scheduler::get_current_thread()->set_saved_context(regs);
 #endif
     // Now unlock the scheduler, which may also call DSRs
     // and cause a thread switch to happen.
     Cyg_Scheduler::unlock();
 #ifdef CYGDBG_KERNEL_DEBUG_GDB_THREAD_SUPPORT
     Cyg_Scheduler::get_current_thread()->set_saved_context(0);
 #endif
     CYG_INSTRUMENT_INTR(RESTORE, vector, 0);
 }
Member Data Documentation
volatile cyg_int32 disable_counter [CYGNUM_KERNEL_CPU_MAX] Cyg_Interrupt::CYGBLD_ANNOTATE_VARIABLE_INTR static private
Definition at line 256 of file intr.hxx.
Cyg_SpinLock interrupt_disable_spinlock Cyg_Interrupt::CYGBLD_ANNOTATE_VARIABLE_INTR static private
Definition at line 260 of file intr.hxx.
CYG_INTERRUPT_STATE interrupt_disable_state [CYGNUM_KERNEL_CPU_MAX] Cyg_Interrupt::CYGBLD_ANNOTATE_VARIABLE_INTR static private
Definition at line 266 of file intr.hxx.
CYG_ADDRWORD Cyg_Interrupt::data private
Definition at line 143 of file intr.hxx.
Referenced by call_pending_DSRs_inner(), and Cyg_Interrupt().
cyg_DSR* Cyg_Interrupt::dsr private
Definition at line 141 of file intr.hxx.
Referenced by call_pending_DSRs_inner(), and Cyg_Interrupt().
cyg_ISR* Cyg_Interrupt::isr private
Definition at line 139 of file intr.hxx.
Referenced by attach(), Cyg_Interrupt(), and detach().
cyg_priority Cyg_Interrupt::priority private
Definition at line 137 of file intr.hxx.
Referenced by attach(), and Cyg_Interrupt().
cyg_vector Cyg_Interrupt::vector private
Definition at line 135 of file intr.hxx.
Referenced by call_pending_DSRs_inner(), Cyg_Interrupt(), get_vector(), interrupt_end(), and post_dsr().
The documentation for this class was generated from the following files:
C:/Users/barry/Documents/GitHub/VEROS/Xinrui/20130621_refined_thread/intr.hxx
C:/Users/barry/Documents/GitHub/VEROS/Xinrui/20130621_refined_thread/intr.cxx