My Project: Cyg_Thread Class Reference
Cyg_Thread Class Reference
#include <thread.hxx>
Public Types
enum {
RUNNING = 0, SLEEPING = 1, COUNTSLEEP = 2, SUSPENDED = 4,
CREATING = 8, EXITED = 16, SLEEPSET = (SLEEPING | COUNTSLEEP)
}
enum cyg_reason {
NONE, WAIT, DELAY, TIMEOUT,
BREAK, DESTRUCT, EXIT, DONE
}
Public Member Functions
CYGDBG_DEFINE_CHECK_THIS Cyg_Thread (cyg_thread_entry *entry, CYG_ADDRWORD entry_data, cyg_ucount32 stack_size=0, CYG_ADDRESS stack_base=0)
Cyg_Thread (CYG_ADDRWORD sched_info, cyg_thread_entry *entry, CYG_ADDRWORD entry_data, char *name, CYG_ADDRESS stack_base=0, cyg_ucount32 stack_size=0)
void reinitialize ()
~Cyg_Thread ()
void to_queue_head (void)
void wake ()
void counted_wake ()
cyg_uint32 cancel_counted_wake ()
void suspend ()
void resume ()
void release ()
void kill ()
void force_resume ()
cyg_uint32 get_state ()
void set_wait_info (CYG_ADDRWORD data)
CYG_ADDRWORD get_wait_info ()
void delay (cyg_tick_count delay)
void set_priority (cyg_priority pri)
cyg_priority get_priority ()
cyg_priority get_current_priority ()
cyg_reason get_sleep_reason ()
void set_wake_reason (cyg_reason reason=DONE)
cyg_reason get_wake_reason ()
cyg_uint16 get_unique_id ()
Public Member Functions inherited from Cyg_HardwareThread
CYGDBG_DEFINE_CHECK_THIS void set_entry_data (CYG_ADDRWORD data)
CYG_ADDRWORD get_entry_data ()
CYG_ADDRESS get_stack_base ()
cyg_uint32 get_stack_size ()
Public Member Functions inherited from Cyg_SchedThread
Cyg_SchedThread (Cyg_Thread *thread, CYG_ADDRWORD sched_info)
Cyg_ThreadQueue * get_current_queue ()
void remove ()
void set_asr_inhibit ()
void clear_asr_inhibit ()
Public Member Functions inherited from Cyg_SchedThread_Implementation
void timeslice_enable ()
void timeslice_disable ()
Public Member Functions inherited from Cyg_DNode_T< Cyg_Thread >
Cyg_DNode_T ()
~Cyg_DNode_T ()
Cyg_Thread * get_next ()
Cyg_Thread * get_prev ()
Public Member Functions inherited from Cyg_DNode
Cyg_DNode ()
Cyg_DNode * get_next ()
Cyg_DNode * get_prev ()
cyg_bool in_list ()
void insert (Cyg_DNode *node)
void append (Cyg_DNode *node)
void unlink ()
~Cyg_DNode ()
Static Public Member Functions
static void sleep ()
static void counted_sleep ()
static void counted_sleep (cyg_tick_count delay)
static void exit ()
static void yield ()
static void rotate_queue (cyg_priority pri)
static Cyg_Thread * self ()
static void set_sleep_reason (cyg_reason reason=WAIT)
static void set_timer (cyg_tick_count trigger, cyg_reason sleep_reason)
static void clear_timer ()
Private Attributes
cyg_uint32 state
cyg_ucount32 suspend_count
cyg_ucount32 wakeup_count
CYG_ADDRWORD wait_info
cyg_uint16 unique_id
Cyg_ThreadTimer timer
cyg_reason sleep_reason
cyg_reason wake_reason
Friends
class Cyg_Scheduler
void deliver_exception (CYG_WORD code, CYG_ADDRWORD data)
Additional Inherited Members
Protected Member Functions inherited from Cyg_HardwareThread
Cyg_HardwareThread (cyg_thread_entry *entry_point, CYG_ADDRWORD entry_data, cyg_ucount32 stack_size=0, CYG_ADDRESS stack_base=0)
void init_context (Cyg_Thread *thread)
void switch_context (Cyg_HardwareThread *next)
void attach_stack (CYG_ADDRESS stack, cyg_uint32 stack_size)
CYG_ADDRESS detach_stack ()
void prepare_exception (cyg_exception_handler *exception_handler, CYG_ADDRWORD exception_data, cyg_code exception_number, CYG_ADDRWORD exception_info)
Protected Member Functions inherited from Cyg_SchedThread_Implementation
Cyg_SchedThread_Implementation (CYG_ADDRWORD sched_info)
void yield ()
void to_queue_head (void)
void timeslice_save ()
void timeslice_restore ()
void timeslice_reset ()
Static Protected Member Functions inherited from Cyg_HardwareThread
static void thread_entry (Cyg_Thread *thread)
Static Protected Member Functions inherited from Cyg_SchedThread_Implementation
static void rotate_queue (cyg_priority pri)
Protected Attributes inherited from Cyg_HardwareThread
CYG_ADDRESS stack_base
cyg_uint32 stack_size
CYG_ADDRESS stack_ptr
cyg_thread_entry * entry_point
CYG_ADDRWORD entry_data
Protected Attributes inherited from Cyg_SchedThread_Implementation
cyg_priority priority
cyg_ucount32 timeslice_count
cyg_bool timeslice_enabled
Detailed Description
Definition at line 209 of file thread.hxx.
Member Enumeration Documentation
anonymous enum
Enumerator
RUNNING
SLEEPING
COUNTSLEEP
SUSPENDED
CREATING
EXITED
SLEEPSET
Definition at line 220 of file thread.hxx.
          {                       // Thread state values
         RUNNING    = 0,          // Thread is runnable or running
         SLEEPING   = 1,          // Thread is waiting for something to happen
         COUNTSLEEP = 2,          // Sleep in counted manner
         SUSPENDED  = 4,          // Suspend count is non-zero
         CREATING   = 8,          // Thread is being created
         EXITED     = 16,         // Thread has exited
         // This is the set of bits that must be cleared by a generic
         // wake() or release().
         SLEEPSET   = (SLEEPING | COUNTSLEEP)
     };
enum Cyg_Thread::cyg_reason
Enumerator
NONE
WAIT
DELAY
TIMEOUT
BREAK
DESTRUCT
EXIT
DONE
Definition at line 383 of file thread.hxx.
     {
         NONE,                           // No recorded reason
         WAIT,                           // Wait with no timeout
         DELAY,                          // Simple time delay
         TIMEOUT,                        // Wait with timeout/timeout expired
         BREAK,                          // forced break out of sleep
         DESTRUCT,                       // wait object destroyed[note]
         EXIT,                           // forced termination
         DONE                            // Wait/delay complete
     };
Constructor & Destructor Documentation
CYGDBG_DEFINE_CHECK_THIS Cyg_Thread::Cyg_Thread (cyg_thread_entry * entry, CYG_ADDRWORD entry_data, cyg_ucount32 stack_size = 0, CYG_ADDRESS stack_base = 0)
Referenced by reinitialize().
Cyg_Thread::Cyg_Thread (CYG_ADDRWORD sched_info, cyg_thread_entry * entry, CYG_ADDRWORD entry_data, char * name, CYG_ADDRESS stack_base = 0, cyg_ucount32 stack_size = 0)
Definition at line 171 of file thread.cxx.
References CYG_REPORT_FUNCTION, CYG_REPORT_RETURN, Cyg_HardwareThread::init_context(), NONE, NULL, sleep_reason, state, suspend_count, SUSPENDED, unique_id, wake_reason, and wakeup_count.
 :   Cyg_HardwareThread(entry, entry_data, stack_size, stack_base),
     Cyg_SchedThread(this, sched_info)
 //#ifdef CYGFUN_KERNEL_THREADS_TIMER
     ,timer(this)
 //#endif
 {
     CYG_REPORT_FUNCTION();
     CYG_INSTRUMENT_THREAD(CREATE,this,0);
     // Start the thread in suspended state.
     state               = SUSPENDED;
     suspend_count       = 1;
     wakeup_count        = 0;
     // Initialize sleep_reason which is used by kill, release
     sleep_reason        = NONE;
     wake_reason         = NONE;
     // Assign a 16 bit id to the thread.
     unique_id           = next_unique_id++;
 #ifdef CYGVAR_KERNEL_THREADS_DATA
     // Zero all per-thread data entries.
     for( int i = 0; i < CYGNUM_KERNEL_THREADS_DATA_MAX; i++ )
         thread_data[i] = 0;
 #endif
 #ifdef CYGSEM_KERNEL_THREADS_DESTRUCTORS_PER_THREAD
     for (int j=0; j<CYGNUM_KERNEL_THREADS_DESTRUCTORS; j++) {
         destructors[j].fn = NULL;
     }
 #endif
 #ifdef CYGVAR_KERNEL_THREADS_NAME
     name = name_arg;
 #endif
 #ifdef CYGVAR_KERNEL_THREADS_LIST
     // Add thread to housekeeping list
     add_to_list();
 #endif
     Cyg_Scheduler::scheduler.register_thread(this);
     init_context(this);
     CYG_REPORT_RETURN();
 }
Cyg_Thread::~Cyg_Thread ()
Definition at line 272 of file thread.cxx.
References CYG_REPORT_FUNCTION, CYG_REPORT_RETURN, and unique_id.
 {
     CYG_REPORT_FUNCTION();
     Cyg_Scheduler::scheduler.deregister_thread(this);
 #ifdef CYGVAR_KERNEL_THREADS_LIST //On but don't care
     // Remove thread from housekeeping list.
     remove_from_list();
 #endif
     // Zero the unique_id to render this thread inconsistent.
     unique_id = 0;
     CYG_REPORT_RETURN();
 }
Member Function Documentation
cyg_uint32 Cyg_Thread::cancel_counted_wake ()
Definition at line 536 of file thread.cxx.
References CYG_REPORT_FUNCTION, CYG_REPORT_RETVAL, Cyg_Scheduler_Base::get_current_thread(), Cyg_Scheduler::lock(), Cyg_Scheduler::unlock(), and wakeup_count.
 {
     CYG_REPORT_FUNCTION();
     CYG_INSTRUMENT_THREAD(WAKE,this,Cyg_Scheduler::get_current_thread());
     // Prevent preemption
     Cyg_Scheduler::lock();
     cyg_uint32 result = wakeup_count;
     wakeup_count = 0;
     // Unlock the scheduler
     Cyg_Scheduler::unlock();
     CYG_REPORT_RETVAL( result );
     return result;
 }
void Cyg_Thread::clear_timer () inline static
Definition at line 473 of file thread.inl.
References Cyg_Alarm::disable(), and timer.
Referenced by counted_sleep(), delay(), and exit().
 {
     self()->timer.disable();
 }
void Cyg_Thread::counted_sleep () static
Definition at line 399 of file thread.cxx.
References COUNTSLEEP, CYG_REPORT_FUNCTION, CYG_REPORT_RETURN, DESTRUCT, exit(), EXIT, Cyg_Scheduler_Base::get_current_thread(), Cyg_Scheduler::lock(), set_sleep_reason(), sleep(), state, Cyg_Scheduler::unlock(), WAIT, wake_reason, and wakeup_count.
 {
     CYG_REPORT_FUNCTION();
     Cyg_Thread *current = Cyg_Scheduler::get_current_thread();
     CYG_ASSERTCLASS( current, "Bad current thread" );
     CYG_INSTRUMENT_THREAD(SLEEP,current,0);
     // Prevent preemption
     Cyg_Scheduler::lock();
     if ( 0 == current->wakeup_count ) {
         set_sleep_reason( Cyg_Thread::WAIT );
         current->sleep();               // prepare to sleep
         current->state |= COUNTSLEEP;   // Set the state
     }
     else
         // there is a queued wakeup, do not sleep
         current->wakeup_count--;
     // Unlock the scheduler and switch threads
     Cyg_Scheduler::unlock();
     // and deal with anything we must do when we return
     switch( current->wake_reason ) {
     case DESTRUCT:
     case EXIT:
         current->exit();
         break;
     default:
         break;
     }
     CYG_REPORT_RETURN();
 }
void Cyg_Thread::counted_sleep (cyg_tick_count delay) static
Definition at line 445 of file thread.cxx.
References clear_timer(), COUNTSLEEP, CYG_REPORT_FUNCTION, CYG_REPORT_RETURN, DESTRUCT, exit(), EXIT, Cyg_Scheduler_Base::get_current_thread(), get_wake_reason(), Cyg_Scheduler::lock(), NONE, Cyg_Clock::real_time_clock, Cyg_Scheduler::reschedule(), set_sleep_reason(), set_timer(), sleep(), state, TIMEOUT, Cyg_Scheduler::unlock(), wake_reason, and wakeup_count.
 {
     CYG_REPORT_FUNCTION();
     Cyg_Thread *current = Cyg_Scheduler::get_current_thread();
     CYG_ASSERTCLASS( current, "Bad current thread" );
     CYG_INSTRUMENT_THREAD(SLEEP,current,0);
     // Prevent preemption
     Cyg_Scheduler::lock();
     if ( 0 == current->wakeup_count ) {
         // Set the timer (once outside any waiting loop.)
         set_timer( Cyg_Clock::real_time_clock->current_value()+delay,
                          Cyg_Thread::TIMEOUT  );
         // If the timeout is in the past, the wake reason will have been
         // set to something other than NONE already.
         if( current->get_wake_reason() == Cyg_Thread::NONE )
         {
             set_sleep_reason( Cyg_Thread::TIMEOUT );
             current->sleep();               // prepare to sleep
             current->state |= COUNTSLEEP;   // Set the state
             Cyg_Scheduler::reschedule();
             // clear the timer; if it actually fired, no worries.
             clear_timer();
         }
     }
     else
         // there is a queued wakeup, do not sleep
         current->wakeup_count--;
     // Unlock the scheduler and switch threads
     Cyg_Scheduler::unlock();
     // and deal with anything we must do when we return
     switch( current->wake_reason ) {
     case DESTRUCT:
     case EXIT:
         current->exit();
         break;
     default:
         break;
     }
     CYG_REPORT_RETURN();
 }
void Cyg_Thread::counted_wake ()
Definition at line 505 of file thread.cxx.
References COUNTSLEEP, CYG_ASSERT, CYG_REPORT_FUNCTION, CYG_REPORT_RETURN, DONE, Cyg_Scheduler_Base::get_current_thread(), Cyg_Scheduler::lock(), NONE, sleep_reason, state, Cyg_Scheduler::unlock(), wake(), wake_reason, and wakeup_count.
 {
     CYG_REPORT_FUNCTION();
     CYG_INSTRUMENT_THREAD(WAKE,this,Cyg_Scheduler::get_current_thread());
     // Prevent preemption
     Cyg_Scheduler::lock();
     if ( 0 == (state & COUNTSLEEP) )    // already awake, or waiting:
         wakeup_count++;                 // not in a counted sleep anyway.
     else {
         sleep_reason = NONE;
         wake_reason = DONE;
         wake();                         // and awaken the thread
     }
 #ifdef CYGNUM_KERNEL_MAX_COUNTED_WAKE_COUNT_ASSERT
     CYG_ASSERT( CYGNUM_KERNEL_MAX_COUNTED_WAKE_COUNT_ASSERT > wakeup_count,
                 "wakeup_count overflow" );
 #endif
     // Unlock the scheduler and maybe switch threads
     Cyg_Scheduler::unlock();
     CYG_REPORT_RETURN();
 }
void Cyg_Thread::delay (cyg_tick_count delay)
Definition at line 959 of file thread.cxx.
References clear_timer(), CYG_REPORT_FUNCTION, CYG_REPORT_RETURN, DELAY, DESTRUCT, exit(), EXIT, Cyg_Scheduler::lock(), Cyg_Clock::real_time_clock, set_timer(), sleep(), Cyg_Scheduler::unlock(), and wake_reason.
 {
     CYG_REPORT_FUNCTION();
 //#ifdef CYGFUN_KERNEL_THREADS_TIMER
     CYG_INSTRUMENT_THREAD(DELAY,this,delay);
     // Prevent preemption
     Cyg_Scheduler::lock();
     sleep();
     set_timer( Cyg_Clock::real_time_clock->current_value()+delay, DELAY );
     // Unlock the scheduler and maybe switch threads
     Cyg_Scheduler::unlock();
     // Clear the timeout. It is irrelevant whether the alarm has
     // actually gone off or not.
     clear_timer();
     // and deal with anything else we must do when we return
     switch( wake_reason ) {
     case DESTRUCT:
     case EXIT:
         exit();
         break;
     default:
         break;
     }
 //#endif
     CYG_REPORT_RETURN();
 }
void Cyg_Thread::exit () static
Definition at line 733 of file thread.cxx.
References clear_timer(), CYG_REPORT_FUNCTION, EXITED, Cyg_Scheduler::lock(), NULL, Cyg_Scheduler::reschedule(), self(), and state.
Referenced by counted_sleep(), delay(), kill(), and Cyg_HardwareThread::thread_entry().
 {
     CYG_REPORT_FUNCTION();
     // The thread should never return from this function.
     Cyg_Thread *self = Cyg_Thread::self();
 #ifdef CYGPKG_KERNEL_THREADS_DESTRUCTORS
     cyg_ucount16 i;
     for (i=0; i<CYGNUM_KERNEL_THREADS_DESTRUCTORS; i++) {
         if (NULL != self->destructors[i].fn) {
             destructor_fn fn = self->destructors[i].fn;
             CYG_ADDRWORD data = self->destructors[i].data;
             fn(data);
         }
     }
 #endif
 #ifdef CYGDBG_KERNEL_THREADS_STACK_MEASUREMENT_VERBOSE_EXIT
     diag_printf( "Stack usage for thread %08x: %d\n", self,
          self->measure_stack_usage() );
 #endif
     Cyg_Scheduler::lock();
     // clear the timer; if there was none, no worries.
     clear_timer();
     // It is possible that we have already been killed by another
     // thread, in which case we do not want to try and take ourself
     // out of the scheduler again.
     if( self->state != EXITED )
     {
         self->state = EXITED;
         Cyg_Scheduler::scheduler.rem_thread(self);
     }
     Cyg_Scheduler::reschedule();
 }
void Cyg_Thread::force_resume ()
Definition at line 634 of file thread.cxx.
References CYG_ASSERT, CYG_REPORT_FUNCTION, CYG_REPORT_RETURN, Cyg_Scheduler_Base::get_current_thread(), Cyg_Scheduler::lock(), RUNNING, state, suspend_count, and Cyg_Scheduler::unlock().
Referenced by kill().
 {
     CYG_REPORT_FUNCTION();
     CYG_INSTRUMENT_THREAD(RESUME,this,Cyg_Scheduler::get_current_thread());
     // Prevent preemption
     Cyg_Scheduler::lock();
     // If we are about to zero the count, clear the state bit and
     // reschedule the thread if possible.
     if ( 0 < suspend_count ) {
         suspend_count = 0;
         CYG_ASSERT( (state & SUSPENDED) != 0, "SUSPENDED bit not set" );
         // Set the state
         state &= ~SUSPENDED;
         // Return thread to scheduler if runnable
         if( state == RUNNING )
             Cyg_Scheduler::scheduler.add_thread(this);
     }
     // Unlock the scheduler and maybe switch threads
     Cyg_Scheduler::unlock();
     CYG_REPORT_RETURN();
 }
cyg_priority Cyg_Thread::get_current_priority ()
cyg_priority Cyg_Thread::get_priority ()
Referenced by reinitialize().
Cyg_Thread::cyg_reason Cyg_Thread::get_sleep_reason () inline
Definition at line 437 of file thread.inl.
References sleep_reason.
Referenced by Cyg_ThreadTimer::alarm().
 {
     return sleep_reason;
 }
cyg_uint32 Cyg_Thread::get_state () inline
Definition at line 547 of file thread.hxx.
References state.
Referenced by Cyg_Scheduler_Implementation::timeslice_cpu(), and Cyg_SchedThread_Implementation::yield().
 {
     return state;
 }
cyg_uint16 Cyg_Thread::get_unique_id () inline
Definition at line 302 of file thread.inl.
References unique_id.
Referenced by Cyg_HardwareThread::init_context().
 {
     return unique_id;
 }
CYG_ADDRWORD Cyg_Thread::get_wait_info () inline
Definition at line 557 of file thread.hxx.
References wait_info.
 {
     return wait_info;
 }
Cyg_Thread::cyg_reason Cyg_Thread::get_wake_reason () inline
Definition at line 452 of file thread.inl.
References wake_reason.
Referenced by counted_sleep().
 {
     return wake_reason;
 }
void Cyg_Thread::kill ()
Definition at line 779 of file thread.cxx.
References BREAK, CYG_REPORT_FUNCTION, CYG_REPORT_RETURN, DELAY, DESTRUCT, Cyg_Alarm::disable(), DONE, exit(), EXIT, EXITED, force_resume(), Cyg_Scheduler_Base::get_current_thread(), Cyg_Scheduler::lock(), NONE, RUNNING, sleep_reason, state, TIMEOUT, timer, Cyg_Scheduler::unlock(), WAIT, wake(), and wake_reason.
 {
     CYG_REPORT_FUNCTION();
     // If this is called by the current thread on itself,
     // just call exit(), which is what he should have done
     // in the first place.
     if( this == Cyg_Scheduler::get_current_thread() )
         exit();
     // Prevent preemption
     Cyg_Scheduler::lock();
     // We are killing someone else. Find out what state he is
     // in and force him to wakeup and call exit().
     force_resume();                     // this is necessary for when
                                         // he is asleep AND suspended.
 //#ifdef CYGFUN_KERNEL_THREADS_TIMER
     timer.disable();                    // and make sure the timer
                                         // does not persist.
 //#endif
     if ( EXIT != wake_reason ) switch( sleep_reason ) {
         // Only do any of this if the thread is not in pending death already:
     case NONE:
         // The thread is not sleeping for any reason, it must be
         // on a run queue.
         // We can safely deschedule and set its state.
         if( state == RUNNING ) Cyg_Scheduler::scheduler.rem_thread(this);
         state = EXITED;
         break;
     case DESTRUCT:
     case BREAK:
     case EXIT:
     case DONE:
         // Do nothing in any of these cases. They are here to
         // keep the compiler happy.
         Cyg_Scheduler::unlock();
         CYG_REPORT_RETURN();
         return;
     case WAIT:
         // The thread was waiting for some sync object to do
         // something.
         // drop through...
     case TIMEOUT:
         // The thread was waiting on a sync object with a timeout.
         // drop through...
     case DELAY:
         // The thread was simply delaying, unless it has been
         // woken up for some other reason, wake it now.
         sleep_reason = NONE;
         wake_reason = EXIT;
         break;
     }
     wake();
     // Allow preemption
     Cyg_Scheduler::unlock();
     CYG_REPORT_RETURN();
 }
void Cyg_Thread::reinitialize ()
Definition at line 233 of file thread.cxx.
References CYG_ASSERT, CYG_REPORT_FUNCTION, CYG_REPORT_RETURN, Cyg_Thread(), Cyg_Alarm::disable(), Cyg_HardwareThread::entry_data, Cyg_HardwareThread::entry_point, Cyg_SchedThread::get_current_queue(), Cyg_Scheduler_Base::get_current_thread(), get_priority(), Cyg_HardwareThread::get_stack_base(), Cyg_HardwareThread::get_stack_size(), NULL, and timer.
 {
     CYG_REPORT_FUNCTION();
     CYG_ASSERTCLASS( this, "Bad thread");
     CYG_ASSERT( this != Cyg_Scheduler::get_current_thread(),
                 "Attempt to reinitialize current thread");
     CYG_ASSERT( get_current_queue() == NULL , "Thread is still on a queue");
 //#ifdef CYGFUN_KERNEL_THREADS_TIMER
     // Clear the timeout. It is irrelevant whether there was
     // actually a timeout pending.
     timer.disable();
 //#endif
     // Ensure the scheduler has let go of us.
     Cyg_Scheduler::scheduler.deregister_thread(this);
     cyg_priority pri = get_priority();
 #ifdef CYGVAR_KERNEL_THREADS_NAME //On but don't care.
     char * name_arg = name;
 #else
     char * name_arg = NULL;
 #endif
     new(this) Cyg_Thread( pri,
                           entry_point, entry_data,
                           name_arg,
                           get_stack_base(), get_stack_size() );
     // the constructor re-registers the thread with the scheduler.
     CYG_ASSERTCLASS( this, "Thread corrupted by reinitialize");
     CYG_REPORT_RETURN();
 }
void Cyg_Thread::release ()
Definition at line 670 of file thread.cxx.
References BREAK, CYG_REPORT_FUNCTION, CYG_REPORT_RETURN, DELAY, DESTRUCT, DONE, EXIT, Cyg_Scheduler::lock(), NONE, sleep_reason, TIMEOUT, Cyg_Scheduler::unlock(), WAIT, wake(), and wake_reason.
 {
     CYG_REPORT_FUNCTION();
     // Prevent preemption
     Cyg_Scheduler::lock();
     // If the thread is in any of the sleep states, set the
     // wake reason and wake it up.
     switch( sleep_reason )
     {
     case NONE:
         // The thread is not sleeping for any reason, do nothing.
         // drop through...
     case DESTRUCT:
     case BREAK:
     case EXIT:
     case DONE:
         // Do nothing in any of these cases. They are here to
         // keep the compiler happy.
         Cyg_Scheduler::unlock();
         CYG_REPORT_RETURN();
         return;
     case WAIT:
         // The thread was waiting for some sync object to do
         // something.
         // drop through...
     case TIMEOUT:
         // The thread was waiting on a sync object with a timeout.
         // drop through...
     case DELAY:
         // The thread was simply delaying, unless it has been
         // woken up for some other reason, wake it now.
         sleep_reason = NONE;
         wake_reason = BREAK;
         break;
     }
     wake();
     // Allow preemption
     Cyg_Scheduler::unlock();
     CYG_REPORT_RETURN();
 }
void Cyg_Thread::resume ()
Definition at line 594 of file thread.cxx.
References CYG_ASSERT, CYG_REPORT_FUNCTION, CYG_REPORT_RETURN, Cyg_Scheduler_Base::get_current_thread(), Cyg_Scheduler::lock(), RUNNING, state, suspend_count, and Cyg_Scheduler::unlock().
Referenced by Cyg_Scheduler_Implementation::set_idle_thread().
 {
     CYG_REPORT_FUNCTION();
     CYG_INSTRUMENT_THREAD(RESUME,this,Cyg_Scheduler::get_current_thread());
     // Prevent preemption
     Cyg_Scheduler::lock();
     // If we are about to zero the count, clear the state bit and
     // reschedule the thread if possible.
     if( suspend_count == 1 )
     {
         suspend_count = 0;
         CYG_ASSERT( (state & SUSPENDED) != 0, "SUSPENDED bit not set" );
         // Set the state
         state &= ~SUSPENDED;
         // Return thread to scheduler if runnable
         if( state == RUNNING )
             Cyg_Scheduler::scheduler.add_thread(this);
     }
     else
         if( suspend_count > 0 )
             suspend_count--;
     // else ignore attempt to resume
     // Unlock the scheduler and maybe switch threads
     Cyg_Scheduler::unlock();
     CYG_REPORT_RETURN();
 }
void Cyg_Thread::rotate_queue (cyg_priority pri) inline static
Definition at line 387 of file thread.inl.
References Cyg_SchedThread_Implementation::rotate_queue().
 {
     self()->Cyg_SchedThread::rotate_queue( pri );
 }
Cyg_Thread * Cyg_Thread::self () inline static
Definition at line 372 of file thread.inl.
References Cyg_Scheduler_Base::get_current_thread().
Referenced by exit().
 {
     return Cyg_Scheduler::get_current_thread();
 }
void Cyg_Thread::set_priority (cyg_priority pri)
Definition at line 853 of file thread.cxx.
References CYG_ASSERT, CYG_CHECK_DATA_PTR, CYG_REPORT_FUNCTION, CYG_REPORT_RETURN, Cyg_ThreadQueue::enqueue(), Cyg_SchedThread::get_current_queue(), Cyg_Scheduler_Base::get_current_thread(), Cyg_Scheduler::lock(), NULL, Cyg_SchedThread_Implementation::priority, Cyg_SchedThread::queue, RUNNING, Cyg_Scheduler_Implementation::set_need_reschedule(), SLEEPING, state, and Cyg_Scheduler::unlock().
 {
     CYG_REPORT_FUNCTION();
 //    CYG_ASSERT( new_priority >=  CYG_THREAD_MAX_PRIORITY, "Priority out of range");
 //    CYG_ASSERT( new_priority <=  CYG_THREAD_MIN_PRIORITY, "Priority out of range");
     CYG_INSTRUMENT_THREAD(PRIORITY,this,new_priority);
     // Prevent preemption
     Cyg_Scheduler::lock();
     Cyg_ThreadQueue *queue = NULL;
     // If running, remove from run qs
     if( state == RUNNING )
         Cyg_Scheduler::scheduler.rem_thread(this);
     else if( state & SLEEPING )
     {
         // Remove thread from current queue.
         queue = get_current_queue();
         // if indeed we are on a queue
         if ( NULL != queue ) {
             CYG_CHECK_DATA_PTR(queue, "Bad queue pointer");
             remove();
         }
     }
     Cyg_Scheduler::scheduler.deregister_thread(this);
 #if CYGINT_KERNEL_SCHEDULER_UNIQUE_PRIORITIES
     // Check that there are no other threads at this priority.
     // If so, leave is as it is.
     CYG_ASSERT( Cyg_Scheduler::scheduler.unique(new_priority), "Priority not unique");
     if( Cyg_Scheduler::scheduler.unique(new_priority) )
         priority = new_priority;
 #else // !CYGINT_KERNEL_SCHEDULER_UNIQUE_PRIORITIES
 #ifdef CYGSEM_KERNEL_SYNCH_MUTEX_PRIORITY_INVERSION_PROTOCOL_SIMPLE
     // When we have priority inheritance, we must update the original
     // priority and not the inherited one.  If the new priority is
     // better than the current inherited one, then use that
     // immediately. We remain in inherited state to avoid problems
     // with multiple mutex inheritances.
     if( priority_inherited )
     {
         original_priority = new_priority;
         if( priority > new_priority ) priority = new_priority;
     }
     else priority = new_priority;
 #else
     priority = new_priority;
 #endif
 #endif // CYGINT_KERNEL_SCHEDULER_UNIQUE_PRIORITIES
     Cyg_Scheduler::scheduler.register_thread(this);
     // Return thread to scheduler if runnable
     if( state == RUNNING )
         Cyg_Scheduler::scheduler.add_thread(this);
     else if ( state & SLEEPING )
     {
         // return to current queue
         // if indeed we are on a queue
         if ( NULL != queue ) {
             CYG_CHECK_DATA_PTR(queue, "Bad queue pointer");
             queue->enqueue(this);
         }
     }
     // If the current thread is being reprioritized, set the
     // reschedule flag to ensure that it gets rescheduled if
     // necessary. (Strictly we only need to do this if the new
     // priority is less than that of some other runnable thread, in
     // practice checking that is as expensive as what the scheduler
     // will do anyway).
     // If it is not the current thread then we need to see whether
     // it is more worthy of execution than any current thread and
     // rescheduled if necessary.
     if( this == Cyg_Scheduler::get_current_thread() )
          Cyg_Scheduler::set_need_reschedule();
     else Cyg_Scheduler::set_need_reschedule(this);
     // Unlock the scheduler and maybe switch threads
     Cyg_Scheduler::unlock();
     CYG_REPORT_RETURN();
 }
void Cyg_Thread::set_sleep_reason (cyg_reason reason = WAIT) inline static
Definition at line 429 of file thread.inl.
References NONE, sleep_reason, and wake_reason.
Referenced by counted_sleep().
 {
     self()->sleep_reason = reason;
     self()->wake_reason = NONE;
 }
void Cyg_Thread::set_timer (cyg_tick_count trigger, cyg_reason sleep_reason) inline static
Definition at line 459 of file thread.inl.
References Cyg_Alarm::initialize(), NONE, sleep_reason, timer, and wake_reason.
Referenced by counted_sleep(), and delay().
 {
     self()->sleep_reason = reason;
     self()->wake_reason = NONE;
     self()->timer.initialize( trigger);
 }
void Cyg_Thread::set_wait_info (CYG_ADDRWORD data) inline
Definition at line 552 of file thread.hxx.
References wait_info.
 {
     wait_info = data;
 }
void Cyg_Thread::set_wake_reason (cyg_reason reason = DONE) inline
Definition at line 444 of file thread.inl.
References NONE, sleep_reason, and wake_reason.
Referenced by Cyg_ThreadTimer::alarm().
 {
     sleep_reason = NONE;
     wake_reason = reason;
 }
void Cyg_Thread::sleep () static
Definition at line 334 of file thread.cxx.
References CYG_REPORT_FUNCTION, CYG_REPORT_RETURN, Cyg_Scheduler_Base::get_current_thread(), Cyg_Scheduler::lock(), RUNNING, SLEEPING, state, and Cyg_Scheduler::unlock().
Referenced by counted_sleep(), and delay().
 {
     CYG_REPORT_FUNCTION();
     Cyg_Thread *current = Cyg_Scheduler::get_current_thread();
     CYG_ASSERTCLASS( current, "Bad current thread" );
     CYG_INSTRUMENT_THREAD(SLEEP,current,0);
     // Prevent preemption
     Cyg_Scheduler::lock();
     // If running, remove from run qs
     if ( current->state == RUNNING )
         Cyg_Scheduler::scheduler.rem_thread(current);
     // Set the state
     current->state |= SLEEPING;
     // Unlock the scheduler and switch threads
     Cyg_Scheduler::unlock();
     CYG_REPORT_RETURN();
 }
void Cyg_Thread::suspend ()
Definition at line 560 of file thread.cxx.
References CYG_ASSERT, CYG_REPORT_FUNCTION, CYG_REPORT_RETURN, Cyg_Scheduler_Base::get_current_thread(), Cyg_Scheduler::lock(), RUNNING, state, suspend_count, SUSPENDED, and Cyg_Scheduler::unlock().
 {
     CYG_REPORT_FUNCTION();
     CYG_INSTRUMENT_THREAD(SUSPEND,this,Cyg_Scheduler::get_current_thread());
     // Prevent preemption
     Cyg_Scheduler::lock();
     suspend_count++;
 #ifdef CYGNUM_KERNEL_MAX_SUSPEND_COUNT_ASSERT
     CYG_ASSERT( CYGNUM_KERNEL_MAX_SUSPEND_COUNT_ASSERT > suspend_count,
                 "suspend_count overflow" );
 #endif
     // If running, remove from run qs
     if( state == RUNNING )
         Cyg_Scheduler::scheduler.rem_thread(this);
     // Set the state
     state |= SUSPENDED;
     // Unlock the scheduler and maybe switch threads
     Cyg_Scheduler::unlock();
     CYG_REPORT_RETURN();
 }
void Cyg_Thread::to_queue_head (void) inline
Definition at line 395 of file thread.inl.
References Cyg_SchedThread_Implementation::to_queue_head().
 {
     this->Cyg_SchedThread::to_queue_head();
 }
void Cyg_Thread::wake ()
Definition at line 364 of file thread.cxx.
References CYG_REPORT_FUNCTION, CYG_REPORT_RETURN, Cyg_Scheduler_Base::get_current_thread(), Cyg_Scheduler::lock(), RUNNING, SLEEPSET, state, and Cyg_Scheduler::unlock().
Referenced by Cyg_ThreadTimer::alarm(), counted_wake(), kill(), and release().
 {
     CYG_REPORT_FUNCTION();
     CYG_INSTRUMENT_THREAD(WAKE,this,Cyg_Scheduler::get_current_thread());
     // Prevent preemption
     Cyg_Scheduler::lock();
     if( 0 != (state & SLEEPSET) )
     {
         // Set the state
         state &= ~SLEEPSET;
         // remove from any queue we were on
         remove();
         // If the thread is now runnable, return it to run queue
         if( state == RUNNING )
             Cyg_Scheduler::scheduler.add_thread(this);
     }
     // Unlock the scheduler and maybe switch threads
     Cyg_Scheduler::unlock();
     CYG_REPORT_RETURN();
 }
void Cyg_Thread::yield (void) inline static
Definition at line 379 of file thread.inl.
References Cyg_SchedThread_Implementation::yield().
Referenced by idle_thread_main().
 {
     self()->Cyg_SchedThread::yield();
 }
Friends And Related Function Documentation
friend class Cyg_Scheduler friend
Definition at line 213 of file thread.hxx.
void deliver_exception (CYG_WORD code, CYG_ADDRWORD data) friend
Member Data Documentation
cyg_reason Cyg_Thread::sleep_reason private
Definition at line 403 of file thread.hxx.
Referenced by counted_wake(), Cyg_Thread(), get_sleep_reason(), kill(), release(), set_sleep_reason(), set_timer(), and set_wake_reason().
cyg_uint32 Cyg_Thread::state private
Definition at line 237 of file thread.hxx.
Referenced by counted_sleep(), counted_wake(), Cyg_Thread(), exit(), force_resume(), get_state(), kill(), resume(), set_priority(), sleep(), suspend(), Cyg_Scheduler::unlock_inner(), and wake().
cyg_ucount32 Cyg_Thread::suspend_count private
Definition at line 240 of file thread.hxx.
Referenced by Cyg_Thread(), force_resume(), resume(), and suspend().
Cyg_ThreadTimer Cyg_Thread::timer private
Definition at line 400 of file thread.hxx.
Referenced by clear_timer(), kill(), reinitialize(), and set_timer().
cyg_uint16 Cyg_Thread::unique_id private
Definition at line 250 of file thread.hxx.
Referenced by Cyg_Thread(), get_unique_id(), and ~Cyg_Thread().
CYG_ADDRWORD Cyg_Thread::wait_info private
Definition at line 247 of file thread.hxx.
Referenced by get_wait_info(), and set_wait_info().
cyg_reason Cyg_Thread::wake_reason private
Definition at line 405 of file thread.hxx.
Referenced by counted_sleep(), counted_wake(), Cyg_Thread(), delay(), get_wake_reason(), kill(), release(), set_sleep_reason(), set_timer(), and set_wake_reason().
cyg_ucount32 Cyg_Thread::wakeup_count private
Definition at line 243 of file thread.hxx.
Referenced by cancel_counted_wake(), counted_sleep(), counted_wake(), and Cyg_Thread().
The documentation for this class was generated from the following files:
C:/Users/barry/Documents/GitHub/VEROS/Xinrui/20130621_refined_thread/thread.hxx
C:/Users/barry/Documents/GitHub/VEROS/Xinrui/20130621_refined_thread/thread.cxx
C:/Users/barry/Documents/GitHub/VEROS/Xinrui/20130621_refined_thread/thread.inl