My Project: Cyg_CList Class Reference
Cyg_CList Class Reference
#include <clist.hxx>
Public Member Functions
Cyg_CList ()
Cyg_DNode * get_head ()
Cyg_DNode * get_tail ()
cyg_bool empty ()
void add_head (Cyg_DNode *node)
Cyg_DNode * rem_head ()
void add_tail (Cyg_DNode *node)
Cyg_DNode * rem_tail ()
void merge (Cyg_CList &list)
void remove (Cyg_DNode *node)
void rotate ()
void to_head (Cyg_DNode *node)
void insert (Cyg_DNode *list_node, Cyg_DNode *node)
~Cyg_CList ()
Private Attributes
Cyg_DNode * head
Detailed Description
Definition at line 156 of file clist.hxx.
Constructor & Destructor Documentation
Cyg_CList::Cyg_CList () inline
Definition at line 162 of file clist.hxx.
References head, and NULL.
     {
         head = NULL;
     };
Cyg_CList::~Cyg_CList () inline
Definition at line 291 of file clist.hxx.
References head, NULL, and rem_head().
     {
         while( head != NULL )
             rem_head();
     };
Member Function Documentation
void Cyg_CList::add_head (Cyg_DNode * node) inline
Definition at line 173 of file clist.hxx.
References head, Cyg_DNode::insert(), and NULL.
     {
         if( head == NULL )
             head = node;
         else
         {
             head->insert( node );
             head = node;
         }
     };
void Cyg_CList::add_tail (Cyg_DNode * node) inline
Definition at line 209 of file clist.hxx.
References head, Cyg_DNode::insert(), and NULL.
Referenced by Cyg_Counter::add_alarm(), Cyg_Scheduler_Implementation::add_thread(), and Cyg_ThreadQueue_Implementation::enqueue().
     {
         if( head == NULL )
             head = node;
         else
             head->insert( node );
     };
cyg_bool Cyg_CList::empty () inline
Definition at line 170 of file clist.hxx.
References head, and NULL.
Referenced by Cyg_Scheduler_Implementation::add_thread(), Cyg_ThreadQueue::empty(), Cyg_Scheduler_Implementation::rem_thread(), Cyg_SchedThread_Implementation::rotate_queue(), Cyg_Scheduler_Implementation::schedule(), and Cyg_Counter::tick().
 { return head == NULL; };
Cyg_DNode* Cyg_CList::get_head () inline
Definition at line 168 of file clist.hxx.
References head.
Referenced by Cyg_CList_T< Cyg_Alarm >::get_head().
 { return head; };
Cyg_DNode* Cyg_CList::get_tail () inline
Definition at line 169 of file clist.hxx.
References head, NULL, and Cyg_DNode::prev.
Referenced by Cyg_CList_T< Cyg_Alarm >::get_tail().
 { return head?head->prev:NULL; };
void Cyg_CList::insert (Cyg_DNode * list_node, Cyg_DNode * node) inline
Definition at line 281 of file clist.hxx.
References head, and Cyg_DNode::insert().
Referenced by Cyg_Counter::add_alarm().
     {
         if( list_node == head )
         {
             head->insert( node );
             head = node;
         }
         else list_node->insert( node );
     };
void Cyg_CList::merge (Cyg_CList & list) inline
Definition at line 233 of file clist.hxx.
References head, Cyg_DNode::next, NULL, and Cyg_DNode::prev.
     {
         if( list.head == NULL )
             return;                     // Nothing to do
         else if( head == NULL )
             head = list.head;           // this is empty, just move it
         else
         {
             // We have a real merge to do. Adjust the pointers
             // on the two lists so that they become one.
             Cyg_DNode *lh = list.head;
             Cyg_DNode *lt = lh->prev;
             Cyg_DNode *tail = head->prev;
             head->prev = lt;
             lt->next = head;
             tail->next = lh;
             lh->prev = tail;
         }
         list.head = NULL;
     };
Cyg_DNode* Cyg_CList::rem_head () inline
Definition at line 185 of file clist.hxx.
References head, Cyg_DNode::next, NULL, and Cyg_DNode::unlink().
Referenced by Cyg_CList_T< Cyg_Alarm >::rem_head(), remove(), and ~Cyg_CList().
     {
         Cyg_DNode *node = head;
         if( node != NULL )
         {
             // There is a node available
             Cyg_DNode *next = node->next;
             if( next == node )
             {
                 // Only node on list
                 head = NULL;
             }
             else
             {
                 // remove head node and move head to next.
                 node->unlink();
                 head = next;
             }
         }
         return node;
     };
Cyg_DNode* Cyg_CList::rem_tail () inline
Definition at line 218 of file clist.hxx.
References head, NULL, Cyg_DNode::prev, and Cyg_DNode::unlink().
Referenced by Cyg_CList_T< Cyg_Alarm >::rem_tail().
     {
         if( head == NULL )
             return NULL;
         Cyg_DNode *node = head->prev;
         if( node == head )
             head = NULL;
         else node->unlink();
         return node;
     };
void Cyg_CList::remove (Cyg_DNode * node) inline
Definition at line 258 of file clist.hxx.
References head, and rem_head().
Referenced by Cyg_Counter::rem_alarm(), Cyg_Scheduler_Implementation::rem_thread(), Cyg_ThreadQueue_Implementation::remove(), and Cyg_Counter::tick().
     {
         if( node == head )
             rem_head();
         else node->unlink();
     };
void Cyg_CList::rotate () inline
Definition at line 266 of file clist.hxx.
References head, and Cyg_DNode::next.
Referenced by Cyg_SchedThread_Implementation::rotate_queue(), Cyg_Scheduler_Implementation::timeslice_cpu(), and Cyg_SchedThread_Implementation::yield().
     {
         if( head )
             head = head->next;
     };
void Cyg_CList::to_head (Cyg_DNode * node) inline
Definition at line 274 of file clist.hxx.
References head.
Referenced by Cyg_ThreadQueue_Implementation::enqueue(), and Cyg_SchedThread_Implementation::to_queue_head().
     {
         head = node;
     };
Member Data Documentation
Cyg_DNode* Cyg_CList::head private
Definition at line 158 of file clist.hxx.
Referenced by add_head(), add_tail(), Cyg_CList(), empty(), get_head(), get_tail(), insert(), merge(), rem_head(), rem_tail(), remove(), rotate(), to_head(), and ~Cyg_CList().
The documentation for this class was generated from the following file:
C:/Users/barry/Documents/GitHub/VEROS/Xinrui/20130621_refined_thread/clist.hxx