My Project: Cyg_ThreadQueue Class Reference
Cyg_ThreadQueue Class Reference
#include <thread.hxx>
Public Member Functions
CYGDBG_DEFINE_CHECK_THIS void enqueue (Cyg_Thread *thread)
Cyg_Thread * highpri ()
Cyg_Thread * dequeue ()
void remove (Cyg_Thread *thread)
cyg_bool empty ()
Additional Inherited Members
Protected Member Functions inherited from Cyg_ThreadQueue_Implementation
Cyg_ThreadQueue_Implementation ()
void enqueue (Cyg_Thread *thread)
Cyg_Thread * highpri ()
Cyg_Thread * dequeue ()
void remove (Cyg_Thread *thread)
Detailed Description
Definition at line 516 of file thread.hxx.
Member Function Documentation
Cyg_Thread * Cyg_ThreadQueue::dequeue (void) inline
Definition at line 614 of file thread.inl.
References Cyg_ThreadQueue_Implementation::dequeue().
 {
     return Cyg_ThreadQueue_Implementation::dequeue();
 }
cyg_bool Cyg_ThreadQueue::empty () inline
Definition at line 628 of file thread.inl.
References Cyg_CList::empty().
 {
     return Cyg_ThreadQueue_Implementation::empty();
 }
void Cyg_ThreadQueue::enqueue (Cyg_Thread * thread) inline
Definition at line 600 of file thread.inl.
References Cyg_ThreadQueue_Implementation::enqueue().
Referenced by Cyg_Thread::set_priority().
 {
     Cyg_ThreadQueue_Implementation::enqueue(thread);
 }
Cyg_Thread * Cyg_ThreadQueue::highpri (void) inline
Definition at line 607 of file thread.inl.
References Cyg_ThreadQueue_Implementation::highpri().
 {
     return Cyg_ThreadQueue_Implementation::highpri();
 }
void Cyg_ThreadQueue::remove (Cyg_Thread * thread) inline
Definition at line 621 of file thread.inl.
References Cyg_ThreadQueue_Implementation::remove().
Referenced by Cyg_SchedThread::remove().
 {
     Cyg_ThreadQueue_Implementation::remove(thread);
 }
The documentation for this class was generated from the following files:
C:/Users/barry/Documents/GitHub/VEROS/Xinrui/20130621_refined_thread/thread.hxx
C:/Users/barry/Documents/GitHub/VEROS/Xinrui/20130621_refined_thread/thread.inl