My Project: Cyg_SchedThread_Implementation Class Reference
Cyg_SchedThread_Implementation Class Reference
#include <mlqueue.hxx>
Public Member Functions
void timeslice_enable ()
void timeslice_disable ()
Public Member Functions inherited from Cyg_DNode_T< Cyg_Thread >
Cyg_DNode_T ()
~Cyg_DNode_T ()
Cyg_Thread * get_next ()
Cyg_Thread * get_prev ()
Public Member Functions inherited from Cyg_DNode
Cyg_DNode ()
Cyg_DNode * get_next ()
Cyg_DNode * get_prev ()
cyg_bool in_list ()
void insert (Cyg_DNode *node)
void append (Cyg_DNode *node)
void unlink ()
~Cyg_DNode ()
Protected Member Functions
Cyg_SchedThread_Implementation (CYG_ADDRWORD sched_info)
void yield ()
void to_queue_head (void)
void timeslice_save ()
void timeslice_restore ()
void timeslice_reset ()
Static Protected Member Functions
static void rotate_queue (cyg_priority pri)
Protected Attributes
cyg_priority priority
cyg_ucount32 timeslice_count
cyg_bool timeslice_enabled
Friends
class Cyg_Scheduler_Implementation
class Cyg_ThreadQueue_Implementation
Detailed Description
Definition at line 225 of file mlqueue.hxx.
Constructor & Destructor Documentation
Cyg_SchedThread_Implementation::Cyg_SchedThread_Implementation (CYG_ADDRWORD sched_info) protected
Definition at line 399 of file mlqueue.cxx.
References CYG_REPORT_FUNCARG1, CYG_REPORT_FUNCTION, and CYG_REPORT_RETURN.
 {
     CYG_REPORT_FUNCTION();
     CYG_REPORT_FUNCARG1("sched_info=%08x", sched_info);
     // Set priority to the supplied value.
     priority = (cyg_priority)sched_info;
     // If timeslice_enabled exists, set it true by default
     timeslice_enabled = true;
     CYG_REPORT_RETURN();
 }
Member Function Documentation
void Cyg_SchedThread_Implementation::rotate_queue (cyg_priority pri) static protected
Definition at line 485 of file mlqueue.cxx.
References CYG_REPORT_FUNCARG1, CYG_REPORT_FUNCTION, CYG_REPORT_RETURN, Cyg_CList::empty(), Cyg_Scheduler::lock(), Cyg_CList::rotate(), Cyg_Scheduler_Implementation::set_need_reschedule(), and Cyg_Scheduler::unlock().
Referenced by Cyg_Thread::rotate_queue().
 {
     CYG_REPORT_FUNCTION();
     CYG_REPORT_FUNCARG1("priority=%d", pri);
     // Prevent preemption
     Cyg_Scheduler::lock();
     Cyg_Scheduler *sched = &Cyg_Scheduler::scheduler;
     CYG_ASSERTCLASS( sched, "Bad scheduler");
     Cyg_RunQueue *queue = &sched->run_queue[pri];
     if ( !queue->empty() ) {
         queue->rotate();
         sched->set_need_reschedule();
     }
     // Unlock the scheduler and switch threads
     Cyg_Scheduler::unlock();
     CYG_REPORT_RETURN();
 }
void Cyg_SchedThread_Implementation::timeslice_disable () inline
Definition at line 303 of file mlqueue.hxx.
References timeslice_enabled.
 {
     timeslice_enabled = false;
 }
void Cyg_SchedThread_Implementation::timeslice_enable () inline
Definition at line 298 of file mlqueue.hxx.
References timeslice_enabled.
 {
     timeslice_enabled = true;
 }
void Cyg_SchedThread_Implementation::timeslice_reset () inline protected
Definition at line 291 of file mlqueue.hxx.
References timeslice_count.
Referenced by Cyg_Scheduler_Implementation::add_thread(), Cyg_Scheduler::thread_entry(), and yield().
 {
     timeslice_count = CYGNUM_KERNEL_SCHED_TIMESLICE_TICKS;
 }
void Cyg_SchedThread_Implementation::timeslice_restore () inline protected
Definition at line 286 of file mlqueue.hxx.
References CYG_KERNEL_CPU_THIS, and timeslice_count.
Referenced by Cyg_Scheduler::thread_entry(), and Cyg_Scheduler::unlock_inner().
 {
     Cyg_Scheduler_Implementation::timeslice_count[CYG_KERNEL_CPU_THIS()] = timeslice_count;
 }
void Cyg_SchedThread_Implementation::timeslice_save () inline protected
Definition at line 281 of file mlqueue.hxx.
References CYG_KERNEL_CPU_THIS, and timeslice_count.
Referenced by Cyg_Scheduler::unlock_inner().
 {
     timeslice_count = Cyg_Scheduler_Implementation::timeslice_count[CYG_KERNEL_CPU_THIS()];
 }
void Cyg_SchedThread_Implementation::to_queue_head (void) protected
Definition at line 515 of file mlqueue.cxx.
References CYG_CLASSFROMBASE, CYG_REPORT_FUNCTION, CYG_REPORT_RETURN, Cyg_SchedThread::get_current_queue(), Cyg_DNode::in_list(), Cyg_Scheduler::lock(), NULL, priority, Cyg_Scheduler_Implementation::set_need_reschedule(), Cyg_CList::to_head(), and Cyg_Scheduler::unlock().
Referenced by Cyg_Thread::to_queue_head().
 {
     CYG_REPORT_FUNCTION();
     // Prevent preemption
     Cyg_Scheduler::lock();
     Cyg_Thread *thread  = CYG_CLASSFROMBASE(Cyg_Thread,
                                             Cyg_SchedThread_Implementation,
                                             this);
     CYG_ASSERTCLASS( thread, "Bad current thread");
     Cyg_ThreadQueue *q = thread->get_current_queue();
     if( q != NULL )
         q->to_head( thread );
     else if( thread->in_list() )
     {
         // If the queue pointer is NULL then it is on a run
         // queue. Move the thread to the head of it's priority list
         // and force a reschedule.
         Cyg_Scheduler *sched = &Cyg_Scheduler::scheduler;
         sched->run_queue[thread->priority].to_head( thread );
         sched->set_need_reschedule( thread );
     }
     // Unlock the scheduler and switch threads
     Cyg_Scheduler::unlock();
     CYG_REPORT_RETURN();
 }
void Cyg_SchedThread_Implementation::yield (void) protected
Definition at line 421 of file mlqueue.cxx.
References CYG_CLASSFROMBASE, CYG_REPORT_FUNCTION, CYG_REPORT_RETURN, Cyg_CList_T< T >::get_head(), Cyg_Scheduler_Base::get_need_reschedule(), Cyg_Thread::get_state(), Cyg_Scheduler::lock(), priority, Cyg_CList::rotate(), Cyg_Thread::RUNNING, Cyg_Scheduler_Implementation::set_need_reschedule(), timeslice_reset(), Cyg_Scheduler::unlock(), and Cyg_Scheduler::unlock_reschedule().
Referenced by Cyg_Thread::yield().
 {
     CYG_REPORT_FUNCTION();
     // Prevent preemption
     Cyg_Scheduler::lock();
     Cyg_Thread *thread  = CYG_CLASSFROMBASE(Cyg_Thread,
                                             Cyg_SchedThread_Implementation,
                                             this);
     // Only do this if this thread is running. If it is not, there
     // is no point.
     if( thread->get_state() == Cyg_Thread::RUNNING )
     {
         // To yield we simply rotate the appropriate
         // run queue to the next thread and reschedule.
         CYG_INSTRUMENT_MLQ( YIELD, thread, 0);
         CYG_ASSERTCLASS( thread, "Bad current thread");
         Cyg_Scheduler *sched = &Cyg_Scheduler::scheduler;
         CYG_ASSERTCLASS( sched, "Bad scheduler");
         cyg_priority pri    = thread->priority;
         Cyg_RunQueue *queue = &sched->run_queue[pri];
             queue->rotate();
         if( queue->get_head() != thread )
             sched->set_need_reschedule();
         else
         {
             // Reset the timeslice counter so that this thread gets a
             // full quantum as a reward for yielding when it is
             // eventually rescheduled.
             thread->timeslice_reset();
         }
     }
     // Unlock the scheduler and switch threads
 #ifdef CYGDBG_USE_ASSERTS
     // This test keeps the assertions in unlock_inner() happy if
     // need_reschedule was not set above.
     if( !Cyg_Scheduler::get_need_reschedule() )
         Cyg_Scheduler::unlock();
     else
 #endif
     Cyg_Scheduler::unlock_reschedule();
     CYG_REPORT_RETURN();
 }
Friends And Related Function Documentation
friend class Cyg_Scheduler_Implementation friend
Definition at line 228 of file mlqueue.hxx.
friend class Cyg_ThreadQueue_Implementation friend
Definition at line 229 of file mlqueue.hxx.
Member Data Documentation
cyg_priority Cyg_SchedThread_Implementation::priority protected
Definition at line 233 of file mlqueue.hxx.
Referenced by Cyg_Scheduler_Implementation::add_thread(), Cyg_ThreadQueue_Implementation::enqueue(), Cyg_Scheduler_Implementation::rem_thread(), Cyg_Scheduler_Implementation::set_need_reschedule(), Cyg_Thread::set_priority(), Cyg_Scheduler_Implementation::timeslice_cpu(), to_queue_head(), and yield().
cyg_ucount32 Cyg_SchedThread_Implementation::timeslice_count protected
Definition at line 249 of file mlqueue.hxx.
Referenced by timeslice_reset(), timeslice_restore(), and timeslice_save().
cyg_bool Cyg_SchedThread_Implementation::timeslice_enabled protected
Definition at line 262 of file mlqueue.hxx.
Referenced by Cyg_Scheduler_Implementation::timeslice_cpu(), timeslice_disable(), and timeslice_enable().
The documentation for this class was generated from the following files:
C:/Users/barry/Documents/GitHub/VEROS/Xinrui/20130621_refined_thread/mlqueue.hxx
C:/Users/barry/Documents/GitHub/VEROS/Xinrui/20130621_refined_thread/mlqueue.cxx