My Project: Cyg_HardwareThread Class Reference
Cyg_HardwareThread Class Reference
#include <thread.hxx>
Public Member Functions
CYGDBG_DEFINE_CHECK_THIS void set_entry_data (CYG_ADDRWORD data)
CYG_ADDRWORD get_entry_data ()
CYG_ADDRESS get_stack_base ()
cyg_uint32 get_stack_size ()
Protected Member Functions
Cyg_HardwareThread (cyg_thread_entry *entry_point, CYG_ADDRWORD entry_data, cyg_ucount32 stack_size=0, CYG_ADDRESS stack_base=0)
void init_context (Cyg_Thread *thread)
void switch_context (Cyg_HardwareThread *next)
void attach_stack (CYG_ADDRESS stack, cyg_uint32 stack_size)
CYG_ADDRESS detach_stack ()
void prepare_exception (cyg_exception_handler *exception_handler, CYG_ADDRWORD exception_data, cyg_code exception_number, CYG_ADDRWORD exception_info)
Static Protected Member Functions
static void thread_entry (Cyg_Thread *thread)
Protected Attributes
CYG_ADDRESS stack_base
cyg_uint32 stack_size
CYG_ADDRESS stack_ptr
cyg_thread_entry * entry_point
CYG_ADDRWORD entry_data
Friends
class Cyg_Scheduler
Detailed Description
Definition at line 74 of file thread.hxx.
Constructor & Destructor Documentation
Cyg_HardwareThread::Cyg_HardwareThread (cyg_thread_entry * entry_point, CYG_ADDRWORD entry_data, cyg_ucount32 stack_size = 0, CYG_ADDRESS stack_base = 0) inline protected
Definition at line 263 of file thread.inl.
References attach_stack(), entry_data, and entry_point.
 {
     entry_point = e_point;
     entry_data  = e_data;
 #ifdef CYGDBG_KERNEL_DEBUG_GDB_THREAD_SUPPORT
     saved_context = 0;
 #endif
     attach_stack( s_base, s_size );
 };
Member Function Documentation
void Cyg_HardwareThread::attach_stack (CYG_ADDRESS stack, cyg_uint32 stack_size) inline protected
Definition at line 182 of file thread.inl.
References CYG_ASSERT, CYGNUM_KERNEL_THREADS_STACK_CHECK_DATA_SIZE, NULL, stack_base, stack_ptr, and stack_size.
Referenced by Cyg_HardwareThread().
 {
 #ifdef CYGNUM_HAL_STACK_SIZE_MINIMUM
     CYG_ASSERT( s_size >= CYGNUM_HAL_STACK_SIZE_MINIMUM,
                 "Stack size too small");
 #endif
 #ifdef CYGFUN_KERNEL_THREADS_STACK_CHECKING
     {
         cyg_uint32 sig = (cyg_uint32)this;
         cyg_uint32 *base = (cyg_uint32 *)s_base;
         cyg_uint32 *top =  (cyg_uint32 *)(s_base + s_size -
             CYGNUM_KERNEL_THREADS_STACK_CHECK_DATA_SIZE);
         unsigned int i;
         CYG_INSTRUMENT_THREAD(ATTACH_STACK, base, top );
         CYG_ASSERT( NULL != base, "stack base non-NULL" );
         CYG_ASSERT( 0 == ((sizeof(CYG_WORD)-1) & (cyg_uint32)base), "stack base alignment" );
         CYG_ASSERT( 0 == ((sizeof(CYG_WORD)-1) & (cyg_uint32)top),  "stack  top alignment" );
         for ( i = 0;
               i < CYGNUM_KERNEL_THREADS_STACK_CHECK_DATA_SIZE/sizeof(cyg_uint32);
               i++ ) {
             base[i] = (sig ^ (i * 0x01010101));
              top[i] = (sig ^ (i * 0x10101010));
         }
         // This check for overlap of the two signature areas also detects
         // wrap round zero of the size in the unsigned subtraction below.
         CYG_ASSERT( &base[i] < &top[0], "Stack is so small size wrapped" );
         // Use this 'i' expression to round correctly to whole words.
         s_base += i * sizeof(cyg_uint32);
         s_size -= i * sizeof(cyg_uint32) * 2;
         // This is a complete guess, the 256; the point is to assert early that
         // this might go badly wrong.  It would not detect wrap of unsigned size.
         CYG_ASSERT( s_size >= 256,
                     "Stack size too small after allocating checking buffer");
     }
 #endif
 #ifdef CYGFUN_KERNEL_THREADS_STACK_MEASUREMENT
     {
     CYG_WORD *base = (CYG_WORD *)s_base;
     cyg_uint32 size = s_size/sizeof(CYG_WORD);
     cyg_ucount32 i;
     // initialize all of stack with known value - don't choose 0
     // could do with pseudo value as above, but this way, checking
     // is faster
     for (i=0; i<size; i++) {
         base[i] = 0xDEADBEEF;
     }
     // Don't bother about the case when the stack isn't a multiple of
     // CYG_WORD in size. Since it's at the top of the stack, it will
     // almost certainly be overwritten the instant the thread starts
     // anyway.
     }
 #endif
     stack_base = s_base;
     stack_size = s_size;
 #ifdef CYGFUN_KERNEL_THREADS_STACK_LIMIT
     stack_limit = s_base;
 #endif
 #ifdef HAL_THREAD_ATTACH_STACK
     HAL_THREAD_ATTACH_STACK(stack_ptr, stack_base, stack_size);
 #else
     stack_ptr = stack_base + stack_size;
 #endif
 #ifdef CYGFUN_KERNEL_THREADS_STACK_CHECKING
     check_stack();
 #endif
 }
CYG_ADDRESS Cyg_HardwareThread::detach_stack () protected
CYG_ADDRWORD Cyg_HardwareThread::get_entry_data () inline
Definition at line 340 of file thread.inl.
References entry_data.
 {
     return entry_data;
 }
CYG_ADDRESS Cyg_HardwareThread::get_stack_base () inline
Definition at line 79 of file thread.inl.
References CYGNUM_KERNEL_THREADS_STACK_CHECK_DATA_SIZE, and stack_base.
Referenced by Cyg_Thread::reinitialize().
 {
     return stack_base - CYGNUM_KERNEL_THREADS_STACK_CHECK_DATA_SIZE;
 }
cyg_uint32 Cyg_HardwareThread::get_stack_size () inline
Definition at line 85 of file thread.inl.
References CYGNUM_KERNEL_THREADS_STACK_CHECK_DATA_SIZE, and stack_size.
Referenced by Cyg_Thread::reinitialize().
 {
     return stack_size + 2 * CYGNUM_KERNEL_THREADS_STACK_CHECK_DATA_SIZE;
 }
void Cyg_HardwareThread::init_context (Cyg_Thread * thread) inline protected
Definition at line 310 of file thread.inl.
References Cyg_Thread::get_unique_id(), stack_ptr, and thread_entry().
Referenced by Cyg_Thread::Cyg_Thread().
 {
 #ifdef CYGPKG_INFRA_DEBUG
     cyg_uint32 threadid = thread->get_unique_id()*0x01010000;
 #else
     cyg_uint32 threadid = 0x11110000;
 #endif
     HAL_THREAD_INIT_CONTEXT( stack_ptr, thread, thread_entry, threadid );
 }
void Cyg_HardwareThread::prepare_exception (cyg_exception_handler * exception_handler, CYG_ADDRWORD exception_data, cyg_code exception_number, CYG_ADDRWORD exception_info) protected
void Cyg_HardwareThread::set_entry_data (CYG_ADDRWORD data) inline
Definition at line 335 of file thread.inl.
References entry_data.
 {
     entry_data = data;
 }
void Cyg_HardwareThread::switch_context (Cyg_HardwareThread * next) inline protected
Definition at line 327 of file thread.inl.
References stack_ptr.
 {
     HAL_THREAD_SWITCH_CONTEXT( &stack_ptr, &next->stack_ptr );
 }
void Cyg_HardwareThread::thread_entry (Cyg_Thread * thread) static protected
Definition at line 84 of file thread.cxx.
References CYG_REPORT_FUNCTION, entry_data, entry_point, and Cyg_Thread::exit().
Referenced by init_context().
 {
     CYG_REPORT_FUNCTION();
     // Call the scheduler to do any housekeeping
     Cyg_Scheduler::scheduler.thread_entry( thread );
     // Call entry point in a loop.
     for(;;)
     {
         thread->entry_point(thread->entry_data);
         thread->exit();
     }
 }
Friends And Related Function Documentation
friend class Cyg_Scheduler friend
Definition at line 76 of file thread.hxx.
Member Data Documentation
CYG_ADDRWORD Cyg_HardwareThread::entry_data protected
Definition at line 92 of file thread.hxx.
Referenced by Cyg_HardwareThread(), get_entry_data(), Cyg_Thread::reinitialize(), set_entry_data(), and thread_entry().
cyg_thread_entry* Cyg_HardwareThread::entry_point protected
Definition at line 90 of file thread.hxx.
Referenced by Cyg_HardwareThread(), Cyg_Thread::reinitialize(), and thread_entry().
CYG_ADDRESS Cyg_HardwareThread::stack_base protected
Definition at line 80 of file thread.hxx.
Referenced by attach_stack(), and get_stack_base().
CYG_ADDRESS Cyg_HardwareThread::stack_ptr protected
Definition at line 88 of file thread.hxx.
Referenced by attach_stack(), init_context(), Cyg_Scheduler::start_cpu(), switch_context(), and Cyg_Scheduler::unlock_inner().
cyg_uint32 Cyg_HardwareThread::stack_size protected
Definition at line 82 of file thread.hxx.
Referenced by attach_stack(), and get_stack_size().
The documentation for this class was generated from the following files:
C:/Users/barry/Documents/GitHub/VEROS/Xinrui/20130621_refined_thread/thread.hxx
C:/Users/barry/Documents/GitHub/VEROS/Xinrui/20130621_refined_thread/thread.cxx
C:/Users/barry/Documents/GitHub/VEROS/Xinrui/20130621_refined_thread/thread.inl