My Project: Cyg_ThreadTimer Class Reference
Cyg_ThreadTimer Class Reference
#include <thread.hxx>
Private Member Functions
Cyg_ThreadTimer (Cyg_Thread *thread)
Static Private Member Functions
static void alarm (Cyg_Alarm *alarm, CYG_ADDRWORD data)
Private Attributes
Cyg_Thread * thread
Friends
class Cyg_Thread
Additional Inherited Members
Public Member Functions inherited from Cyg_Alarm
CYGDBG_DEFINE_CHECK_THIS Cyg_Alarm (Cyg_Counter *counter, cyg_alarm_fn *alarm, CYG_ADDRWORD data)
~Cyg_Alarm ()
void initialize (cyg_tick_count trigger, cyg_tick_count interval=0)
void enable ()
void disable ()
void get_times (cyg_tick_count *trigger, cyg_tick_count *interval)
Protected Member Functions inherited from Cyg_Alarm
Cyg_Alarm ()
void synchronize (void)
Protected Attributes inherited from Cyg_Alarm
Cyg_Counter * counter
cyg_alarm_fn * alarm
CYG_ADDRWORD data
cyg_tick_count trigger
cyg_tick_count interval
cyg_bool enabled
Detailed Description
Definition at line 183 of file thread.hxx.
Constructor & Destructor Documentation
Cyg_ThreadTimer::Cyg_ThreadTimer (Cyg_Thread * thread) private
Member Function Documentation
void Cyg_ThreadTimer::alarm (Cyg_Alarm * alarm, CYG_ADDRWORD data) static private
Definition at line 1140 of file thread.cxx.
References Cyg_Thread::BREAK, CYG_REPORT_FUNCTION, CYG_REPORT_RETURN, Cyg_Thread::DELAY, Cyg_Thread::DESTRUCT, Cyg_Thread::DONE, Cyg_Thread::EXIT, Cyg_Thread::get_sleep_reason(), Cyg_Scheduler::lock(), Cyg_Thread::NONE, Cyg_Thread::set_wake_reason(), thread, Cyg_Thread::TIMEOUT, Cyg_Scheduler::unlock(), Cyg_Thread::WAIT, and Cyg_Thread::wake().
 {
     CYG_REPORT_FUNCTION();
     Cyg_ThreadTimer *self = (Cyg_ThreadTimer *)data;
     Cyg_Thread *thread = self->thread;
     CYG_INSTRUMENT_THREAD(ALARM, 0, 0);
     Cyg_Scheduler::lock();
     Cyg_Thread::cyg_reason sleep_reason = thread->get_sleep_reason();
     switch( sleep_reason ) {
     case Cyg_Thread::DESTRUCT:
     case Cyg_Thread::BREAK:
     case Cyg_Thread::EXIT:
     case Cyg_Thread::NONE:
     case Cyg_Thread::WAIT:
     case Cyg_Thread::DONE:
         // Do nothing in any of these cases. Most are here to
         // keep the compiler happy.
         Cyg_Scheduler::unlock();
         CYG_REPORT_RETURN();
         return;
     case Cyg_Thread::DELAY:
         // The thread was simply delaying, unless it has been
         // woken up for some other reason, wake it now.
         thread->set_wake_reason(Cyg_Thread::DONE);
         break;
     case Cyg_Thread::TIMEOUT:
         // The thread has timed out, set the wake reason to
         // TIMEOUT and restart.
         thread->set_wake_reason(Cyg_Thread::TIMEOUT);
         break;
     }
     thread->wake();
     Cyg_Scheduler::unlock();
     CYG_REPORT_RETURN();
 }
Friends And Related Function Documentation
friend class Cyg_Thread friend
Definition at line 186 of file thread.hxx.
Member Data Documentation
Cyg_Thread* Cyg_ThreadTimer::thread private
Definition at line 189 of file thread.hxx.
Referenced by alarm().
The documentation for this class was generated from the following files:
C:/Users/barry/Documents/GitHub/VEROS/Xinrui/20130621_refined_thread/thread.hxx
C:/Users/barry/Documents/GitHub/VEROS/Xinrui/20130621_refined_thread/thread.cxx