My Project: Cyg_Alarm Class Reference
Cyg_Alarm Class Reference
#include <clock.hxx>
Public Member Functions
CYGDBG_DEFINE_CHECK_THIS Cyg_Alarm (Cyg_Counter *counter, cyg_alarm_fn *alarm, CYG_ADDRWORD data)
~Cyg_Alarm ()
void initialize (cyg_tick_count trigger, cyg_tick_count interval=0)
void enable ()
void disable ()
void get_times (cyg_tick_count *trigger, cyg_tick_count *interval)
Protected Member Functions
Cyg_Alarm ()
void synchronize (void)
Protected Attributes
Cyg_Counter * counter
cyg_alarm_fn * alarm
CYG_ADDRWORD data
cyg_tick_count trigger
cyg_tick_count interval
cyg_bool enabled
Friends
class Cyg_Counter
Detailed Description
Definition at line 199 of file clock.hxx.
Constructor & Destructor Documentation
Cyg_Alarm::Cyg_Alarm () protected
Definition at line 624 of file clock.cxx.
 {}
Cyg_Alarm::Cyg_Alarm (Cyg_Counter * counter, cyg_alarm_fn * alarm, CYG_ADDRWORD data)
Definition at line 607 of file clock.cxx.
References alarm, counter, CYG_REPORT_FUNCTION, data, enabled, interval, and trigger.
 {
     CYG_REPORT_FUNCTION();
     counter     = c;
     alarm       = a;
     data        = d;
     trigger     = 0;
     interval    = 0;
     enabled     = false;
 }
Cyg_Alarm::~Cyg_Alarm ()
Definition at line 629 of file clock.cxx.
References CYG_REPORT_FUNCTION, and disable().
 {
     CYG_REPORT_FUNCTION();
     disable();
 }
Member Function Documentation
void Cyg_Alarm::disable ()
Definition at line 744 of file clock.cxx.
References counter, enabled, Cyg_Scheduler::lock(), Cyg_Counter::rem_alarm(), and Cyg_Scheduler::unlock().
Referenced by Cyg_Thread::clear_timer(), Cyg_Thread::kill(), Cyg_Thread::reinitialize(), and ~Cyg_Alarm().
 {
     Cyg_Scheduler::lock();
     if( enabled ) counter->rem_alarm(this);
     Cyg_Scheduler::unlock();
 }
void Cyg_Alarm::enable ()
Definition at line 726 of file clock.cxx.
References Cyg_Counter::add_alarm(), counter, enabled, Cyg_Scheduler::lock(), synchronize(), and Cyg_Scheduler::unlock().
 {
     Cyg_Scheduler::lock();
     if( !enabled )
     {
         // ensure the alarm time is in our future:
         synchronize();
         enabled = true;
         counter->add_alarm(this);
     }
     Cyg_Scheduler::unlock();
 }
void Cyg_Alarm::get_times (cyg_tick_count * trigger, cyg_tick_count * interval)
Definition at line 756 of file clock.cxx.
References interval, Cyg_Scheduler::lock(), NULL, trigger, and Cyg_Scheduler::unlock().
 {
     // Lock the scheduler while we do this to avoid
     // race conditions.
     Cyg_Scheduler::lock();
     if( t != NULL ) *t = trigger;
     if( i != NULL ) *i = interval;
     Cyg_Scheduler::unlock();
 }
void Cyg_Alarm::initialize (cyg_tick_count trigger, cyg_tick_count interval = 0)
Definition at line 667 of file clock.cxx.
References Cyg_Counter::add_alarm(), counter, CYG_REPORT_FUNCTION, enabled, interval, Cyg_Scheduler::lock(), Cyg_Counter::rem_alarm(), trigger, and Cyg_Scheduler::unlock().
Referenced by Cyg_Thread::set_timer().
 {
     CYG_REPORT_FUNCTION();
     Cyg_Scheduler::lock();
     // If already enabled, remove from counter
     if( enabled ) counter->rem_alarm(this);
     CYG_INSTRUMENT_ALARM( INIT,     this, 0 );
     CYG_INSTRUMENT_ALARM( TRIGGER,
                           ((cyg_uint32 *)&t)[0],
                           ((cyg_uint32 *)&t)[1] );
     CYG_INSTRUMENT_ALARM( INTERVAL,
                           ((cyg_uint32 *)&i)[0],
                           ((cyg_uint32 *)&i)[1] );
     trigger = t;
     interval = i;
     counter->add_alarm(this);
     Cyg_Scheduler::unlock();
 }
void Cyg_Alarm::synchronize (void) protected
Definition at line 701 of file clock.cxx.
References counter, Cyg_Counter::current_value(), interval, and trigger.
Referenced by Cyg_Counter::add_alarm(), and enable().
 {
     if( interval != 0 ) {
         // This expression sets the trigger to the next whole interval
         // at or after the current time. This means that alarms will
         // continue at the same intervals as if they had never been
         // disabled. The alternative would be to just set trigger to
         // (counter->counter + interval), but this is less satisfying
         // than preserving the original intervals. That behaviour can
         // always be obtained by using initialize() rather than
         // enable(), while the current behaviour would be more
         // difficult to achieve that way.
         cyg_tick_count d;
         d = counter->current_value() + interval - trigger;
         if ( d > interval ) {
             // then trigger was in the past, so resynchronize
             trigger += interval * ((d - 1) / interval );
         }
         // otherwise, we were just set up, so no worries.
     }
 }
Friends And Related Function Documentation
friend class Cyg_Counter friend
Definition at line 204 of file clock.hxx.
Member Data Documentation
cyg_alarm_fn* Cyg_Alarm::alarm protected
Definition at line 209 of file clock.hxx.
Referenced by Cyg_Counter::add_alarm(), Cyg_Alarm(), and Cyg_Counter::tick().
Cyg_Counter* Cyg_Alarm::counter protected
Definition at line 207 of file clock.hxx.
Referenced by Cyg_Alarm(), disable(), enable(), initialize(), and synchronize().
CYG_ADDRWORD Cyg_Alarm::data protected
Definition at line 211 of file clock.hxx.
Referenced by Cyg_Counter::add_alarm(), Cyg_Alarm(), and Cyg_Counter::tick().
cyg_bool Cyg_Alarm::enabled protected
Definition at line 217 of file clock.hxx.
Referenced by Cyg_Counter::add_alarm(), Cyg_Alarm(), disable(), enable(), initialize(), Cyg_Counter::rem_alarm(), and Cyg_Counter::tick().
cyg_tick_count Cyg_Alarm::interval protected
Definition at line 215 of file clock.hxx.
Referenced by Cyg_Counter::add_alarm(), Cyg_Alarm(), get_times(), initialize(), synchronize(), and Cyg_Counter::tick().
cyg_tick_count Cyg_Alarm::trigger protected
Definition at line 213 of file clock.hxx.
Referenced by Cyg_Counter::add_alarm(), Cyg_Alarm(), get_times(), initialize(), synchronize(), and Cyg_Counter::tick().
The documentation for this class was generated from the following files:
C:/Users/barry/Documents/GitHub/VEROS/Xinrui/20130621_refined_thread/clock.hxx
C:/Users/barry/Documents/GitHub/VEROS/Xinrui/20130621_refined_thread/clock.cxx