My Project: Cyg_Scheduler_Base Class Reference
Cyg_Scheduler_Base Class Reference
#include <sched.hxx>
Static Public Member Functions
static Cyg_Thread * get_current_thread ()
static void set_current_thread (Cyg_Thread *thread)
static void set_current_thread (Cyg_Thread *thread, HAL_SMP_CPU_TYPE cpu)
static void set_need_reschedule ()
static void set_need_reschedule (Cyg_Thread *thread)
static cyg_bool get_need_reschedule ()
static cyg_ucount32 get_sched_lock ()
static void clear_need_reschedule ()
static cyg_ucount32 get_thread_switches ()
Static Protected Attributes
static Cyg_Thread *volatile
current_thread[CYGNUM_KERNEL_CPU_MAX] CYGBLD_ANNOTATE_VARIABLE_SCHED
static volatile cyg_bool
need_reschedule[CYGNUM_KERNEL_CPU_MAX] CYGBLD_ANNOTATE_VARIABLE_SCHED
static volatile cyg_ucount32
thread_switches[CYGNUM_KERNEL_CPU_MAX] CYGBLD_ANNOTATE_VARIABLE_SCHED
Friends
class Cyg_HardwareThread
class Cyg_SchedThread
Additional Inherited Members
Protected Member Functions inherited from Cyg_Scheduler_SchedLock
Cyg_Scheduler_SchedLock ()
Static Protected Member Functions inherited from Cyg_Scheduler_SchedLock
static void inc_sched_lock ()
static void zero_sched_lock ()
static void set_sched_lock (cyg_uint32 new_lock)
static cyg_ucount32 get_sched_lock ()
Detailed Description
Definition at line 74 of file sched.hxx.
Member Function Documentation
void Cyg_Scheduler_Base::clear_need_reschedule () inline static
Definition at line 335 of file sched.hxx.
References CYG_KERNEL_CPU_THIS.
Referenced by Cyg_Scheduler::start_cpu(), Cyg_Scheduler::thread_entry(), and Cyg_Scheduler::unlock_inner().
 {
     need_reschedule[CYG_KERNEL_CPU_THIS()] = false;
 }
Cyg_Thread * Cyg_Scheduler_Base::get_current_thread () inline static
Definition at line 304 of file sched.hxx.
References CYG_KERNEL_CPU_THIS.
Referenced by Cyg_Thread::cancel_counted_wake(), Cyg_Thread::counted_sleep(), Cyg_Thread::counted_wake(), Cyg_Thread::force_resume(), interrupt_end(), Cyg_Thread::kill(), Cyg_Thread::reinitialize(), Cyg_Thread::resume(), Cyg_Thread::self(), Cyg_Thread::set_priority(), Cyg_Thread::sleep(), Cyg_Thread::suspend(), Cyg_Scheduler_Implementation::timeslice_cpu(), Cyg_Scheduler::unlock_inner(), and Cyg_Thread::wake().
 {
     return current_thread[CYG_KERNEL_CPU_THIS()];
 }
cyg_bool Cyg_Scheduler_Base::get_need_reschedule () inline static
Definition at line 320 of file sched.hxx.
References CYG_KERNEL_CPU_THIS.
Referenced by Cyg_Scheduler::unlock_inner(), and Cyg_SchedThread_Implementation::yield().
 {
     return need_reschedule[CYG_KERNEL_CPU_THIS()];
 }
cyg_ucount32 Cyg_Scheduler_Base::get_sched_lock () inline static
Definition at line 340 of file sched.hxx.
References Cyg_Scheduler_SchedLock::get_sched_lock().
Referenced by Cyg_Counter::add_alarm(), Cyg_Interrupt::call_pending_DSRs(), idle_thread_main(), Cyg_Scheduler::lock(), Cyg_Counter::rem_alarm(), Cyg_Scheduler::reschedule(), Cyg_Scheduler::thread_entry(), Cyg_Scheduler_Implementation::timeslice_cpu(), Cyg_Scheduler::unlock(), Cyg_Scheduler::unlock_inner(), Cyg_Scheduler::unlock_reschedule(), and Cyg_Scheduler::unlock_simple().
 {
     return Cyg_Scheduler_SchedLock::get_sched_lock();
 }
cyg_ucount32 Cyg_Scheduler_Base::get_thread_switches () inline static
Definition at line 346 of file sched.hxx.
References CYG_KERNEL_CPU_THIS.
 {
     return thread_switches[CYG_KERNEL_CPU_THIS()];
 }
void Cyg_Scheduler_Base::set_current_thread (Cyg_Thread * thread) inline static
Definition at line 309 of file sched.hxx.
References CYG_KERNEL_CPU_THIS.
Referenced by Cyg_Scheduler::start_cpu(), and Cyg_Scheduler::thread_entry().
 {
     current_thread[CYG_KERNEL_CPU_THIS()] = thread;
 }
void Cyg_Scheduler_Base::set_current_thread (Cyg_Thread * thread, HAL_SMP_CPU_TYPE cpu) inline static
Definition at line 314 of file sched.hxx.
 {
     current_thread[cpu] = thread;
 }
void Cyg_Scheduler_Base::set_need_reschedule () inline static
Definition at line 325 of file sched.hxx.
References CYG_KERNEL_CPU_THIS.
 {
     need_reschedule[CYG_KERNEL_CPU_THIS()] = true;
 }
void Cyg_Scheduler_Base::set_need_reschedule (Cyg_Thread * thread) inline static
Definition at line 330 of file sched.hxx.
References CYG_KERNEL_CPU_THIS.
 {
     need_reschedule[CYG_KERNEL_CPU_THIS()] = true;
 }
Friends And Related Function Documentation
friend class Cyg_HardwareThread friend
Definition at line 77 of file sched.hxx.
friend class Cyg_SchedThread friend
Definition at line 78 of file sched.hxx.
Member Data Documentation
Cyg_Thread* volatile current_thread [CYGNUM_KERNEL_CPU_MAX] Cyg_Scheduler_Base::CYGBLD_ANNOTATE_VARIABLE_SCHED static protected
Definition at line 86 of file sched.hxx.
volatile cyg_bool need_reschedule [CYGNUM_KERNEL_CPU_MAX] Cyg_Scheduler_Base::CYGBLD_ANNOTATE_VARIABLE_SCHED static protected
Definition at line 90 of file sched.hxx.
volatile cyg_ucount32 thread_switches [CYGNUM_KERNEL_CPU_MAX] Cyg_Scheduler_Base::CYGBLD_ANNOTATE_VARIABLE_SCHED static protected
Definition at line 94 of file sched.hxx.
The documentation for this class was generated from the following file:
C:/Users/barry/Documents/GitHub/VEROS/Xinrui/20130621_refined_thread/sched.hxx