My Project: Cyg_ThreadQueue_Implementation Class Reference
Cyg_ThreadQueue_Implementation Class Reference
#include <mlqueue.hxx>
Protected Member Functions
Cyg_ThreadQueue_Implementation ()
void enqueue (Cyg_Thread *thread)
Cyg_Thread * highpri ()
Cyg_Thread * dequeue ()
void remove (Cyg_Thread *thread)
Private Member Functions
void set_thread_queue (Cyg_Thread *thread, Cyg_ThreadQueue *tq)
Friends
class Cyg_Scheduler_Implementation
class Cyg_SchedThread_Implementation
Additional Inherited Members
Public Member Functions inherited from Cyg_CList_T< Cyg_Thread >
Cyg_CList_T ()
~Cyg_CList_T ()
Cyg_Thread * get_head ()
Cyg_Thread * get_tail ()
Cyg_Thread * rem_head ()
Cyg_Thread * rem_tail ()
Detailed Description
Definition at line 104 of file mlqueue.hxx.
Constructor & Destructor Documentation
Cyg_ThreadQueue_Implementation::Cyg_ThreadQueue_Implementation () inline protected
Definition at line 117 of file mlqueue.hxx.
 {};   // Constructor
Member Function Documentation
Cyg_Thread * Cyg_ThreadQueue_Implementation::dequeue (void) protected
Definition at line 639 of file mlqueue.cxx.
References CYG_REPORT_FUNCTYPE, CYG_REPORT_RETVAL, NULL, and Cyg_CList_T< Cyg_Thread >::rem_head().
Referenced by Cyg_ThreadQueue::dequeue().
 {
     CYG_REPORT_FUNCTYPE("returning thread %08x");
     Cyg_Thread *thread = rem_head();
     CYG_INSTRUMENT_MLQ( DEQUEUE, this, thread );
     if( thread != NULL )
         thread->queue = NULL;
     CYG_REPORT_RETVAL(thread);
     return thread;
 }
void Cyg_ThreadQueue_Implementation::enqueue (Cyg_Thread * thread) protected
Definition at line 554 of file mlqueue.cxx.
References Cyg_CList::add_tail(), Cyg_DNode::append(), CYG_CLASSFROMBASE, CYG_REPORT_FUNCARG1, CYG_REPORT_FUNCTION, CYG_REPORT_RETURN, Cyg_CList_T< Cyg_Thread >::get_head(), Cyg_DNode_T< T >::get_next(), Cyg_DNode_T< T >::get_prev(), Cyg_CList_T< Cyg_Thread >::get_tail(), Cyg_DNode::insert(), NULL, Cyg_SchedThread_Implementation::priority, and Cyg_CList::to_head().
Referenced by Cyg_ThreadQueue::enqueue().
 {
     CYG_REPORT_FUNCTION();
     CYG_REPORT_FUNCARG1("thread=%08x", thread);
     CYG_INSTRUMENT_MLQ( ENQUEUE, this, thread );
 #ifdef CYGIMP_KERNEL_SCHED_SORTED_QUEUES
     // Insert the thread into the queue in priority order.
     Cyg_Thread *qhead = get_head();
     if( qhead == NULL ) add_tail( thread );
     else if( qhead == qhead->get_next() )
     {
         // There is currently only one thread in the queue, join it
         // and adjust the queue pointer to point to the highest
         // priority of the two. If they are the same priority,
         // leave the pointer pointing to the oldest.
         qhead->insert( thread );
         if( thread->priority < qhead->priority )
             to_head(thread);
     }
     else
     {
         // There is more than one thread in the queue. First check
         // whether we are of higher priority than the head and if
         // so just jump in at the front. Also check whether we are
         // lower priority than the tail and jump onto the end.
         // Otherwise we really have to search the queue to find
         // our place.
         if( thread->priority < qhead->priority )
         {
             qhead->insert( thread );
             to_head(thread);
         }
         else if( thread->priority > get_tail()->priority )
         {
             // We are lower priority than any thread in the queue,
             // go in at the end.
             add_tail( thread );
         }
         else
         {
             // Search the queue. We do this backwards so that we
             // always add new threads after any that have the same
             // priority.
             // Because of the previous tests we know that this
             // search will terminate before we hit the head of the
             // queue, hence we do not need to check for that
             // condition.
             Cyg_Thread *qtmp = get_tail();
             // Scan the queue until we find a higher or equal
             // priority thread.
             while( qtmp->priority > thread->priority )
                 qtmp = qtmp->get_prev();
             // Append ourself after the node pointed to by qtmp.
             qtmp->append( thread );
         }
     }
 #else
     // Just add the thread to the tail of the list
     add_tail( thread );
 #endif
     thread->queue = CYG_CLASSFROMBASE(Cyg_ThreadQueue,
                                       Cyg_ThreadQueue_Implementation,
                                       this);
     CYG_REPORT_RETURN();
 }
Cyg_Thread * Cyg_ThreadQueue_Implementation::highpri (void) protected
Definition at line 674 of file mlqueue.cxx.
References CYG_REPORT_FUNCTYPE, CYG_REPORT_RETVAL, and Cyg_CList_T< Cyg_Thread >::get_head().
Referenced by Cyg_ThreadQueue::highpri().
 {
     CYG_REPORT_FUNCTYPE("returning thread %08x");
     CYG_REPORT_RETVAL(get_head());
     return get_head();
 }
void Cyg_ThreadQueue_Implementation::remove (Cyg_Thread * thread) protected
Definition at line 657 of file mlqueue.cxx.
References CYG_REPORT_FUNCARG1, CYG_REPORT_FUNCTION, CYG_REPORT_RETURN, NULL, and Cyg_CList::remove().
Referenced by Cyg_ThreadQueue::remove().
 {
     CYG_REPORT_FUNCTION();
     CYG_REPORT_FUNCARG1("thread=%08x", thread);
     CYG_INSTRUMENT_MLQ( REMOVE, this, thread );
     thread->queue = NULL;
     Cyg_CList_T<Cyg_Thread>::remove( thread );
     CYG_REPORT_RETURN();
 }
void Cyg_ThreadQueue_Implementation::set_thread_queue (Cyg_Thread * thread, Cyg_ThreadQueue * tq) inline private
Definition at line 684 of file mlqueue.cxx.
 {
     thread->queue = tq;
 }
Friends And Related Function Documentation
friend class Cyg_SchedThread_Implementation friend
Definition at line 108 of file mlqueue.hxx.
friend class Cyg_Scheduler_Implementation friend
Definition at line 107 of file mlqueue.hxx.
The documentation for this class was generated from the following files:
C:/Users/barry/Documents/GitHub/VEROS/Xinrui/20130621_refined_thread/mlqueue.hxx
C:/Users/barry/Documents/GitHub/VEROS/Xinrui/20130621_refined_thread/mlqueue.cxx