My Project: Cyg_Counter Class Reference
Cyg_Counter Class Reference
#include <clock.hxx>
Public Member Functions
CYGDBG_DEFINE_CHECK_THIS Cyg_Counter (cyg_uint32 increment=1)
~Cyg_Counter ()
cyg_tick_count current_value ()
cyg_uint32 current_value_lo ()
cyg_uint32 current_value_hi ()
void set_value (cyg_tick_count new_value)
void tick (cyg_uint32 ticks=1)
Private Member Functions
void add_alarm (Cyg_Alarm *alarm)
void rem_alarm (Cyg_Alarm *alarm)
Private Attributes
Cyg_Alarm_List alarm_list
volatile cyg_tick_count counter
cyg_uint32 increment
Friends
class Cyg_Alarm
Detailed Description
Definition at line 75 of file clock.hxx.
Constructor & Destructor Documentation
Cyg_Counter::Cyg_Counter (cyg_uint32 increment = 1)
Definition at line 81 of file clock.cxx.
References counter, CYG_REPORT_FUNCTION, and increment.
 {
     CYG_REPORT_FUNCTION();
     counter = 0;
     increment = incr;
 }
Cyg_Counter::~Cyg_Counter ()
Definition at line 95 of file clock.cxx.
References CYG_REPORT_FUNCTION.
 {
     CYG_REPORT_FUNCTION();
 }
Member Function Documentation
void Cyg_Counter::add_alarm (Cyg_Alarm * alarm) private
Definition at line 270 of file clock.cxx.
References Cyg_CList::add_tail(), Cyg_Alarm::alarm, alarm_list, counter, CYG_ASSERT, CYG_REPORT_FUNCTION, Cyg_Alarm::data, Cyg_Alarm::enabled, Cyg_CList_T< T >::get_head(), Cyg_Scheduler_Base::get_sched_lock(), Cyg_CList::insert(), Cyg_Alarm::interval, NULL, Cyg_Alarm::synchronize(), and Cyg_Alarm::trigger.
Referenced by Cyg_Alarm::enable(), Cyg_Alarm::initialize(), and tick().
 {
     CYG_REPORT_FUNCTION();
     CYG_ASSERTCLASS( this, "Bad counter object" );
     CYG_ASSERTCLASS( alarm, "Bad alarm passed" );
     CYG_ASSERT( Cyg_Scheduler::get_sched_lock() > 0, "Scheduler not locked");
     // set this now to allow an immediate handler call to manipulate
     // this alarm sensibly.
     alarm->enabled = true;
     // Check here for an alarm that triggers now or in the past and
     // call its alarm function immediately.
     if( alarm->trigger <= counter )
     {
         CYG_INSTRUMENT_ALARM( CALL, this, alarm );
         // call alarm function. Note that this is being
         // called here before the add_alarm has returned.
         // Note that this function may disable the alarm.
         alarm->alarm(alarm, alarm->data);
         // Note that this extra check on alarm->enabled is in case the
         // handler function disables this alarm!
         if( alarm->interval != 0 && alarm->enabled )
         {
             // The alarm has a retrigger interval.
             // Reset the trigger interval and drop
             // through to queue it.
             alarm->trigger += alarm->interval;
             // ensure the next alarm time is in our future, and in phase
             // with the original time requested.
             alarm->synchronize();
         }
         else
         {
             // The alarm is all done with, disable it
             // unlock and return.
             alarm->enabled = false;
             return;
         }
     }
     CYG_INSTRUMENT_ALARM( ADD, this, alarm );
     // Find the pointer to the relevant list _after_ a retrigger
     // alarm has been given its new trigger time.
     Cyg_Alarm_List *alarm_list_ptr;     // pointer to list
     alarm_list_ptr = &alarm_list;
 #ifdef CYGIMP_KERNEL_COUNTERS_SORT_LIST
     // Now that we have the list pointer, we can use common code for
     // both list organizations.
     Cyg_Alarm *list_alarm = alarm_list_ptr->get_head();
     if( list_alarm != NULL )
     {
         do
         {
             CYG_ASSERTCLASS(list_alarm, "Bad alarm in counter list" );
             // The alarms are in ascending trigger order. If we
             // find an alarm that triggers later than us, we go
             // in front of it.
             if( list_alarm->trigger > alarm->trigger )
             {
                 alarm_list_ptr->insert( list_alarm, alarm );
                 return;
             }
             list_alarm = list_alarm->get_next();
         } while( list_alarm != alarm_list_ptr->get_head() );
         // a lower or equal alarm time was not found, so drop through
         // so it is added to the list tail
     }
 #endif
     alarm_list_ptr->add_tail( alarm );
 }
cyg_tick_count Cyg_Counter::current_value () inline
Definition at line 65 of file clock.inl.
References counter.
Referenced by Cyg_Alarm::synchronize().
 {
     return counter;
 }
cyg_uint32 Cyg_Counter::current_value_hi () inline
Definition at line 75 of file clock.inl.
References counter.
 {
     return (counter>>32)&0xFFFFFFFF;
 }
cyg_uint32 Cyg_Counter::current_value_lo () inline
Definition at line 70 of file clock.inl.
References counter.
 {
     return counter&0xFFFFFFFF;
 }
void Cyg_Counter::rem_alarm (Cyg_Alarm * alarm) private
Definition at line 365 of file clock.cxx.
References alarm_list, CYG_ASSERT, CYG_REPORT_FUNCTION, Cyg_Alarm::enabled, Cyg_Scheduler_Base::get_sched_lock(), and Cyg_CList::remove().
Referenced by Cyg_Alarm::disable(), and Cyg_Alarm::initialize().
 {
     CYG_REPORT_FUNCTION();
     CYG_ASSERTCLASS( this, "Bad counter object" );
     CYG_ASSERTCLASS( alarm, "Bad alarm passed" );
     CYG_ASSERT( Cyg_Scheduler::get_sched_lock() > 0, "Scheduler not locked");
     Cyg_Alarm_List *alarm_list_ptr;     // pointer to list
     alarm_list_ptr = &alarm_list;
     // Now that we have the list pointer, we can use common code for
     // both list organizations.
     CYG_INSTRUMENT_ALARM( REM, this, alarm );
     alarm_list_ptr->remove( alarm );
     alarm->enabled = false;
 }
void Cyg_Counter::set_value (cyg_tick_count new_value) inline
Definition at line 81 of file clock.inl.
References counter.
 {
     counter = new_value;
 }
void Cyg_Counter::tick (cyg_uint32 ticks = 1)
Definition at line 132 of file clock.cxx.
References add_alarm(), Cyg_Alarm::alarm, alarm_list, counter, CYG_CLASSFROMBASE, Cyg_Alarm::data, Cyg_CList::empty(), Cyg_Alarm::enabled, Cyg_CList_T< T >::get_head(), increment, Cyg_Alarm::interval, Cyg_Scheduler::lock(), NULL, Cyg_CList_T< T >::rem_head(), Cyg_CList::remove(), Cyg_Alarm::trigger, and Cyg_Scheduler::unlock().
Referenced by idle_thread_main().
 {
 //    CYG_REPORT_FUNCTION();
     CYG_ASSERTCLASS( this, "Bad counter object" );
     // Increment the counter in a loop so we process
     // each tick separately. This is easier than trying
     // to cope with a range of increments.
     while( ticks-- )
     {
         Cyg_Scheduler::lock();
         // increment the counter, note that it is
         // allowed to wrap.
         counter += increment;
         // now check for any expired alarms
         Cyg_Alarm_List *alarm_list_ptr;     // pointer to list
         alarm_list_ptr = &alarm_list;
         // Now that we have the list pointer, we can use common code for
         // both list organizations.
 #ifdef CYGIMP_KERNEL_COUNTERS_SORT_LIST
         // With a sorted alarm list, we can simply pick alarms off the
         // front of the list until we find one that is in the future.
         while( !alarm_list_ptr->empty() )
         {
             Cyg_Alarm *alarm = alarm_list_ptr->get_head();
             CYG_ASSERTCLASS(alarm, "Bad alarm in counter list" );
             if( alarm->trigger <= counter )
             {
                 // remove alarm from list
                 alarm_list_ptr->rem_head();
                 if( alarm->interval != 0 )
                 {
                     // The alarm has a retrigger interval.
                     // Reset the trigger time and requeue
                     // the alarm.
                     alarm->trigger += alarm->interval;
                     add_alarm( alarm );
                 }
                 else alarm->enabled = false;
                 CYG_INSTRUMENT_ALARM( CALL, this, alarm );
                 // call alarm function
                 alarm->alarm(alarm, alarm->data);
                 // all done, loop
             }
             else break;
         }
 #else
         // With unsorted lists we must scan the whole list for
         // candidates. However, we must be careful here since it is
         // possible for the function of one alarm to add or remove
         // other alarms to/from this list. Having the list shift under
         // our feet in this way could be disasterous. We solve this by
         // restarting the scan from the beginning whenever we call an
         // alarm function.
         cyg_bool rescan = true;
         while( rescan )
         {
             Cyg_DNode_T<Cyg_Alarm> *node = alarm_list_ptr->get_head();
             rescan = false;
             while( node != NULL )
             {
                 Cyg_Alarm *alarm = CYG_CLASSFROMBASE( Cyg_Alarm, Cyg_DNode, node );
                 Cyg_DNode_T<Cyg_Alarm> *next = alarm->get_next();
                 CYG_ASSERTCLASS(alarm, "Bad alarm in counter list" );
                 if( alarm->trigger <= counter )
                 {
                     alarm_list_ptr->remove(alarm);
                     if( alarm->interval != 0 )
                     {
                         // The alarm has a retrigger interval.
                         // Reset the trigger time and requeue
                         // the alarm.
                         alarm->trigger += alarm->interval;
                         add_alarm( alarm );
                     }
                     else alarm->enabled = false;
                     CYG_INSTRUMENT_ALARM( CALL, this, alarm );
                     // Call alarm function
                     alarm->alarm(alarm, alarm->data);
                     rescan = true;
                     break;
                 }
                 // If the next node is the head of the list, then we have
                 // looped all the way around. The node == next test
                 // catches the case where we only had one element to start
                 // with.
                 if( next == alarm_list_ptr->get_head() || node == next )
                     node = NULL;
                 else
                     node = next;
             }
         }
 #endif
         Cyg_Scheduler::unlock();
     }
 }
Friends And Related Function Documentation
friend class Cyg_Alarm friend
Definition at line 78 of file clock.hxx.
Member Data Documentation
Cyg_Alarm_List Cyg_Counter::alarm_list private
Definition at line 82 of file clock.hxx.
Referenced by add_alarm(), rem_alarm(), and tick().
volatile cyg_tick_count Cyg_Counter::counter private
Definition at line 85 of file clock.hxx.
Referenced by add_alarm(), current_value(), current_value_hi(), current_value_lo(), Cyg_Counter(), set_value(), and tick().
cyg_uint32 Cyg_Counter::increment private
Definition at line 87 of file clock.hxx.
Referenced by Cyg_Counter(), and tick().
The documentation for this class was generated from the following files:
C:/Users/barry/Documents/GitHub/VEROS/Xinrui/20130621_refined_thread/clock.hxx
C:/Users/barry/Documents/GitHub/VEROS/Xinrui/20130621_refined_thread/clock.cxx
C:/Users/barry/Documents/GitHub/VEROS/Xinrui/20130621_refined_thread/clock.inl