My Project: Cyg_CList_T< T > Class Template Reference
Cyg_CList_T< T > Class Template Reference
#include <clist.hxx>
Public Member Functions
Cyg_CList_T ()
~Cyg_CList_T ()
T * get_head ()
T * get_tail ()
T * rem_head ()
T * rem_tail ()
Public Member Functions inherited from Cyg_CList
Cyg_CList ()
Cyg_DNode * get_head ()
Cyg_DNode * get_tail ()
cyg_bool empty ()
void add_head (Cyg_DNode *node)
Cyg_DNode * rem_head ()
void add_tail (Cyg_DNode *node)
Cyg_DNode * rem_tail ()
void merge (Cyg_CList &list)
void remove (Cyg_DNode *node)
void rotate ()
void to_head (Cyg_DNode *node)
void insert (Cyg_DNode *list_node, Cyg_DNode *node)
~Cyg_CList ()
Detailed Description
template<class T>
class Cyg_CList_T< T >
Definition at line 304 of file clist.hxx.
Constructor & Destructor Documentation
template<class T> Cyg_CList_T< T >::Cyg_CList_T () inline
Definition at line 309 of file clist.hxx.
 {};
template<class T> Cyg_CList_T< T >::~Cyg_CList_T () inline
Definition at line 310 of file clist.hxx.
 {};
Member Function Documentation
template<class T> T* Cyg_CList_T< T >::get_head () inline
Definition at line 312 of file clist.hxx.
Referenced by Cyg_Counter::add_alarm(), Cyg_Scheduler_Implementation::schedule(), Cyg_Counter::tick(), Cyg_Scheduler_Implementation::timeslice_cpu(), and Cyg_SchedThread_Implementation::yield().
     {
         Cyg_DNode *node = Cyg_CList::get_head();
         if( node ) return CYG_CLASSFROMBASE( T, Cyg_DNode, node );
         return NULL;
     };
template<class T> T* Cyg_CList_T< T >::get_tail () inline
Definition at line 318 of file clist.hxx.
     {
         Cyg_DNode *node = Cyg_CList::get_tail();
         if( node ) return CYG_CLASSFROMBASE( T, Cyg_DNode, node );
         return NULL;
     };
template<class T> T* Cyg_CList_T< T >::rem_head () inline
Definition at line 325 of file clist.hxx.
Referenced by Cyg_Counter::tick().
     {
         Cyg_DNode *node = Cyg_CList::rem_head();
         if( node ) return CYG_CLASSFROMBASE( T, Cyg_DNode, node );
         return NULL;
     };
template<class T> T* Cyg_CList_T< T >::rem_tail () inline
Definition at line 332 of file clist.hxx.
     {
         Cyg_DNode *node = Cyg_CList::rem_tail();
         if( node ) return CYG_CLASSFROMBASE( T, Cyg_DNode, node );
         return NULL;
     };
The documentation for this class was generated from the following file:
C:/Users/barry/Documents/GitHub/VEROS/Xinrui/20130621_refined_thread/clist.hxx