My Project: Cyg_SchedThread Class Reference
Cyg_SchedThread Class Reference
#include <sched.hxx>
Public Member Functions
Cyg_SchedThread (Cyg_Thread *thread, CYG_ADDRWORD sched_info)
Cyg_ThreadQueue * get_current_queue ()
void remove ()
void set_asr_inhibit ()
void clear_asr_inhibit ()
Public Member Functions inherited from Cyg_SchedThread_Implementation
void timeslice_enable ()
void timeslice_disable ()
Public Member Functions inherited from Cyg_DNode_T< Cyg_Thread >
Cyg_DNode_T ()
~Cyg_DNode_T ()
Cyg_Thread * get_next ()
Cyg_Thread * get_prev ()
Public Member Functions inherited from Cyg_DNode
Cyg_DNode ()
Cyg_DNode * get_next ()
Cyg_DNode * get_prev ()
cyg_bool in_list ()
void insert (Cyg_DNode *node)
void append (Cyg_DNode *node)
void unlink ()
~Cyg_DNode ()
Private Attributes
Cyg_ThreadQueue * queue
Friends
class Cyg_ThreadQueue_Implementation
class Cyg_Scheduler_Implementation
class Cyg_Scheduler
Additional Inherited Members
Protected Member Functions inherited from Cyg_SchedThread_Implementation
Cyg_SchedThread_Implementation (CYG_ADDRWORD sched_info)
void yield ()
void to_queue_head (void)
void timeslice_save ()
void timeslice_restore ()
void timeslice_reset ()
Static Protected Member Functions inherited from Cyg_SchedThread_Implementation
static void rotate_queue (cyg_priority pri)
Protected Attributes inherited from Cyg_SchedThread_Implementation
cyg_priority priority
cyg_ucount32 timeslice_count
cyg_bool timeslice_enabled
Detailed Description
Definition at line 194 of file sched.hxx.
Constructor & Destructor Documentation
Cyg_SchedThread::Cyg_SchedThread (Cyg_Thread * thread, CYG_ADDRWORD sched_info)
Definition at line 408 of file sched.cxx.
References CYG_REPORT_FUNCTION, NULL, and queue.
 : Cyg_SchedThread_Implementation(sched_info)
 {
     CYG_REPORT_FUNCTION();
     queue = NULL;
 #ifdef CYGSEM_KERNEL_SYNCH_MUTEX_PRIORITY_INVERSION_PROTOCOL
     mutex_count = 0;
 #ifdef CYGSEM_KERNEL_SYNCH_MUTEX_PRIORITY_INVERSION_PROTOCOL_SIMPLE
     priority_inherited = false;
 #endif
 #endif
 }
Member Function Documentation
void Cyg_SchedThread::clear_asr_inhibit () inline
Definition at line 222 of file sched.hxx.
 { }
Cyg_ThreadQueue * Cyg_SchedThread::get_current_queue () inline
Definition at line 352 of file sched.hxx.
Referenced by Cyg_Thread::reinitialize(), Cyg_Thread::set_priority(), and Cyg_SchedThread_Implementation::to_queue_head().
 {
     return queue;
 }
void Cyg_SchedThread::remove () inline
Definition at line 155 of file sched.inl.
References NULL, queue, and Cyg_ThreadQueue::remove().
Referenced by Cyg_Scheduler_Implementation::add_thread().
 {
     if( queue != NULL )
     {
         queue->remove((Cyg_Thread *)this);
         queue = NULL;
     }
 }
void Cyg_SchedThread::set_asr_inhibit () inline
Definition at line 221 of file sched.hxx.
 { }
Friends And Related Function Documentation
friend class Cyg_Scheduler friend
Definition at line 199 of file sched.hxx.
friend class Cyg_Scheduler_Implementation friend
Definition at line 198 of file sched.hxx.
friend class Cyg_ThreadQueue_Implementation friend
Definition at line 197 of file sched.hxx.
Member Data Documentation
Cyg_ThreadQueue* Cyg_SchedThread::queue private
Definition at line 201 of file sched.hxx.
Referenced by Cyg_SchedThread(), remove(), and Cyg_Thread::set_priority().
The documentation for this class was generated from the following files:
C:/Users/barry/Documents/GitHub/VEROS/Xinrui/20130621_refined_thread/sched.hxx
C:/Users/barry/Documents/GitHub/VEROS/Xinrui/20130621_refined_thread/sched.cxx
C:/Users/barry/Documents/GitHub/VEROS/Xinrui/20130621_refined_thread/sched.inl