My Project: Cyg_Scheduler_SchedLock Class Reference
Cyg_Scheduler_SchedLock Class Reference
#include <smp.hxx>
Protected Member Functions
Cyg_Scheduler_SchedLock ()
Static Protected Member Functions
static void inc_sched_lock ()
static void zero_sched_lock ()
static void set_sched_lock (cyg_uint32 new_lock)
static cyg_ucount32 get_sched_lock ()
Static Private Attributes
static volatile cyg_ucount32
sched_lock CYGBLD_ANNOTATE_VARIABLE_SCHED
Detailed Description
Definition at line 165 of file smp.hxx.
Constructor & Destructor Documentation
Cyg_Scheduler_SchedLock::Cyg_Scheduler_SchedLock () inline protected
Definition at line 175 of file smp.hxx.
     {
         sched_lock = 1;
     };
Member Function Documentation
static cyg_ucount32 Cyg_Scheduler_SchedLock::get_sched_lock () inline static protected
Definition at line 202 of file smp.hxx.
Referenced by Cyg_Scheduler_Base::get_sched_lock().
     {
         return sched_lock;
     };
static void Cyg_Scheduler_SchedLock::inc_sched_lock () inline static protected
Definition at line 182 of file smp.hxx.
Referenced by Cyg_Scheduler::lock(), and Cyg_Scheduler::unlock_inner().
     {
         sched_lock++;
     };
static void Cyg_Scheduler_SchedLock::set_sched_lock (cyg_uint32 new_lock) inline static protected
Definition at line 195 of file smp.hxx.
References CYG_ASSERT.
Referenced by Cyg_Scheduler::unlock(), Cyg_Scheduler::unlock_inner(), and Cyg_Scheduler::unlock_simple().
     {
         CYG_ASSERT( new_lock > 0, "New scheduler lock value == 0");
         CYG_ASSERT( sched_lock > 0, "Scheduler lock == 0");
         sched_lock = new_lock;
     };
static void Cyg_Scheduler_SchedLock::zero_sched_lock () inline static protected
Definition at line 187 of file smp.hxx.
References CYG_ASSERT.
Referenced by Cyg_Scheduler::unlock_inner(), and Cyg_Scheduler::unlock_simple().
     {
         CYG_ASSERT( sched_lock != 0, "Scheduler lock already zero");
         sched_lock = 0;
     };
Member Data Documentation
volatile cyg_ucount32 sched_lock Cyg_Scheduler_SchedLock::CYGBLD_ANNOTATE_VARIABLE_SCHED static private
Definition at line 170 of file smp.hxx.
The documentation for this class was generated from the following file:
C:/Users/barry/Documents/GitHub/VEROS/Xinrui/20130621_refined_thread/smp.hxx