My Project: Cyg_SpinLock Class Reference
Cyg_SpinLock Class Reference
#include <smp.hxx>
Public Member Functions
Cyg_SpinLock ()
~Cyg_SpinLock ()
void spin ()
void clear ()
cyg_bool trylock ()
cyg_bool test ()
void spin_intsave (CYG_INTERRUPT_STATE *state)
void clear_intsave (CYG_INTERRUPT_STATE state)
Private Attributes
volatile cyg_uint32 lock
Detailed Description
Definition at line 100 of file smp.hxx.
Constructor & Destructor Documentation
Cyg_SpinLock::Cyg_SpinLock () inline
Definition at line 107 of file smp.hxx.
References lock.
 { lock = 0; };
Cyg_SpinLock::~Cyg_SpinLock () inline
Definition at line 109 of file smp.hxx.
References CYG_ASSERT, and lock.
     {
         CYG_ASSERT( lock == 0, "spinlock still claimed");
     };
Member Function Documentation
void Cyg_SpinLock::clear () inline
Definition at line 122 of file smp.hxx.
References CYG_ASSERT, and lock.
Referenced by clear_intsave().
     {
         CYG_ASSERT( lock != 0, "spinlock already cleared!");
         lock = 0;
     };
void Cyg_SpinLock::clear_intsave (CYG_INTERRUPT_STATE state) inline
Definition at line 154 of file smp.hxx.
References clear().
     {
         clear();
         HAL_RESTORE_INTERRUPTS(state);
     };
void Cyg_SpinLock::spin () inline
Definition at line 115 of file smp.hxx.
References CYG_ASSERT, and lock.
Referenced by spin_intsave().
     {
         CYG_ASSERT( lock == 0, "spinlock already claimed!");
         lock = 1;
     };
void Cyg_SpinLock::spin_intsave (CYG_INTERRUPT_STATE * state) inline
Definition at line 144 of file smp.hxx.
References spin().
     {
         CYG_INTERRUPT_STATE s;
         HAL_DISABLE_INTERRUPTS(s);
         *state = s;
         spin();
     };
cyg_bool Cyg_SpinLock::test () inline
Definition at line 136 of file smp.hxx.
References lock.
 { return lock; };
cyg_bool Cyg_SpinLock::trylock () inline
Definition at line 129 of file smp.hxx.
References lock.
     {
         if( lock ) return false;
         else { lock = 1; return true; }
     };
Member Data Documentation
volatile cyg_uint32 Cyg_SpinLock::lock private
Definition at line 102 of file smp.hxx.
Referenced by clear(), Cyg_SpinLock(), spin(), test(), trylock(), and ~Cyg_SpinLock().
The documentation for this class was generated from the following file:
C:/Users/barry/Documents/GitHub/VEROS/Xinrui/20130621_refined_thread/smp.hxx