My Project: Cyg_Scheduler_Implementation Class Reference
Cyg_Scheduler_Implementation Class Reference
#include <mlqueue.hxx>
Public Member Functions
void set_idle_thread (Cyg_Thread *thread, HAL_SMP_CPU_TYPE cpu)
void timeslice ()
void timeslice_cpu ()
Protected Member Functions
Cyg_Scheduler_Implementation ()
Cyg_Thread * schedule ()
void add_thread (Cyg_Thread *thread)
void rem_thread (Cyg_Thread *thread)
void register_thread (Cyg_Thread *thread)
void deregister_thread (Cyg_Thread *thread)
cyg_bool unique (cyg_priority priority)
Static Protected Member Functions
static void set_need_reschedule (Cyg_Thread *thread)
static void set_need_reschedule ()
Static Protected Attributes
static cyg_ucount32
timeslice_count[CYGNUM_KERNEL_CPU_MAX] CYGBLD_ANNOTATE_VARIABLE_SCHED
Static Protected Attributes inherited from Cyg_Scheduler_Base
static Cyg_Thread *volatile
current_thread[CYGNUM_KERNEL_CPU_MAX] CYGBLD_ANNOTATE_VARIABLE_SCHED
static volatile cyg_bool
need_reschedule[CYGNUM_KERNEL_CPU_MAX] CYGBLD_ANNOTATE_VARIABLE_SCHED
static volatile cyg_ucount32
thread_switches[CYGNUM_KERNEL_CPU_MAX] CYGBLD_ANNOTATE_VARIABLE_SCHED
Private Attributes
cyg_sched_bitmap queue_map
Cyg_RunQueue run_queue [CYGNUM_KERNEL_SCHED_PRIORITIES]
Friends
class Cyg_ThreadQueue_Implementation
class Cyg_SchedThread_Implementation
class Cyg_HardwareThread
void cyg_scheduler_set_need_reschedule ()
Additional Inherited Members
Static Public Member Functions inherited from Cyg_Scheduler_Base
static Cyg_Thread * get_current_thread ()
static void set_current_thread (Cyg_Thread *thread)
static void set_current_thread (Cyg_Thread *thread, HAL_SMP_CPU_TYPE cpu)
static void set_need_reschedule ()
static void set_need_reschedule (Cyg_Thread *thread)
static cyg_bool get_need_reschedule ()
static cyg_ucount32 get_sched_lock ()
static void clear_need_reschedule ()
static cyg_ucount32 get_thread_switches ()
Detailed Description
Definition at line 137 of file mlqueue.hxx.
Constructor & Destructor Documentation
Cyg_Scheduler_Implementation::Cyg_Scheduler_Implementation () protected
Definition at line 86 of file mlqueue.cxx.
References CYG_REPORT_FUNCTION, CYG_REPORT_RETURN, CYGNUM_KERNEL_CPU_MAX, and queue_map.
 {
     CYG_REPORT_FUNCTION();
     queue_map   = 0;
     for( int i = 0; i < CYGNUM_KERNEL_CPU_MAX; i++ )
     {
         timeslice_count[i] = CYGNUM_KERNEL_SCHED_TIMESLICE_TICKS;
         need_reschedule[i] = true;
     }
     CYG_REPORT_RETURN();
 }
Member Function Documentation
void Cyg_Scheduler_Implementation::add_thread (Cyg_Thread * thread) protected
Definition at line 145 of file mlqueue.cxx.
References Cyg_CList::add_tail(), CYG_ASSERT, CYG_REPORT_FUNCARG1, CYG_REPORT_FUNCTION, CYG_REPORT_RETURN, CYG_THREAD_MAX_PRIORITY, CYG_THREAD_MIN_PRIORITY, Cyg_CList::empty(), NULL, Cyg_SchedThread_Implementation::priority, queue_map, Cyg_SchedThread::remove(), run_queue, set_need_reschedule(), and Cyg_SchedThread_Implementation::timeslice_reset().
 {
     CYG_REPORT_FUNCTION();
     CYG_REPORT_FUNCARG1("thread=%08x", thread);
     cyg_priority pri                               = thread->priority;
     Cyg_RunQueue *queue = &run_queue[pri];
     CYG_INSTRUMENT_MLQ( ADD, thread, pri);
     CYG_ASSERT((CYG_THREAD_MIN_PRIORITY >= pri)
                && (CYG_THREAD_MAX_PRIORITY <= pri),
                "Priority out of range!");
     CYG_ASSERT( ((queue_map & (1<<pri))!=0) == ((!run_queue[pri].empty())!=0), "Map and queue disagree");
     // If the thread is on some other queue, remove it
     // here.
     if( thread->queue != NULL )
     {
         thread->queue->remove(thread);
     }
     if( queue->empty() )
     {
         // set the map bit and ask for a reschedule if this is a
         // new highest priority thread.
         queue_map |= (1<<pri);
     }
     // else the queue already has an occupant, queue behind him
     queue->add_tail(thread);
     // If the new thread is higher priority than any
     // current thread, request a reschedule.
     set_need_reschedule(thread);
     // Also reset the timeslice_count so that this thread gets a full
     // timeslice once it begins to run.
     thread->timeslice_reset();
     CYG_ASSERT( thread->queue == NULL , "Runnable thread on a queue!");
     CYG_ASSERT( queue_map != 0, "Run queue empty");
     CYG_ASSERT( queue_map & (1<<pri), "Queue map bit not set for pri");
     CYG_ASSERT( !run_queue[pri].empty(), "Queue for pri empty");
     CYG_ASSERT( ((queue_map & (1<<pri))!=0) == ((!run_queue[pri].empty())!=0), "Map and queue disagree");
     CYG_ASSERT( queue_map & (1<<CYG_THREAD_MIN_PRIORITY), "Idle thread vanished!!!");
     CYG_ASSERT( !run_queue[CYG_THREAD_MIN_PRIORITY].empty(), "Idle thread vanished!!!");
     CYG_REPORT_RETURN();
 }
void Cyg_Scheduler_Implementation::deregister_thread (Cyg_Thread * thread) protected
Definition at line 289 of file mlqueue.cxx.
References CYG_REPORT_FUNCARG1, CYG_REPORT_FUNCTION, and CYG_REPORT_RETURN.
 {
     CYG_REPORT_FUNCTION();
     CYG_REPORT_FUNCARG1("thread=%08x", thread);
     // No registration necessary in this scheduler
     CYG_REPORT_RETURN();
 }
void Cyg_Scheduler_Implementation::register_thread (Cyg_Thread * thread) protected
Definition at line 277 of file mlqueue.cxx.
References CYG_REPORT_FUNCARG1, CYG_REPORT_FUNCTION, and CYG_REPORT_RETURN.
 {
     CYG_REPORT_FUNCTION();
     CYG_REPORT_FUNCARG1("thread=%08x", thread);
     // No registration necessary in this scheduler
     CYG_REPORT_RETURN();
 }
void Cyg_Scheduler_Implementation::rem_thread (Cyg_Thread * thread) protected
Definition at line 205 of file mlqueue.cxx.
References CYG_ASSERT, CYG_REPORT_FUNCARG1, CYG_REPORT_FUNCTION, CYG_REPORT_RETURN, CYG_THREAD_MIN_PRIORITY, Cyg_CList::empty(), Cyg_SchedThread_Implementation::priority, queue_map, Cyg_CList::remove(), and run_queue.
 {
     CYG_REPORT_FUNCTION();
     CYG_REPORT_FUNCARG1("thread=%08x", thread);
     CYG_ASSERT( queue_map != 0, "Run queue empty");
     cyg_priority pri    = thread->priority;
     Cyg_RunQueue *queue = &run_queue[pri];
     CYG_INSTRUMENT_MLQ( REM, thread, pri);
     CYG_ASSERT( pri != CYG_THREAD_MIN_PRIORITY, "Idle thread trying to sleep!");
     CYG_ASSERT( !run_queue[CYG_THREAD_MIN_PRIORITY].empty(), "Idle thread vanished!!!");
     CYG_ASSERT( queue_map & (1<<pri), "Queue map bit not set for pri");
     CYG_ASSERT( !run_queue[pri].empty(), "Queue for pri empty");
     // remove thread from queue
     queue->remove(thread);
     if( queue->empty() )
     {
         // If this was only thread in
         // queue, clear map.
         queue_map &= ~(1<<pri);
     }
     CYG_ASSERT( queue_map != 0, "Run queue empty");
     CYG_ASSERT( queue_map & (1<<CYG_THREAD_MIN_PRIORITY), "Idle thread vanished!!!");
     CYG_ASSERT( !run_queue[CYG_THREAD_MIN_PRIORITY].empty(), "Idle thread vanished!!!");
     CYG_ASSERT( ((queue_map & (1<<pri))!=0) == ((!run_queue[pri].empty())!=0), "Map and queue disagree");
     CYG_REPORT_RETURN();
 }
Cyg_Thread * Cyg_Scheduler_Implementation::schedule (void) protected
Definition at line 108 of file mlqueue.cxx.
References CYG_ASSERT, CYG_REPORT_FUNCTYPE, CYG_REPORT_RETVAL, CYG_THREAD_MIN_PRIORITY, Cyg_CList::empty(), Cyg_CList_T< T >::get_head(), NULL, queue_map, and run_queue.
 {
     CYG_REPORT_FUNCTYPE("returning thread %08x");
     // The run queue may _never_ be empty, there is always
     // an idle thread at the lowest priority.
     CYG_ASSERT( queue_map != 0, "Run queue empty");
     CYG_ASSERT( queue_map & (1<<CYG_THREAD_MIN_PRIORITY), "Idle thread vanished!!!");
     CYG_ASSERT( !run_queue[CYG_THREAD_MIN_PRIORITY].empty(), "Idle thread vanished!!!");
     register cyg_uint32 index;
     HAL_LSBIT_INDEX(index, queue_map);
     Cyg_RunQueue *queue = &run_queue[index];
     CYG_ASSERT( !queue->empty(), "Queue for index empty");
     Cyg_Thread *thread = queue->get_head();
     CYG_INSTRUMENT_MLQ( SCHEDULE, thread, index);
     CYG_ASSERT( thread != NULL , "No threads in run queue");
     CYG_ASSERT( thread->queue == NULL , "Runnable thread on a queue!");
     CYG_REPORT_RETVAL(thread);
     return thread;
 }
void Cyg_Scheduler_Implementation::set_idle_thread (Cyg_Thread * thread, HAL_SMP_CPU_TYPE cpu)
Definition at line 261 of file mlqueue.cxx.
References Cyg_Thread::resume().
 {
     // Make the thread the current thread for this CPU.
     current_thread[cpu] = thread;
     // This will insert the thread in the run queues and make it
     // available to execute.
     thread->resume();
 }
void Cyg_Scheduler_Implementation::set_need_reschedule (Cyg_Thread * thread) static protected
Definition at line 249 of file mlqueue.cxx.
References Cyg_SchedThread_Implementation::priority, and Cyg_Thread::RUNNING.
Referenced by Cyg_SchedThread_Implementation::rotate_queue(), timeslice_cpu(), Cyg_SchedThread_Implementation::to_queue_head(), and Cyg_SchedThread_Implementation::yield().
 {
     if( current_thread[0]->priority > thread->priority ||
         current_thread[0]->get_state() != Cyg_Thread::RUNNING )
         need_reschedule[0] = true;
 }
void Cyg_Scheduler_Implementation::set_need_reschedule () inline static protected
Definition at line 214 of file mlqueue.hxx.
References CYG_KERNEL_CPU_THIS.
Referenced by add_thread(), and Cyg_Thread::set_priority().
 {
     need_reschedule[CYG_KERNEL_CPU_THIS()] = true;
 }
void Cyg_Scheduler_Implementation::timeslice (void)
Definition at line 317 of file mlqueue.cxx.
References CYG_KERNEL_CPU_THIS, and timeslice_cpu().
 {
     if( --timeslice_count[CYG_KERNEL_CPU_THIS()] == 0 )
         timeslice_cpu();
 }
void Cyg_Scheduler_Implementation::timeslice_cpu (void)
Definition at line 331 of file mlqueue.cxx.
References CYG_ASSERT, CYG_KERNEL_CPU_THIS, CYG_REPORT_RETURN, CYG_THREAD_MIN_PRIORITY, Cyg_Scheduler_Base::get_current_thread(), Cyg_CList_T< T >::get_head(), Cyg_Scheduler_Base::get_sched_lock(), Cyg_Thread::get_state(), HAL_SMP_CPU_TYPE, Cyg_SchedThread_Implementation::priority, queue_map, Cyg_CList::rotate(), run_queue, Cyg_Thread::RUNNING, set_need_reschedule(), and Cyg_SchedThread_Implementation::timeslice_enabled.
Referenced by timeslice().
 {
     Cyg_Thread *thread = get_current_thread();
     HAL_SMP_CPU_TYPE cpu_this = CYG_KERNEL_CPU_THIS();
     CYG_ASSERT( queue_map != 0, "Run queue empty");
     CYG_ASSERT( queue_map & (1<<CYG_THREAD_MIN_PRIORITY), "Idle thread vanished!!!");
     if( thread->timeslice_enabled &&
         timeslice_count[cpu_this] == 0 )
     if( timeslice_count[cpu_this] == 0 )
     {
         CYG_INSTRUMENT_SCHED(TIMESLICE,0,0);
         CYG_ASSERT( get_sched_lock() > 0 , "Timeslice called with zero sched_lock");
         // Only try to rotate the run queue if the current thread is running.
         // Otherwise we are going to reschedule anyway.
         if( thread->get_state() == Cyg_Thread::RUNNING )
         {
             Cyg_Scheduler *sched = &Cyg_Scheduler::scheduler;
             CYG_INSTRUMENT_MLQ( TIMESLICE, thread, 0);
             CYG_ASSERTCLASS( thread, "Bad current thread");
             CYG_ASSERTCLASS( sched, "Bad scheduler");
             cyg_priority pri    = thread->priority;
             Cyg_RunQueue *queue = &sched->run_queue[pri];
             queue->rotate();
             if( queue->get_head() != thread )
                 sched->set_need_reschedule();
             timeslice_count[cpu_this] = CYGNUM_KERNEL_SCHED_TIMESLICE_TICKS;
         }
     }
     CYG_ASSERT( queue_map & (1<<CYG_THREAD_MIN_PRIORITY), "Idle thread vanished!!!");
     CYG_ASSERT( !run_queue[CYG_THREAD_MIN_PRIORITY].empty(), "Idle thread vanished!!!");
 #ifdef CYGDBG_KERNEL_TRACE_TIMESLICE
     CYG_REPORT_RETURN();
 #endif
 }
cyg_bool Cyg_Scheduler_Implementation::unique (cyg_priority priority) protected
Definition at line 301 of file mlqueue.cxx.
References CYG_REPORT_FUNCARG1, CYG_REPORT_FUNCTYPE, and CYG_REPORT_RETVAL.
 {
     CYG_REPORT_FUNCTYPE("returning %d");
     CYG_REPORT_FUNCARG1("priority=%d", priority);
     // Priorities are not unique
     CYG_REPORT_RETVAL(true);
     return true;
 }
Friends And Related Function Documentation
friend class Cyg_HardwareThread friend
Definition at line 142 of file mlqueue.hxx.
friend class Cyg_SchedThread_Implementation friend
Definition at line 141 of file mlqueue.hxx.
void cyg_scheduler_set_need_reschedule () friend
friend class Cyg_ThreadQueue_Implementation friend
Definition at line 140 of file mlqueue.hxx.
Member Data Documentation
cyg_ucount32 timeslice_count [CYGNUM_KERNEL_CPU_MAX] Cyg_Scheduler_Implementation::CYGBLD_ANNOTATE_VARIABLE_SCHED static protected
Definition at line 162 of file mlqueue.hxx.
cyg_sched_bitmap Cyg_Scheduler_Implementation::queue_map private
Definition at line 146 of file mlqueue.hxx.
Referenced by add_thread(), Cyg_Scheduler_Implementation(), rem_thread(), schedule(), and timeslice_cpu().
Cyg_RunQueue Cyg_Scheduler_Implementation::run_queue[CYGNUM_KERNEL_SCHED_PRIORITIES] private
Definition at line 150 of file mlqueue.hxx.
Referenced by add_thread(), rem_thread(), schedule(), and timeslice_cpu().
The documentation for this class was generated from the following files:
C:/Users/barry/Documents/GitHub/VEROS/Xinrui/20130621_refined_thread/mlqueue.hxx
C:/Users/barry/Documents/GitHub/VEROS/Xinrui/20130621_refined_thread/mlqueue.cxx