My Project: C:/Users/barry/Documents/GitHub/VEROS/Xinrui/20130621_refined_thread/intr.hxx File Reference
intr.hxx File Reference
#include <cyg/kernel/ktypes.h>
#include <cyg/kernel/smp.hxx>
#include <cyg/hal/hal_arch.h>
#include <cyg/hal/hal_intr.h>
Classes
class Cyg_Interrupt
Macros
#define CYGNUM_HAL_ISR_TABLE_SIZE CYGNUM_HAL_ISR_COUNT
#define HAL_INTERRUPT_STACK_CALL_PENDING_DSRS() Cyg_Interrupt::call_pending_DSRs_inner()
Typedefs
typedef void cyg_VSR ()
typedef cyg_uint32 cyg_ISR (cyg_vector vector, CYG_ADDRWORD data)
typedef void cyg_DSR (cyg_vector vector, cyg_ucount32 count, CYG_ADDRWORD data)
Functions
externC void interrupt_end (cyg_uint32 isr_ret, Cyg_Interrupt *intr, HAL_SavedRegisters *ctx)
externC void cyg_interrupt_post_dsr (CYG_ADDRWORD intr_obj)
externC void cyg_interrupt_call_pending_DSRs (void)
Macro Definition Documentation
#define CYGNUM_HAL_ISR_TABLE_SIZE CYGNUM_HAL_ISR_COUNT
Definition at line 70 of file intr.hxx.
#define HAL_INTERRUPT_STACK_CALL_PENDING_DSRS () Cyg_Interrupt::call_pending_DSRs_inner()
Definition at line 108 of file intr.hxx.
Referenced by Cyg_Interrupt::call_pending_DSRs().
Typedef Documentation
typedef void cyg_DSR(cyg_vector vector, cyg_ucount32 count, CYG_ADDRWORD data)
Definition at line 96 of file intr.hxx.
typedef cyg_uint32 cyg_ISR(cyg_vector vector, CYG_ADDRWORD data)
Definition at line 88 of file intr.hxx.
typedef void cyg_VSR()
Definition at line 81 of file intr.hxx.
Function Documentation
externC void cyg_interrupt_call_pending_DSRs (void)
Definition at line 233 of file intr.cxx.
References Cyg_Interrupt::call_pending_DSRs_inner().
 {
     Cyg_Interrupt::call_pending_DSRs_inner();
 }
externC void cyg_interrupt_post_dsr (CYG_ADDRWORD intr_obj)
Definition at line 324 of file intr.cxx.
References Cyg_Interrupt::post_dsr().
 {
     Cyg_Interrupt* intr = (Cyg_Interrupt*) intr_obj;
     intr->post_dsr ();
 }
externC void interrupt_end (cyg_uint32 isr_ret, Cyg_Interrupt * intr, HAL_SavedRegisters * ctx)
Definition at line 334 of file intr.cxx.
References Cyg_Interrupt::CALL_DSR, CYG_UNUSED_PARAM, Cyg_Scheduler_Base::get_current_thread(), Cyg_Scheduler::lock(), NULL, Cyg_Interrupt::post_dsr(), Cyg_Scheduler::unlock(), and Cyg_Interrupt::vector.
 {
 //    CYG_REPORT_FUNCTION();
 #ifdef CYGPKG_KERNEL_SMP_SUPPORT
     Cyg_Scheduler::lock();
 #endif
     // Sometimes we have a NULL intr object pointer.
     cyg_vector vector = (intr!=NULL)?intr->vector:0;
     CYG_INSTRUMENT_INTR(END, vector, isr_ret);
     CYG_UNUSED_PARAM( cyg_vector, vector ); // prevent compiler warning
 #ifndef CYGIMP_KERNEL_INTERRUPTS_CHAIN
     // Only do this if we are in a non-chained configuration.
     // If we are chained, then chain_isr below will do the DSR
     // posting.
     if( isr_ret & Cyg_Interrupt::CALL_DSR && intr != NULL ) intr->post_dsr();
 #endif
 #ifdef CYGDBG_KERNEL_DEBUG_GDB_THREAD_SUPPORT
     // If we have GDB support enabled, and there is the possibility
     // that this thread will be context switched as a result of this
     // interrupt, then save the pointer to the saved thread context in
     // the thread object so that GDB can get a meaningful context to
     // look at.
     Cyg_Scheduler::get_current_thread()->set_saved_context(regs);
 #endif
     // Now unlock the scheduler, which may also call DSRs
     // and cause a thread switch to happen.
     Cyg_Scheduler::unlock();
 #ifdef CYGDBG_KERNEL_DEBUG_GDB_THREAD_SUPPORT
     Cyg_Scheduler::get_current_thread()->set_saved_context(0);
 #endif
     CYG_INSTRUMENT_INTR(RESTORE, vector, 0);
 }