My Project: C:/Users/barry/Documents/GitHub/VEROS/Xinrui/20130621_refined_thread/thread.cxx File Reference
thread.cxx File Reference
#include <pkgconf/kernel.h>
#include <cyg/hal/hal_arch.h>
#include <cyg/kernel/ktypes.h>
#include <cyg/infra/cyg_trac.h>
#include <cyg/infra/cyg_ass.h>
#include <cyg/kernel/instrmnt.h>
#include <cyg/kernel/thread.hxx>
#include <cyg/kernel/intr.hxx>
#include <cyg/kernel/thread.inl>
#include <cyg/kernel/sched.inl>
#include <cyg/kernel/clock.inl>
Classes
class Cyg_IdleThread
Functions
void * operator new (size_t size, Cyg_Thread *ptr)
void idle_thread_main (CYG_ADDRESS data)
Cyg_IdleThread idle_thread[CYGNUM_KERNEL_CPU_MAX] CYG_INIT_PRIORITY (IDLE_THREAD)
Variables
static cyg_uint16 next_unique_id = 1
cyg_uint32 volatile idle_thread_loops [CYGNUM_KERNEL_CPU_MAX]
static char idle_thread_stack [CYGNUM_KERNEL_CPU_MAX][CYGNUM_KERNEL_THREADS_IDLE_STACK_SIZE]
Function Documentation
Cyg_IdleThread idle_thread [CYGNUM_KERNEL_CPU_MAX] CYG_INIT_PRIORITY (IDLE_THREAD)
void idle_thread_main (CYG_ADDRESS data)
Definition at line 1222 of file thread.cxx.
References CYG_ASSERT, CYG_KERNEL_CPU_THIS, CYG_REPORT_FUNCTION, Cyg_Scheduler_Base::get_sched_lock(), Cyg_Clock::real_time_clock, Cyg_Counter::tick(), and Cyg_Thread::yield().
 {
     CYG_REPORT_FUNCTION();
     for(;;)
     {
         idle_thread_loops[CYG_KERNEL_CPU_THIS()]++;
         HAL_IDLE_THREAD_ACTION(idle_thread_loops[CYG_KERNEL_CPU_THIS()]);
         CYG_ASSERT( Cyg_Scheduler::get_sched_lock() == 0, "Scheduler lock not zero" );
 #if 0
         // For testing, it is useful to be able to fake
         // clock interrupts in the idle thread.
         Cyg_Clock::real_time_clock->tick();
 #endif
 #ifdef CYGIMP_IDLE_THREAD_YIELD
         // In single priority and non-preemptive systems,
         // the idle thread should yield repeatedly to
         // other threads.
         Cyg_Thread::yield();
 #endif
     }
 }
void* operator new (size_t size, Cyg_Thread * ptr) inline
Definition at line 166 of file thread.cxx.
 { return (void *)ptr; };
Variable Documentation
cyg_uint32 volatile idle_thread_loops[CYGNUM_KERNEL_CPU_MAX]
Definition at line 1214 of file thread.cxx.
char idle_thread_stack[CYGNUM_KERNEL_CPU_MAX][CYGNUM_KERNEL_THREADS_IDLE_STACK_SIZE] static
Definition at line 1216 of file thread.cxx.
cyg_uint16 next_unique_id = 1 static
Definition at line 159 of file thread.cxx.