My Project: C:/Users/barry/Dropbox/ecos/130721消息数据优化5/130721消息数据优化5/MessageData.h File Reference
MessageData.h File Reference
#include "mvb_project.h"
#include "mvb_def.h"
#include "hal.h"
Data Structures
struct MD_ABILITY_NODE
Macros
#define md_get_pre(address) ((md_ability_array[address].pre_high << 8) + md_ability_array[address].pre_low)
#define md_get_next(address) ((md_ability_array[address].next_high << 8) + md_ability_array[address].next_low)
#define md_set_pre(address, value)
#define md_set_next(address, value)
#define address_filter 0x0FFF
#define fcode_filter 0xF000
#define is_source() (this_addr == (current_mf & address_filter))
#define match_device_address() ((this_addr == (current_mf & address_filter)) && (((current_mf & fcode_filter) >> 12)== 14))
Functions
int send_general_request (void)
int send_group_request (int M, int C)
int send_single_request (int C)
int send_read_request (UNSIGNED16 device_address)
int event_identifier_response ()
int match_group_address ()
void bsp_handler ()
void slaveframe_handler ()
void timeout_handler ()
void collision_handler ()
void Fcode_9_handler ()
void Fcode_13_handler ()
void Fcode_14_handler ()
void Fcode_12_handler ()
Variables
struct MD_ABILITY_NODE md_ability_array [4096] ={{0,0,0,0}}
UNSIGNED8 md_ability_count = 0
UNSIGNED16 last_M
UNSIGNED16 last_C
UNSIGNED16 last_address = 0
int md_notime = 0
UNSIGNED16 group_filter [12] ={ 0x0800 , 0x0400 , 0x0200 , 0x0100 , 0x0080 , 0x0040 , 0x0020 , 0x0010 , 0x0008 , 0x0004 , 0x0002 , 0x0001 }
Macro Definition Documentation
#define address_filter 0x0FFF
Definition at line 30 of file MessageData.h.
Referenced by match_group_address().
#define fcode_filter 0xF000
Definition at line 31 of file MessageData.h.
#define is_source () (this_addr == (current_mf & address_filter))
Definition at line 94 of file MessageData.h.
Referenced by Fcode_12_handler().
#define match_device_address () ((this_addr == (current_mf & address_filter)) && (((current_mf & fcode_filter) >> 12)== 14))
Definition at line 100 of file MessageData.h.
Referenced by Fcode_14_handler().
#define md_get_next (address) ((md_ability_array[address].next_high << 8) + md_ability_array[address].next_low)
Definition at line 6 of file MessageData.h.
#define md_get_pre (address) ((md_ability_array[address].pre_high << 8) + md_ability_array[address].pre_low)
Definition at line 5 of file MessageData.h.
#define md_set_next (address, value)
Value:
{\
                                            md_ability_array[address].next_high = ( value >> 8 );\
                                            md_ability_array[address].next_low = ( value & 0xff);\
                                        }
Definition at line 11 of file MessageData.h.
#define md_set_pre (address, value)
Value:
{\
                                            md_ability_array[address].pre_high = ( value >> 8 );\
                                            md_ability_array[address].pre_low = ( value & 0xff);\
                                        }
Definition at line 7 of file MessageData.h.
Function Documentation
void bsp_handler ()
Definition at line 20 of file MessageData.c.
References last_address, md_get_next, md_notime, and send_read_request().
Referenced by md_context_process().
 {
 //diag_printf( "bsp\n" );
     if( !md_notime )
     {
         last_address = md_get_next(last_address);
         if( last_address == 0 )
             last_address = md_get_next(last_address);
         if( !md_notime )
             send_read_request( last_address );
     }
 }
void collision_handler ()
Definition at line 56 of file MessageData.c.
References last_address, md_get_next, md_notime, and send_read_request().
Referenced by md_context_process().
 {
 //diag_printf( "collision\n" );
     if( !md_notime )
     {
         last_address = md_get_next(last_address);
         if( last_address == 0 )
             last_address = md_get_next(last_address);
         if( !md_notime )
             send_read_request( last_address );
     }
 }
int event_identifier_response ()
Definition at line 155 of file MessageData.c.
References mvb_arm_send_slave_frame, and this_addr.
Referenced by Fcode_13_handler(), Fcode_14_handler(), and Fcode_9_handler().
 {
 #ifdef MVBPROJ_DEBUG_INFO
     printf( "send slave frame %x\n" , 0xC000 + this_addr );
 #endif
     mvb_arm_send_slave_frame( 0xC000 + this_addr );
 }
void Fcode_12_handler ()
Definition at line 107 of file MessageData.c.
References HAL_IO_ENUM_UART_NOT_EMPTY, HAL_IO_UART_CHECKBIT, is_source, and mvb_arm_send_message.
Referenced by mfprocess_handle().
 {
 //diag_printf( "12" );
     //last_addr = current_mf & address_filter;
     cyg_uint32 uart_checkbit;
     HAL_IO_UART_CHECKBIT(&uart_checkbit);
     if ( uart_checkbit == HAL_IO_ENUM_UART_NOT_EMPTY && is_source() )
     {
         mvb_arm_send_message();
     }
 }
void Fcode_13_handler ()
Definition at line 81 of file MessageData.c.
References event_identifier_response(), HAL_IO_ENUM_UART_NOT_EMPTY, HAL_IO_UART_CHECKBIT, and match_group_address().
Referenced by mfprocess_handle().
 {
 //diag_printf( "13" );
     //жϱ־λβٲãͷӦ֡
     cyg_uint32 uart_checkbit;
     HAL_IO_UART_CHECKBIT(&uart_checkbit);
     if ( uart_checkbit == HAL_IO_ENUM_UART_NOT_EMPTY )
     {
         if( match_group_address() )
             event_identifier_response();
     }
 }
void Fcode_14_handler ()
Definition at line 94 of file MessageData.c.
References event_identifier_response(), HAL_IO_ENUM_UART_NOT_EMPTY, HAL_IO_UART_CHECKBIT, and match_device_address.
Referenced by mfprocess_handle().
 {
 //diag_printf( "14" );
     //жϱ־λβٲãͷӦ֡
     cyg_uint32 uart_checkbit;
     HAL_IO_UART_CHECKBIT(&uart_checkbit);
     if ( uart_checkbit == HAL_IO_ENUM_UART_NOT_EMPTY )
     {
         if( match_device_address() )
             event_identifier_response();
     }
 }
void Fcode_9_handler ()
Definition at line 69 of file MessageData.c.
References event_identifier_response(), HAL_IO_ENUM_UART_NOT_EMPTY, and HAL_IO_UART_CHECKBIT.
Referenced by mfprocess_handle().
 {
 //diag_printf( "9" );
     cyg_uint32 uart_checkbit;
     HAL_IO_UART_CHECKBIT(&uart_checkbit);
     if ( uart_checkbit == HAL_IO_ENUM_UART_NOT_EMPTY )
     {
         //Ӧ֡
         event_identifier_response();
     }
 }
int match_group_address ()
Definition at line 163 of file MessageData.c.
References address_filter, current_mf, group_filter, last_C, last_M, and this_addr.
Referenced by Fcode_13_handler().
 {
     UNSIGNED16 device_address_tmp = current_mf & address_filter ;
     int i = 0 ;
     for( i = 0 ; i < 12 ; ++i )
     {
         if( ( device_address_tmp & group_filter[i] ) == 0 )
             break;
     }
     last_M = i + 1;
     last_C = device_address_tmp << ( last_M + 4 );
     last_C >>= ( last_M + 4 );
     int C_tmp = this_addr << ( last_M + 4 );
     C_tmp >>= ( last_M + 4 );
     if( last_C == C_tmp )
         return 1;
     return 0;
 }
int send_general_request (void)
Definition at line 124 of file MessageData.c.
References mvb_arm_send_main_frame.
 {
     mvb_arm_send_main_frame( 0x9110 );
 }
int send_group_request (int M, int C)
Definition at line 129 of file MessageData.c.
References mvb_arm_send_main_frame.
 {
     UNSIGNED16 frame = 0xD000;
     UNSIGNED16 tmp = 0x0000;
     int count = 0 ;
     for( count = 0 ; count < M ; ++count )
     {
         tmp += 1;
         tmp <<= 1;
     }
     tmp <<= ( 12 - M );
     frame += tmp;
     frame += C;
     mvb_arm_send_main_frame( frame );
 }
int send_read_request (UNSIGNED16 device_address)
Definition at line 150 of file MessageData.c.
References mvb_arm_send_main_frame.
Referenced by bsp_handler(), collision_handler(), slaveframe_handler(), and timeout_handler().
 {
     mvb_arm_send_main_frame( 0xC000 + device_address );
 }
int send_single_request (int C)
Definition at line 145 of file MessageData.c.
References mvb_arm_send_main_frame.
 {
     mvb_arm_send_main_frame( 0xE000 + C );
 }
void slaveframe_handler ()
Definition at line 32 of file MessageData.c.
References last_address, md_get_next, md_notime, and send_read_request().
Referenced by md_context_process().
 {
 //diag_printf( "slaveframe\n" );
     if( !md_notime )
     {
         last_address = md_get_next(last_address);
         if( last_address == 0 )
             last_address = md_get_next(last_address);
         if( !md_notime )
             send_read_request( last_address );
     }
 }
void timeout_handler ()
Definition at line 44 of file MessageData.c.
References last_address, md_get_next, md_notime, and send_read_request().
Referenced by md_context_process().
 {
 //diag_printf( "timeout\n" );
     if( !md_notime )
     {
         last_address = md_get_next(last_address);
         if( last_address == 0 )
             last_address = md_get_next(last_address);
         if( !md_notime )
             send_read_request( last_address );
     }
 }
Variable Documentation
UNSIGNED16 group_filter[12] ={ 0x0800 , 0x0400 , 0x0200 , 0x0100 , 0x0080 , 0x0040 , 0x0020 , 0x0010 , 0x0008 , 0x0004 , 0x0002 , 0x0001 }
Definition at line 38 of file MessageData.h.
Referenced by match_group_address().
UNSIGNED16 last_address = 0
Definition at line 35 of file MessageData.h.
Referenced by bsp_handler(), collision_handler(), slaveframe_handler(), and timeout_handler().
UNSIGNED16 last_C
Definition at line 34 of file MessageData.h.
Referenced by match_group_address().
UNSIGNED16 last_M
Definition at line 33 of file MessageData.h.
Referenced by match_group_address().
struct MD_ABILITY_NODE md_ability_array[4096] ={{0,0,0,0}}
Definition at line 24 of file MessageData.h.
UNSIGNED8 md_ability_count = 0
Definition at line 25 of file MessageData.h.
Referenced by build_list_of_devices_scan().
int md_notime = 0
Definition at line 36 of file MessageData.h.
Referenced by bsp_handler(), collision_handler(), notime_interrupt_isr(), slaveframe_handler(), supervisory_interrupt_isr(), and timeout_handler().