My Project: C:/Users/barry/Dropbox/ecos/130721消息数据优化5/130721消息数据优化5/intr.c File Reference
intr.c File Reference
#include "intr.h"
Functions
void exti_thread (cyg_addrword_t data)
void standup_alarm (cyg_handle_t alarm, cyg_addrword_t data)
void standup_thread (cyg_addrword_t data)
cyg_uint32 supervisory_interrupt_isr (cyg_vector_t vector, cyg_addrword_t data)
void supervisory_interrupt_dsr (cyg_vector_t vector, cyg_ucount32 count, cyg_addrword_t data)
cyg_uint32 timeout_interrupt_isr (cyg_vector_t vector, cyg_addrword_t data)
void timeout_interrupt_dsr (cyg_vector_t vector, cyg_ucount32 count, cyg_addrword_t data)
cyg_uint32 errorframe_interrupt_isr (cyg_vector_t vector, cyg_addrword_t data)
void errorframe_interrupt_dsr (cyg_vector_t vector, cyg_ucount32 count, cyg_addrword_t data)
cyg_uint32 mainframe_interrupt_isr (cyg_vector_t vector, cyg_addrword_t data)
void mainframe_interrupt_dsr (cyg_vector_t vector, cyg_ucount32 count, cyg_addrword_t data)
cyg_uint32 slaveframe_interrupt_isr (cyg_vector_t vector, cyg_addrword_t data)
void slaveframe_interrupt_dsr (cyg_vector_t vector, cyg_ucount32 count, cyg_addrword_t data)
cyg_uint32 sync_interrupt_isr (cyg_vector_t vector, cyg_addrword_t data)
void sync_interrupt_dsr (cyg_vector_t vector, cyg_ucount32 count, cyg_addrword_t data)
cyg_uint32 notime_interrupt_isr (cyg_vector_t vector, cyg_addrword_t data)
void notime_interrupt_dsr (cyg_vector_t vector, cyg_ucount32 count, cyg_addrword_t data)
void mfprocess_handle (cyg_vector_t vector)
void sfprocess_handle (cyg_vector_t vector)
void syncprocess_handle ()
Variables
bool wait_for_ba
cyg_uint32 frame_checkbit
cyg_uint32 sync_checkbit
cyg_uint32 sync_interrupt_flag
UNSIGNED16 current_mf
UNSIGNED16 last_mf
UNSIGNED16 current_sf
UNSIGNED16 last_sf
char standup_stack [SA_STACK_SIZE]
cyg_thread standup_thread_data
cyg_handle_t standup_thread_handle
int standup_flag = 0
UNSIGNED16 this_akey
UNSIGNED16 this_addr
MVB_ADMINISTRATOR mvb_administrator
MVB_DEVICE_STATUS mvb_device_status
cyg_uint16 mvb_device_status_16
UNSIGNED16 ba_mf
cyg_handle_t standup_counter_handle
cyg_tick_count_t standup_alarm_count
cyg_alarm standup_alarm_object
cyg_handle_t standup_alarm_handle
int md_notime
Function Documentation
void errorframe_interrupt_dsr (cyg_vector_t vector, cyg_ucount32 count, cyg_addrword_t data)
Definition at line 439 of file intr.c.
References MVB_DEVICE_STATUS::cs3, frame_checkbit, HAL_IO_ENUM_MAIN_FRAME, mvb_arm_master_led, mvb_arm_send_status, and mvb_device_status_16.
Referenced by exti_thread().
 {
 #ifdef MVBPROJ_DEBUG_INFO
     printf("[EXTI] ERRORFRAME_INTERRUPT_DSR\n");
 #endif
     if (frame_checkbit == HAL_IO_ENUM_MAIN_FRAME)
     {
 #ifdef MVBPROJ_DEBUG_REALTIME
     _debug_err_mf++;
 #endif // ifdef MVBPROJ_DEBUG_REALTIME
         if (mvb_device_status.cs3 == 1)
         {
             mvb_device_status.cs3 = 0;
             mvb_device_status_16 = *((cyg_uint16*)&mvb_device_status);
 #ifdef MVBPROJ_DEBUG_INFO
     printf("\t[BA] conflict\n");
     printf("SED SYNC.\n");
 #endif
 #ifdef MVBPROJ_LED_SUPPORT
     mvb_arm_master_led(0);
 #endif
             mvb_arm_send_status(mvb_device_status_16);
         }
     }
     else
     {
 #ifdef MVBPROJ_DEBUG_REALTIME
     _debug_err_sf++;
 #endif // ifdef MVBPROJ_DEBUG_REALTIME
     }
     cyg_interrupt_unmask(vector);
 }
cyg_uint32 errorframe_interrupt_isr (cyg_vector_t vector, cyg_addrword_t data)
Definition at line 409 of file intr.c.
References frame_checkbit, and HAL_IO_FRAME_CHECKBIT.
Referenced by exti_thread().
 {
     cyg_interrupt_mask(vector);
     cyg_interrupt_acknowledge(vector);
 #ifdef MVBPROJ_DEBUG_INFO
     printf("[EXTI] ERRORFRAME_INTERRUPT_ISR\n");
 #endif
     HAL_IO_FRAME_CHECKBIT(&frame_checkbit);
     return (CYG_ISR_HANDLED | CYG_ISR_CALL_DSR);
 }
void exti_thread (cyg_addrword_t data)
Definition at line 116 of file intr.c.
References errorframe_interrupt_dsr(), errorframe_interrupt_isr(), EXTI_ERROR_FRAME_PRI, EXTI_ERROR_FRAME_VECTOR, EXTI_MAIN_FRAME_PRI, EXTI_MAIN_FRAME_VECTOR, EXTI_NO_TIME_PRI, EXTI_NO_TIME_VECTOR, EXTI_SLAVE_FRAME_PRI, EXTI_SLAVE_FRAME_VECTOR, EXTI_SUPERVISORY_INT_PRI, EXTI_SUPERVISORY_INT_VECTOR, EXTI_SYNC_PRI, EXTI_SYNC_VECTOR, EXTI_TIMEOUT_PRI, EXTI_TIMEOUT_VECTOR, mainframe_interrupt_dsr(), mainframe_interrupt_isr(), mvb_arm_send_status, mvb_device_status_16, notime_interrupt_dsr(), notime_interrupt_isr(), slaveframe_interrupt_dsr(), slaveframe_interrupt_isr(), supervisory_interrupt_dsr(), supervisory_interrupt_handle(), supervisory_interrupt_isr(), sync_interrupt_dsr(), sync_interrupt_isr(), this_addr, timeout_interrupt_dsr(), and timeout_interrupt_isr().
Referenced by start_thread().
 {
     cyg_interrupt   supervisory_interrupt,
                     timeout_interrupt,
                     errorframe_interrupt,
                     mainframe_interrupt,
                     slaveframe_interrupt,
                     sync_interrupt,
                     notime_interrupt;
     cyg_handle_t    supervisory_interrupt_handle,
                     timeout_interrupt_handle,
                     errorframe_interrupt_handle,
                     mainframe_interrupt_handle,
                     slaveframe_interrupt_handle,
                     sync_interrupt_handle,
                     notime_interrupt_handle;
     cyg_interrupt_create(EXTI_SUPERVISORY_INT_VECTOR, EXTI_SUPERVISORY_INT_PRI, 0, supervisory_interrupt_isr, supervisory_interrupt_dsr, &supervisory_interrupt_handle, &supervisory_interrupt);
     cyg_interrupt_configure(EXTI_SUPERVISORY_INT_VECTOR, 0, 0);
     cyg_interrupt_attach(supervisory_interrupt_handle);
     cyg_interrupt_create(EXTI_TIMEOUT_VECTOR, EXTI_TIMEOUT_PRI, 0, timeout_interrupt_isr, timeout_interrupt_dsr, &timeout_interrupt_handle, &timeout_interrupt);
     cyg_interrupt_configure(EXTI_TIMEOUT_VECTOR, 0, 0);
     cyg_interrupt_attach(timeout_interrupt_handle);
     cyg_interrupt_create(EXTI_ERROR_FRAME_VECTOR, EXTI_ERROR_FRAME_PRI, 0, errorframe_interrupt_isr, errorframe_interrupt_dsr, &errorframe_interrupt_handle, &errorframe_interrupt);
     cyg_interrupt_configure(EXTI_ERROR_FRAME_VECTOR, 0, 0);
     cyg_interrupt_attach(errorframe_interrupt_handle);
     cyg_interrupt_create(EXTI_MAIN_FRAME_VECTOR, EXTI_MAIN_FRAME_PRI, 0, mainframe_interrupt_isr, mainframe_interrupt_dsr, &mainframe_interrupt_handle, &mainframe_interrupt);
     cyg_interrupt_configure(EXTI_MAIN_FRAME_VECTOR, 0, 0);
     cyg_interrupt_attach(mainframe_interrupt_handle);
     cyg_interrupt_create(EXTI_SLAVE_FRAME_VECTOR, EXTI_SLAVE_FRAME_PRI, 0, slaveframe_interrupt_isr, slaveframe_interrupt_dsr, &slaveframe_interrupt_handle, &slaveframe_interrupt);
     cyg_interrupt_configure(EXTI_SLAVE_FRAME_VECTOR, 0, 0);
     cyg_interrupt_attach(slaveframe_interrupt_handle);
     cyg_interrupt_create(EXTI_SYNC_VECTOR, EXTI_SYNC_PRI, 0, sync_interrupt_isr, sync_interrupt_dsr, &sync_interrupt_handle, &sync_interrupt);
     cyg_interrupt_configure(EXTI_SYNC_VECTOR, 0, 0);
     cyg_interrupt_attach(sync_interrupt_handle);
     cyg_interrupt_create(EXTI_NO_TIME_VECTOR, EXTI_NO_TIME_PRI, 0, notime_interrupt_isr, notime_interrupt_dsr, &notime_interrupt_handle, &notime_interrupt);
     cyg_interrupt_configure(EXTI_NO_TIME_VECTOR, 0, 0);
     cyg_interrupt_attach(notime_interrupt_handle);
 #ifdef MVBPROJ_BASIC_INFO_SUPPORT
     printf("Interrupt init :: attach completed\n\n");
     printf("Device address: 0x%04x (%d), status: 0x%04x, All clear.\n", this_addr, this_addr, mvb_device_status_16);
 #endif // ifdef MVBPROJ_BASIC_INFO_SUPPORT
     cyg_interrupt_unmask(EXTI_SUPERVISORY_INT_VECTOR);
     cyg_interrupt_unmask(EXTI_TIMEOUT_VECTOR);
     cyg_interrupt_unmask(EXTI_ERROR_FRAME_VECTOR);
     cyg_interrupt_unmask(EXTI_MAIN_FRAME_VECTOR);
     cyg_interrupt_unmask(EXTI_SLAVE_FRAME_VECTOR);
     cyg_interrupt_unmask(EXTI_SYNC_VECTOR);
     cyg_interrupt_unmask(EXTI_NO_TIME_VECTOR);
     cyg_interrupt_enable();
     mvb_arm_send_status(mvb_device_status_16);
     cyg_thread_exit();
 }
void mainframe_interrupt_dsr (cyg_vector_t vector, cyg_ucount32 count, cyg_addrword_t data)
Definition at line 552 of file intr.c.
Referenced by exti_thread().
 {
     cyg_interrupt_unmask(vector);
 }
cyg_uint32 mainframe_interrupt_isr (cyg_vector_t vector, cyg_addrword_t data)
Definition at line 490 of file intr.c.
References ba_mf, MVB_DEVICE_STATUS::cs3, current_mf, last_mf, mfprocess_handle(), mvb_arm_master_led, mvb_arm_receive_frame, mvb_arm_send_status, mvb_device_status_16, and wait_for_ba.
Referenced by exti_thread().
 {
     cyg_interrupt_mask(vector);
     cyg_interrupt_acknowledge(vector);
 #ifdef MVBPROJ_DEBUG_INFO
     printf("[EXTI] MAINFRAME_INTERRUPT_ISR\n");
 #endif
     wait_for_ba = false;
     last_mf = current_mf;
     mvb_arm_receive_frame(current_mf);
     /*
     cyg_interrupt_disable();
     printf("rev m_frame 0x%04x\n", current_mf);
     cyg_interrupt_enable();
     */
     if (mvb_device_status.cs3 == 1 && current_mf != ba_mf)
     {
         mvb_device_status.cs3 = 0;
         mvb_device_status_16 = *((cyg_uint16*)&mvb_device_status);
 #ifdef MVBPROJ_DEBUG_INFO
     printf("BA conflict, mf: 0x%04x, ba: 0x%04x\n", current_mf, ba_mf);
     printf("SED SYNC.\n");
 #endif
 #ifdef MVBPROJ_LED_SUPPORT
     mvb_arm_master_led(0);
 #endif
         mvb_arm_send_status(mvb_device_status_16);
     }
 #ifdef MVBPROJ_DEBUG_REALTIME
     _debug_success_mf++;
 #endif
 #ifdef MVBPROJ_DEBUG_INFO
     printf("[EXTI] MAINFRAME_INTERRUPT_DSR MF:0x%04x\n", current_mf);
 #endif
     mfprocess_handle(vector);
     cyg_interrupt_unmask(vector);
     return (CYG_ISR_HANDLED);
 }
void mfprocess_handle (cyg_vector_t vector)
Definition at line 738 of file intr.c.
References MVB_DEVICE_STATUS::ba, ba_init(), current_mf, Fcode_12_handler(), Fcode_13_handler(), Fcode_14_handler(), Fcode_9_handler(), FRAME_ADDRESS, FRAME_F_CODE, FRAME_F_CODE_12, FRAME_F_CODE_13, FRAME_F_CODE_14, FRAME_F_CODE_15, FRAME_F_CODE_8, FRAME_F_CODE_9, mvb_arm_send_slave_frame, mvb_device_status_16, sync_interrupt_flag, this_addr, and this_akey.
Referenced by mainframe_interrupt_isr().
 {
 /*
 if (FRAME_ADDRESS(current_mf) == this_addr)
 {
     switch (FRAME_F_CODE(current_mf))
     {
     case FRAME_F_CODE_8:
         if (mvb_device_status.ba == 1)
         {
             if (mvb_device_status.cs2 == 1)
             {
                 mvb_arm_send_slave_frame(0x8000 | this_akey);
                 ba_init(true);
             }
             else
             {
                 mvb_arm_send_slave_frame(0x0000);
             }
         }
         break;
     case FRAME_F_CODE_15:
         mvb_arm_send_slave_frame(mvb_device_status_16);
         break;
     }
 }
 */
     sync_interrupt_flag = 1;
 #ifdef MVBPROJ_DEBUG_INFO
     printf("[HANDLE] MFPROCESS MF:0x%04x\n", current_mf);
 #endif
     switch (FRAME_F_CODE(current_mf))
         {
         case FRAME_F_CODE_8:
             if (mvb_device_status.ba == 1 && FRAME_ADDRESS(current_mf) == this_addr)
             {
                 mvb_arm_send_slave_frame(0x8000 | this_akey);
                 ba_init(true);
             }
         break;
     case FRAME_F_CODE_15:
         if (FRAME_ADDRESS(current_mf) == this_addr)
         {
 #ifdef MVBPROJ_DEBUG_INFO
     printf("[HANDLE] MFPROCESS, sending status, F=15 Status=0x%04x\n", mvb_device_status_16);
 #endif
             mvb_arm_send_slave_frame(mvb_device_status_16);
         }
         break;
     case FRAME_F_CODE_9:
         Fcode_9_handler();
         break;
     case FRAME_F_CODE_13:
         Fcode_13_handler();
         break;
     case FRAME_F_CODE_14:
         Fcode_14_handler();
         break;
     case FRAME_F_CODE_12:
         Fcode_12_handler();
         break;
     }
 }
void notime_interrupt_dsr (cyg_vector_t vector, cyg_ucount32 count, cyg_addrword_t data)
Definition at line 717 of file intr.c.
Referenced by exti_thread().
 {
 #ifdef MVBPROJ_DEBUG_INFO
     printf("[EXTI] NOTIME_INTERRUPT_DSR\n");
 #endif
     cyg_interrupt_unmask(vector);
 }
cyg_uint32 notime_interrupt_isr (cyg_vector_t vector, cyg_addrword_t data)
Definition at line 689 of file intr.c.
References md_notime.
Referenced by exti_thread().
 {
     cyg_interrupt_mask(vector);
     cyg_interrupt_acknowledge(vector);
     md_notime = 1;
 #ifdef MVBPROJ_DEBUG_INFO
     printf("[EXTI] NOTIME_INTERRUPT_ISR\n");
 #endif
     cyg_interrupt_unmask(vector);
     return (CYG_ISR_HANDLED);
 }
void sfprocess_handle (cyg_vector_t vector)
Definition at line 819 of file intr.c.
References MVB_DEVICE_STATUS::ba, ba_context_process(), MVB_DEVICE_STATUS::cs3, current_mf, current_sf, FRAME_F_CODE, FRAME_F_CODE_15, and sync_interrupt_flag.
Referenced by slaveframe_interrupt_isr().
 {
     sync_interrupt_flag = 1;
 #ifdef MVBPROJ_DEBUG_INFO
     printf("[HANDLE] SFPROCESS SF:0x%04x\n", current_sf);
 #endif
     if (mvb_device_status.cs3 == 0)
     {
         if (mvb_device_status.ba == 1)
         {
             switch (FRAME_F_CODE(current_mf))
             {
             case FRAME_F_CODE_15:
                 //modify by lqc
                 //build_list_of_devices_scan(FRAME_ADDRESS(current_mf), current_sf, false);
                 break;
             }
         }
     }
     else
     {
         ba_context_process(FRAME_F_CODE(current_mf), current_sf, vector);
     }
 }
void slaveframe_interrupt_dsr (cyg_vector_t vector, cyg_ucount32 count, cyg_addrword_t data)
Definition at line 616 of file intr.c.
Referenced by exti_thread().
 {
     cyg_interrupt_unmask(vector);
 }
cyg_uint32 slaveframe_interrupt_isr (cyg_vector_t vector, cyg_addrword_t data)
Definition at line 572 of file intr.c.
References current_sf, last_sf, mvb_arm_receive_frame, and sfprocess_handle().
Referenced by exti_thread().
 {
     cyg_interrupt_mask(vector);
     cyg_interrupt_acknowledge(vector);
 #ifdef MVBPROJ_DEBUG_INFO
     printf("[EXTI] SLAVEFRAME_INTERRUPT_ISR\n");
 #endif
     last_sf = current_sf;
     mvb_arm_receive_frame(current_sf);
     /*
     cyg_interrupt_disable();
     printf("rev s_frame 0x%04x\n", current_sf);
     cyg_interrupt_enable();
     */
 #ifdef MVBPROJ_DEBUG_REALTIME
     _debug_success_sf++;
 #endif
 #ifdef MVBPROJ_DEBUG_INFO
     printf("[EXTI] SLAVEFRAME_INTERRUPT_DSR SF:0x%04x\n", current_sf);
 #endif
     sfprocess_handle(vector);
     cyg_interrupt_unmask(vector);
     return (CYG_ISR_HANDLED);
 }
void standup_alarm (cyg_handle_t alarm, cyg_addrword_t data)
Definition at line 195 of file intr.c.
References ba_init(), standup_alarm_handle, standup_flag, standup_thread_handle, and wait_for_ba.
Referenced by standup_thread().
 {
     if (wait_for_ba)
         ba_init(true);
     cyg_thread_kill(standup_thread_handle);
     cyg_alarm_delete(standup_alarm_handle);
     standup_flag = 0;
 }
void standup_thread (cyg_addrword_t data)
Definition at line 215 of file intr.c.
References standup_alarm(), standup_alarm_count, standup_alarm_handle, standup_counter_handle, standup_flag, and this_addr.
Referenced by timeout_interrupt_dsr().
 {
     standup_flag = 1;
 /*
     cyg_tick_count_t mainticks = cyg_current_time();
     cyg_tick_count_t slaveticks;
     while (wait_for_ba)
     {
         slaveticks = cyg_current_time();
         if ((UNSIGNED32)slaveticks - (UNSIGNED32)mainticks > this_addr)
         {
             ba_init(true);
             break;
         }
     }
     standup_flag = 0;
     cyg_interrupt_unmask(EXTI_TIMEOUT_VECTOR);
     cyg_thread_exit();
     */
     cyg_clock_to_counter(cyg_real_time_clock(), &standup_counter_handle);
     standup_alarm_count = 26 * (this_addr + 15) - 13;
     cyg_alarm_create(standup_counter_handle, standup_alarm, 0, &standup_alarm_handle, &standup_alarm_object);
     cyg_alarm_initialize(standup_alarm_handle, cyg_current_time() + standup_alarm_count, standup_alarm_count);
     cyg_alarm_enable(standup_alarm_handle);
     while (1)
     {
         cyg_thread_delay(10000);
     }
     //cyg_thread_exit();
 }
void supervisory_interrupt_dsr (cyg_vector_t vector, cyg_ucount32 count, cyg_addrword_t data)
Definition at line 300 of file intr.c.
Referenced by exti_thread().
 {
 #ifdef MVBPROJ_DEBUG_INFO
     printf("[EXTI] SUPERVISORY_INTERRUPT_DSR\n");
 #endif
     cyg_interrupt_unmask(vector);
 }
cyg_uint32 supervisory_interrupt_isr (cyg_vector_t vector, cyg_addrword_t data)
Definition at line 269 of file intr.c.
References md_notime, and supervisory_interrupt_handle().
Referenced by exti_thread().
 {
     cyg_interrupt_mask(vector);
     cyg_interrupt_acknowledge(vector);
 #ifdef MVBPROJ_DEBUG_INFO
     printf("[EXTI] SUPERVISORY_INTERRUPT_ISR\n");
 #endif
     md_notime = 0;
     supervisory_interrupt_handle();
     cyg_interrupt_unmask(vector);
     return (CYG_ISR_HANDLED);
 }
void sync_interrupt_dsr (cyg_vector_t vector, cyg_ucount32 count, cyg_addrword_t data)
Definition at line 664 of file intr.c.
References syncprocess_handle().
Referenced by exti_thread().
 {
 #ifdef MVBPROJ_DEBUG_REALTIME
     _debug_sync++;
 #endif
     syncprocess_handle();
     cyg_interrupt_unmask(vector);
 }
cyg_uint32 sync_interrupt_isr (cyg_vector_t vector, cyg_addrword_t data)
Definition at line 635 of file intr.c.
References HAL_IO_SYNC_CHECKBIT, and sync_checkbit.
Referenced by exti_thread().
 {
     cyg_interrupt_mask(vector);
     cyg_interrupt_acknowledge(vector);
     HAL_IO_SYNC_CHECKBIT(&sync_checkbit);
 #ifdef MVBPROJ_DEBUG_INFO
     printf("[EXTI] SYNC_INTERRUPT_ISR\n");
 #endif
     return (CYG_ISR_HANDLED | CYG_ISR_CALL_DSR);
 }
void syncprocess_handle ()
Definition at line 859 of file intr.c.
References MVB_DEVICE_STATUS::ba, MVB_DEVICE_STATUS::cs2, MVB_DEVICE_STATUS::cs3, FRAME_ADDRESS, HAL_IO_ENUM_SYNC_STATUS, mvb_arm_master_led, mvb_arm_receive_sync, mvb_arm_send_status, mvb_device_status_16, standup_alarm_count, STATUS_CHECK, sync_checkbit, sync_interrupt_flag, and this_addr.
Referenced by sync_interrupt_dsr().
 {
     if (sync_checkbit == HAL_IO_ENUM_SYNC_STATUS)
     {
         cyg_uint16 new_status_16;
         sync_interrupt_flag = 0;
         mvb_arm_receive_sync(new_status_16);
         MVB_DEVICE_STATUS new_status = *((MVB_DEVICE_STATUS*)&new_status_16);
         if ((sync_interrupt_flag == 0) && (STATUS_CHECK(new_status_16) == 0))
         {
             mvb_device_status_16 = new_status_16;
             mvb_device_status = new_status;
 #ifdef MVBPROJ_DEBUG_INFO
             printf("[EXTI] SYNC_INTERRUPT_DSR, Status = 0x%04x\n", mvb_device_status_16);
 #endif
             if (mvb_device_status.ba == 0 || mvb_device_status.cs3 == 0)
             {
 #ifdef MVBPROJ_LED_SUPPORT
                 mvb_arm_master_led(0);
 #endif
             }
         }
 #ifdef MVBPROJ_DEBUG_SYNC
 cyg_interrupt_disable();
 printf("[EXTI] SYNC_INTERRUPT_DSR, Status = 0x%04x\n", mvb_device_status_16);
 cyg_interrupt_enable();
 #endif // ifdef MVBPROJ_DEBUG_SYNC
     }
     else
     {
         cyg_uint16 content;
         sync_interrupt_flag = 0;
         mvb_arm_receive_sync(content);
         if (sync_interrupt_flag == 0)
         {
             //modify by lqc
             //build_list_of_devices_scan(this_addr, 0, true);
             this_addr = FRAME_ADDRESS(content);
             //modify by lqc
             //build_list_of_devices_scan(this_addr, mvb_device_status_16, false);
             standup_alarm_count = 26 * (this_addr + 15) - 13;
             if (((content >> 13) % 2) == 0 && mvb_device_status.ba == 1)
             {
                 mvb_device_status.ba = 0;
                 mvb_device_status.cs2 = 0;
                 mvb_device_status.cs3 = 0;
                 mvb_device_status_16 = *((cyg_uint16*)&mvb_device_status);
 #ifdef MVBPROJ_LED_SUPPORT
         mvb_arm_master_led(0);
 #endif
             }
             else if (((content >> 13) % 2) == 1 && mvb_device_status.ba == 0)
             {
                 mvb_device_status.ba = 1;
                 mvb_device_status.cs2 = 1;
                 mvb_device_status_16 = *((cyg_uint16*)&mvb_device_status);
             }
 #ifdef MVBPROJ_DEBUG_INFO
             printf("[EXTI] SYNC_INTERRUPT_DSR, Address = 0x%04x\n", content);
 #endif
 #ifdef MVBPROJ_DEBUG_SYNC
 cyg_interrupt_disable();
 printf("[EXTI] SYNC_INTERRUPT_DSR, Address = 0x%04x\n", content);
 cyg_interrupt_enable();
 #endif // ifdef MVBPROJ_DEBUG_SYNC
         }
     }
     if (STATUS_CHECK(mvb_device_status_16) == 0)
         mvb_arm_send_status(mvb_device_status_16);
 }
void timeout_interrupt_dsr (cyg_vector_t vector, cyg_ucount32 count, cyg_addrword_t data)
Definition at line 353 of file intr.c.
References MVB_DEVICE_STATUS::ba, ba_context_process(), MVB_DEVICE_STATUS::cs3, frame_checkbit, HAL_IO_ENUM_MAIN_FRAME, SA_STACK_SIZE, SA_WORKTHREAD_PRI, standup_flag, standup_stack, standup_thread(), standup_thread_handle, and wait_for_ba.
Referenced by exti_thread().
 {
 #ifdef MVBPROJ_DEBUG_INFO
     diag_printf("[EXTI] TIMEOUT_INTERRUPT_DSR\n");
 #endif
     if (frame_checkbit == HAL_IO_ENUM_MAIN_FRAME)
     {
 #ifdef MVBPROJ_DEBUG_REALTIME
     _debug_fail_mf++;
 #endif
         wait_for_ba = true;
         if (mvb_device_status.ba == 1 && standup_flag == 0 && mvb_device_status.cs3 == 0)
         {
             standup_flag = 1;
             cyg_thread_create(SA_WORKTHREAD_PRI, standup_thread, 0, "STANDUP THREAD", &standup_stack, SA_STACK_SIZE, &standup_thread_handle, &standup_thread_data);
             cyg_thread_resume(standup_thread_handle); // Start it
         }
     }
     else
     {
 #ifdef MVBPROJ_DEBUG_REALTIME
     _debug_fail_sf++;
 #endif
         if (mvb_device_status.cs3 == 0) // MAS
         {
             if (mvb_device_status.ba == 1)
             {
                 //modify by lqc
                 //build_list_of_devices_scan(FRAME_ADDRESS(current_mf), 0, false);
             }
         }
         else
         {
             ba_context_process(0, 0, vector);
         }
     }
     cyg_interrupt_unmask(vector);
 }
cyg_uint32 timeout_interrupt_isr (cyg_vector_t vector, cyg_addrword_t data)
Definition at line 323 of file intr.c.
References frame_checkbit, and HAL_IO_FRAME_CHECKBIT.
Referenced by exti_thread().
 {
     cyg_interrupt_mask(vector);
     cyg_interrupt_acknowledge(vector);
     HAL_IO_FRAME_CHECKBIT(&frame_checkbit);
 #ifdef MVBPROJ_DEBUG_INFO
     diag_printf("[EXTI] TIMEOUT_INTERRUPT_ISR\n");
 #endif
     return (CYG_ISR_HANDLED | CYG_ISR_CALL_DSR);
 }
Variable Documentation
UNSIGNED16 ba_mf
Definition at line 66 of file ba.c.
UNSIGNED16 current_mf
Definition at line 45 of file intr.c.
Referenced by devices_scan(), mainframe_interrupt_isr(), match_group_address(), mfprocess_handle(), and sfprocess_handle().
UNSIGNED16 current_sf
Definition at line 46 of file intr.c.
Referenced by sfprocess_handle(), and slaveframe_interrupt_isr().
cyg_uint32 frame_checkbit
Definition at line 44 of file intr.c.
Referenced by errorframe_interrupt_dsr(), errorframe_interrupt_isr(), timeout_interrupt_dsr(), and timeout_interrupt_isr().
UNSIGNED16 last_mf
Definition at line 45 of file intr.c.
Referenced by mainframe_interrupt_isr().
UNSIGNED16 last_sf
Definition at line 46 of file intr.c.
Referenced by slaveframe_interrupt_isr().
int md_notime
Definition at line 36 of file MessageData.h.
Referenced by bsp_handler(), collision_handler(), notime_interrupt_isr(), slaveframe_handler(), supervisory_interrupt_isr(), and timeout_handler().
MVB_ADMINISTRATOR mvb_administrator
Definition at line 46 of file init.c.
MVB_DEVICE_STATUS mvb_device_status
Definition at line 51 of file init.c.
cyg_uint16 mvb_device_status_16
Definition at line 52 of file init.c.
cyg_tick_count_t standup_alarm_count
Definition at line 70 of file intr.c.
Referenced by standup_thread(), and syncprocess_handle().
cyg_handle_t standup_alarm_handle
Definition at line 72 of file intr.c.
Referenced by standup_alarm(), and standup_thread().
cyg_alarm standup_alarm_object
Definition at line 71 of file intr.c.
cyg_handle_t standup_counter_handle
Definition at line 68 of file intr.c.
Referenced by standup_thread().
int standup_flag = 0
Definition at line 58 of file intr.c.
Referenced by standup_alarm(), standup_thread(), and timeout_interrupt_dsr().
char standup_stack[SA_STACK_SIZE]
Definition at line 54 of file intr.c.
Referenced by timeout_interrupt_dsr().
cyg_thread standup_thread_data
Definition at line 56 of file intr.c.
cyg_handle_t standup_thread_handle
Definition at line 57 of file intr.c.
Referenced by standup_alarm(), and timeout_interrupt_dsr().
cyg_uint32 sync_checkbit
Definition at line 44 of file intr.c.
Referenced by sync_interrupt_isr(), and syncprocess_handle().
cyg_uint32 sync_interrupt_flag
Definition at line 44 of file intr.c.
Referenced by mfprocess_handle(), sfprocess_handle(), and syncprocess_handle().
UNSIGNED16 this_addr
Definition at line 61 of file init.c.
UNSIGNED16 this_akey
Definition at line 60 of file init.c.
Referenced by create_structure(), and mfprocess_handle().
bool wait_for_ba
Definition at line 42 of file intr.c.
Referenced by mainframe_interrupt_isr(), standup_alarm(), and timeout_interrupt_dsr().