My Project: C:/Users/barry/Dropbox/ecos/130721消息数据优化5/130721消息数据优化5/main.h File Reference
main.h File Reference
#include "mvb_project.h"
#include "mvb_def.h"
#include "hal.h"
#include <cyg/kernel/kapi.h>
#include <pkgconf/system.h>
#include <stdio.h>
Macros
#define MVB_BUILD_DEFINITION 1122
#define STACK_SIZE 256
#define START_WORKTHREAD_PRI 0
#define EXTI_WORKTHREAD_PRI 1
#define LED_WORKTHREAD_PRI 3
#define LED_FREQUENCY 5000
Functions
void exti_thread (cyg_addrword_t data)
void start_thread (cyg_addrword_t data)
void led_thread (cyg_addrword_t data)
void cyg_start (void)
Macro Definition Documentation
#define EXTI_WORKTHREAD_PRI 1
Definition at line 37 of file main.h.
Referenced by start_thread().
#define LED_FREQUENCY 5000
Definition at line 52 of file main.h.
Referenced by led_thread().
#define LED_WORKTHREAD_PRI 3
Definition at line 38 of file main.h.
Referenced by start_thread().
#define MVB_BUILD_DEFINITION 1122
Definition at line 30 of file main.h.
Referenced by cyg_start().
#define STACK_SIZE 256
Definition at line 33 of file main.h.
Referenced by cyg_start(), and start_thread().
#define START_WORKTHREAD_PRI 0
Definition at line 36 of file main.h.
Referenced by cyg_start().
Function Documentation
void cyg_start (void)
Definition at line 57 of file main.c.
References mvb_arm_init_led, MVB_BUILD_DEFINITION, STACK_SIZE, start_stack, start_thread(), start_thread_handle, and START_WORKTHREAD_PRI.
 {
 #ifdef MVBPROJ_BASIC_INFO_SUPPORT
     printf("\n\n\n\n\nMVB ARM monitor for T113 (build%04d)\n\n", MVB_BUILD_DEFINITION);
 #endif // ifdef MVBPROJ_BASIC_INFO_SUPPORT
 #ifdef MVBPROJ_LED_SUPPORT
     mvb_arm_init_led(0);
 #endif
     cyg_thread_create(START_WORKTHREAD_PRI, start_thread, 0, "START ARM", &start_stack, STACK_SIZE, &start_thread_handle, &start_thread_data);
     cyg_thread_resume(start_thread_handle);
     cyg_scheduler_start();
 }
void exti_thread (cyg_addrword_t data)
Definition at line 116 of file intr.c.
References errorframe_interrupt_dsr(), errorframe_interrupt_isr(), EXTI_ERROR_FRAME_PRI, EXTI_ERROR_FRAME_VECTOR, EXTI_MAIN_FRAME_PRI, EXTI_MAIN_FRAME_VECTOR, EXTI_NO_TIME_PRI, EXTI_NO_TIME_VECTOR, EXTI_SLAVE_FRAME_PRI, EXTI_SLAVE_FRAME_VECTOR, EXTI_SUPERVISORY_INT_PRI, EXTI_SUPERVISORY_INT_VECTOR, EXTI_SYNC_PRI, EXTI_SYNC_VECTOR, EXTI_TIMEOUT_PRI, EXTI_TIMEOUT_VECTOR, mainframe_interrupt_dsr(), mainframe_interrupt_isr(), mvb_arm_send_status, mvb_device_status_16, notime_interrupt_dsr(), notime_interrupt_isr(), slaveframe_interrupt_dsr(), slaveframe_interrupt_isr(), supervisory_interrupt_dsr(), supervisory_interrupt_handle(), supervisory_interrupt_isr(), sync_interrupt_dsr(), sync_interrupt_isr(), this_addr, timeout_interrupt_dsr(), and timeout_interrupt_isr().
Referenced by start_thread().
 {
     cyg_interrupt   supervisory_interrupt,
                     timeout_interrupt,
                     errorframe_interrupt,
                     mainframe_interrupt,
                     slaveframe_interrupt,
                     sync_interrupt,
                     notime_interrupt;
     cyg_handle_t    supervisory_interrupt_handle,
                     timeout_interrupt_handle,
                     errorframe_interrupt_handle,
                     mainframe_interrupt_handle,
                     slaveframe_interrupt_handle,
                     sync_interrupt_handle,
                     notime_interrupt_handle;
     cyg_interrupt_create(EXTI_SUPERVISORY_INT_VECTOR, EXTI_SUPERVISORY_INT_PRI, 0, supervisory_interrupt_isr, supervisory_interrupt_dsr, &supervisory_interrupt_handle, &supervisory_interrupt);
     cyg_interrupt_configure(EXTI_SUPERVISORY_INT_VECTOR, 0, 0);
     cyg_interrupt_attach(supervisory_interrupt_handle);
     cyg_interrupt_create(EXTI_TIMEOUT_VECTOR, EXTI_TIMEOUT_PRI, 0, timeout_interrupt_isr, timeout_interrupt_dsr, &timeout_interrupt_handle, &timeout_interrupt);
     cyg_interrupt_configure(EXTI_TIMEOUT_VECTOR, 0, 0);
     cyg_interrupt_attach(timeout_interrupt_handle);
     cyg_interrupt_create(EXTI_ERROR_FRAME_VECTOR, EXTI_ERROR_FRAME_PRI, 0, errorframe_interrupt_isr, errorframe_interrupt_dsr, &errorframe_interrupt_handle, &errorframe_interrupt);
     cyg_interrupt_configure(EXTI_ERROR_FRAME_VECTOR, 0, 0);
     cyg_interrupt_attach(errorframe_interrupt_handle);
     cyg_interrupt_create(EXTI_MAIN_FRAME_VECTOR, EXTI_MAIN_FRAME_PRI, 0, mainframe_interrupt_isr, mainframe_interrupt_dsr, &mainframe_interrupt_handle, &mainframe_interrupt);
     cyg_interrupt_configure(EXTI_MAIN_FRAME_VECTOR, 0, 0);
     cyg_interrupt_attach(mainframe_interrupt_handle);
     cyg_interrupt_create(EXTI_SLAVE_FRAME_VECTOR, EXTI_SLAVE_FRAME_PRI, 0, slaveframe_interrupt_isr, slaveframe_interrupt_dsr, &slaveframe_interrupt_handle, &slaveframe_interrupt);
     cyg_interrupt_configure(EXTI_SLAVE_FRAME_VECTOR, 0, 0);
     cyg_interrupt_attach(slaveframe_interrupt_handle);
     cyg_interrupt_create(EXTI_SYNC_VECTOR, EXTI_SYNC_PRI, 0, sync_interrupt_isr, sync_interrupt_dsr, &sync_interrupt_handle, &sync_interrupt);
     cyg_interrupt_configure(EXTI_SYNC_VECTOR, 0, 0);
     cyg_interrupt_attach(sync_interrupt_handle);
     cyg_interrupt_create(EXTI_NO_TIME_VECTOR, EXTI_NO_TIME_PRI, 0, notime_interrupt_isr, notime_interrupt_dsr, &notime_interrupt_handle, &notime_interrupt);
     cyg_interrupt_configure(EXTI_NO_TIME_VECTOR, 0, 0);
     cyg_interrupt_attach(notime_interrupt_handle);
 #ifdef MVBPROJ_BASIC_INFO_SUPPORT
     printf("Interrupt init :: attach completed\n\n");
     printf("Device address: 0x%04x (%d), status: 0x%04x, All clear.\n", this_addr, this_addr, mvb_device_status_16);
 #endif // ifdef MVBPROJ_BASIC_INFO_SUPPORT
     cyg_interrupt_unmask(EXTI_SUPERVISORY_INT_VECTOR);
     cyg_interrupt_unmask(EXTI_TIMEOUT_VECTOR);
     cyg_interrupt_unmask(EXTI_ERROR_FRAME_VECTOR);
     cyg_interrupt_unmask(EXTI_MAIN_FRAME_VECTOR);
     cyg_interrupt_unmask(EXTI_SLAVE_FRAME_VECTOR);
     cyg_interrupt_unmask(EXTI_SYNC_VECTOR);
     cyg_interrupt_unmask(EXTI_NO_TIME_VECTOR);
     cyg_interrupt_enable();
     mvb_arm_send_status(mvb_device_status_16);
     cyg_thread_exit();
 }
void led_thread (cyg_addrword_t data)
Definition at line 166 of file main.c.
References MVB_DEVICE_STATUS::lat, LED_FREQUENCY, mvb_arm_active_led, mvb_arm_line_a_led, mvb_arm_line_b_led, and MVB_DEVICE_STATUS::rld.
Referenced by start_thread().
 {
     cyg_uint16 active_light_status = 0;
     while (1)
     {
         mvb_arm_active_led(active_light_status);
         if (mvb_device_status.lat == 1)
         {
 #ifdef MVB_ARM_LED_LINE_A
             mvb_arm_line_a_led(active_light_status);
 #endif // ifdef MVB_ARM_LED_LINE_A
 #ifdef MVB_ARM_LED_LINE_B
             if (mvb_device_status.rld == 1)
             {
                 mvb_arm_line_b_led(0);
             }
             else
             {
                 mvb_arm_line_b_led(1);
             }
 #endif // ifdef MVB_ARM_LED_LINE_B
         }
         else
         {
 #ifdef MVB_ARM_LED_LINE_B
             mvb_arm_line_b_led(active_light_status);
 #endif // ifdef MVB_ARM_LED_LINE_B
 #ifdef MVB_ARM_LED_LINE_A
             if (mvb_device_status.rld == 1)
             {
                 mvb_arm_line_a_led(0);
             }
             else
             {
                 mvb_arm_line_a_led(1);
             }
 #endif // ifdef MVB_ARM_LED_LINE_A
         }
         cyg_thread_delay(LED_FREQUENCY);
         if (active_light_status == 0)
             active_light_status = 1;
         else
             active_light_status = 0;
     }
 }
void start_thread (cyg_addrword_t data)
Definition at line 92 of file main.c.
References create_structure(), CYGARC_REG_SYSTICK_BASE, CYGARC_REG_SYSTICK_RELOAD, exti_stack, exti_thread(), exti_thread_handle, EXTI_WORKTHREAD_PRI, fpga(), HAL_WRITE_UINT32, led_stack, led_thread(), led_thread_handle, LED_WORKTHREAD_PRI, mvb_arm_init_all_gpio, mvb_arm_init_exti, parse(), and STACK_SIZE.
Referenced by cyg_start().
 {
     HAL_WRITE_UINT32(CYGARC_REG_SYSTICK_BASE+CYGARC_REG_SYSTICK_RELOAD, 2099 );
     cyg_tick_count_t aticks = cyg_current_time();
     if (fpga() == 0)
     {
 #ifdef MVBPROJ_BASIC_INFO_SUPPORT
         printf("FPGA init :: ERROR :: ARM STOP\n");
 #endif // ifdef MVBPROJ_BASIC_INFO_SUPPORT
         cyg_thread_exit();
     }
     cyg_tick_count_t bticks = cyg_current_time();
     UNSIGNED32 time = ((UNSIGNED32)bticks - (UNSIGNED32)aticks) / 10;
     printf("FPGA init :: PROGRAMMING TIME :: %d ms\n", time);
 #ifdef MVBPROJ_BASIC_INFO_SUPPORT
     printf("...configuring GPIO...\n");
 #endif // ifdef MVBPROJ_BASIC_INFO_SUPPORT
     mvb_arm_init_all_gpio();
 #ifdef MVBPROJ_BASIC_INFO_SUPPORT
     printf("...configuring EXTI...\n");
 #endif // ifdef MVBPROJ_BASIC_INFO_SUPPORT
     mvb_arm_init_exti();
     cyg_thread_create(EXTI_WORKTHREAD_PRI, exti_thread, 0, "EXTI CONFIGURATION", &exti_stack, STACK_SIZE, &exti_thread_handle, &exti_thread_data);
     aticks = cyg_current_time();
     if (parse() == 0)
     {
 #ifdef MVBPROJ_BASIC_INFO_SUPPORT
         printf("Binary init :: ERROR :: Parsing error, no config data.\n");
 #endif // ifdef MVBPROJ_BASIC_INFO_SUPPORT
     }
     bticks = cyg_current_time();
     time = ((UNSIGNED32)bticks - (UNSIGNED32)aticks) / 10;
     printf("Binary init :: ELAPSED TIME :: %d ms\n", time);
 #ifdef MVBPROJ_BASIC_INFO_SUPPORT
     printf("...creating data structure...\n");
 #endif // ifdef MVBPROJ_BASIC_INFO_SUPPORT
     create_structure();
 #ifdef MVBPROJ_BASIC_INFO_SUPPORT
     printf("...attaching interrupt...\n");
 #endif // ifdef MVBPROJ_BASIC_INFO_SUPPORT
 #ifdef MVBPROJ_LED_SUPPORT
     cyg_thread_create(LED_WORKTHREAD_PRI, led_thread, 0, "LED SUPPORT", &led_stack, STACK_SIZE, &led_thread_handle, &led_thread_data);
 #endif // ifdef MVBPROJ_LED_SUPPORT
     cyg_thread_resume(exti_thread_handle); // Start it
 #ifdef MVBPROJ_LED_SUPPORT
     cyg_thread_resume(led_thread_handle);
 #endif // ifdef MVBPROJ_LED_SUPPORT
     cyg_thread_exit();
 }