My Project: C:/Users/barry/Dropbox/ecos/130721消息数据优化5/130721消息数据优化5/main.c File Reference
main.c File Reference
#include "main.h"
Functions
void cyg_start (void)
void start_thread (cyg_addrword_t data)
void led_thread (cyg_addrword_t data)
Variables
char exti_stack [STACK_SIZE]
char start_stack [STACK_SIZE]
cyg_thread start_thread_data
cyg_thread exti_thread_data
cyg_handle_t start_thread_handle
cyg_handle_t exti_thread_handle
char led_stack [STACK_SIZE]
cyg_thread led_thread_data
cyg_handle_t led_thread_handle
MVB_DEVICE_STATUS mvb_device_status
Function Documentation
void cyg_start (void)
Definition at line 57 of file main.c.
References mvb_arm_init_led, MVB_BUILD_DEFINITION, STACK_SIZE, start_stack, start_thread(), start_thread_handle, and START_WORKTHREAD_PRI.
 {
 #ifdef MVBPROJ_BASIC_INFO_SUPPORT
     printf("\n\n\n\n\nMVB ARM monitor for T113 (build%04d)\n\n", MVB_BUILD_DEFINITION);
 #endif // ifdef MVBPROJ_BASIC_INFO_SUPPORT
 #ifdef MVBPROJ_LED_SUPPORT
     mvb_arm_init_led(0);
 #endif
     cyg_thread_create(START_WORKTHREAD_PRI, start_thread, 0, "START ARM", &start_stack, STACK_SIZE, &start_thread_handle, &start_thread_data);
     cyg_thread_resume(start_thread_handle);
     cyg_scheduler_start();
 }
void led_thread (cyg_addrword_t data)
Definition at line 166 of file main.c.
References MVB_DEVICE_STATUS::lat, LED_FREQUENCY, mvb_arm_active_led, mvb_arm_line_a_led, mvb_arm_line_b_led, and MVB_DEVICE_STATUS::rld.
Referenced by start_thread().
 {
     cyg_uint16 active_light_status = 0;
     while (1)
     {
         mvb_arm_active_led(active_light_status);
         if (mvb_device_status.lat == 1)
         {
 #ifdef MVB_ARM_LED_LINE_A
             mvb_arm_line_a_led(active_light_status);
 #endif // ifdef MVB_ARM_LED_LINE_A
 #ifdef MVB_ARM_LED_LINE_B
             if (mvb_device_status.rld == 1)
             {
                 mvb_arm_line_b_led(0);
             }
             else
             {
                 mvb_arm_line_b_led(1);
             }
 #endif // ifdef MVB_ARM_LED_LINE_B
         }
         else
         {
 #ifdef MVB_ARM_LED_LINE_B
             mvb_arm_line_b_led(active_light_status);
 #endif // ifdef MVB_ARM_LED_LINE_B
 #ifdef MVB_ARM_LED_LINE_A
             if (mvb_device_status.rld == 1)
             {
                 mvb_arm_line_a_led(0);
             }
             else
             {
                 mvb_arm_line_a_led(1);
             }
 #endif // ifdef MVB_ARM_LED_LINE_A
         }
         cyg_thread_delay(LED_FREQUENCY);
         if (active_light_status == 0)
             active_light_status = 1;
         else
             active_light_status = 0;
     }
 }
void start_thread (cyg_addrword_t data)
Definition at line 92 of file main.c.
References create_structure(), CYGARC_REG_SYSTICK_BASE, CYGARC_REG_SYSTICK_RELOAD, exti_stack, exti_thread(), exti_thread_handle, EXTI_WORKTHREAD_PRI, fpga(), HAL_WRITE_UINT32, led_stack, led_thread(), led_thread_handle, LED_WORKTHREAD_PRI, mvb_arm_init_all_gpio, mvb_arm_init_exti, parse(), and STACK_SIZE.
Referenced by cyg_start().
 {
     HAL_WRITE_UINT32(CYGARC_REG_SYSTICK_BASE+CYGARC_REG_SYSTICK_RELOAD, 2099 );
     cyg_tick_count_t aticks = cyg_current_time();
     if (fpga() == 0)
     {
 #ifdef MVBPROJ_BASIC_INFO_SUPPORT
         printf("FPGA init :: ERROR :: ARM STOP\n");
 #endif // ifdef MVBPROJ_BASIC_INFO_SUPPORT
         cyg_thread_exit();
     }
     cyg_tick_count_t bticks = cyg_current_time();
     UNSIGNED32 time = ((UNSIGNED32)bticks - (UNSIGNED32)aticks) / 10;
     printf("FPGA init :: PROGRAMMING TIME :: %d ms\n", time);
 #ifdef MVBPROJ_BASIC_INFO_SUPPORT
     printf("...configuring GPIO...\n");
 #endif // ifdef MVBPROJ_BASIC_INFO_SUPPORT
     mvb_arm_init_all_gpio();
 #ifdef MVBPROJ_BASIC_INFO_SUPPORT
     printf("...configuring EXTI...\n");
 #endif // ifdef MVBPROJ_BASIC_INFO_SUPPORT
     mvb_arm_init_exti();
     cyg_thread_create(EXTI_WORKTHREAD_PRI, exti_thread, 0, "EXTI CONFIGURATION", &exti_stack, STACK_SIZE, &exti_thread_handle, &exti_thread_data);
     aticks = cyg_current_time();
     if (parse() == 0)
     {
 #ifdef MVBPROJ_BASIC_INFO_SUPPORT
         printf("Binary init :: ERROR :: Parsing error, no config data.\n");
 #endif // ifdef MVBPROJ_BASIC_INFO_SUPPORT
     }
     bticks = cyg_current_time();
     time = ((UNSIGNED32)bticks - (UNSIGNED32)aticks) / 10;
     printf("Binary init :: ELAPSED TIME :: %d ms\n", time);
 #ifdef MVBPROJ_BASIC_INFO_SUPPORT
     printf("...creating data structure...\n");
 #endif // ifdef MVBPROJ_BASIC_INFO_SUPPORT
     create_structure();
 #ifdef MVBPROJ_BASIC_INFO_SUPPORT
     printf("...attaching interrupt...\n");
 #endif // ifdef MVBPROJ_BASIC_INFO_SUPPORT
 #ifdef MVBPROJ_LED_SUPPORT
     cyg_thread_create(LED_WORKTHREAD_PRI, led_thread, 0, "LED SUPPORT", &led_stack, STACK_SIZE, &led_thread_handle, &led_thread_data);
 #endif // ifdef MVBPROJ_LED_SUPPORT
     cyg_thread_resume(exti_thread_handle); // Start it
 #ifdef MVBPROJ_LED_SUPPORT
     cyg_thread_resume(led_thread_handle);
 #endif // ifdef MVBPROJ_LED_SUPPORT
     cyg_thread_exit();
 }
Variable Documentation
char exti_stack[STACK_SIZE]
Definition at line 30 of file main.c.
Referenced by start_thread().
cyg_thread exti_thread_data
Definition at line 32 of file main.c.
cyg_handle_t exti_thread_handle
Definition at line 33 of file main.c.
Referenced by start_thread().
char led_stack[STACK_SIZE]
Definition at line 37 of file main.c.
Referenced by start_thread().
cyg_thread led_thread_data
Definition at line 38 of file main.c.
cyg_handle_t led_thread_handle
Definition at line 39 of file main.c.
Referenced by start_thread().
MVB_DEVICE_STATUS mvb_device_status
Definition at line 51 of file init.c.
char start_stack[STACK_SIZE]
Definition at line 30 of file main.c.
Referenced by cyg_start().
cyg_thread start_thread_data
Definition at line 32 of file main.c.
cyg_handle_t start_thread_handle
Definition at line 33 of file main.c.
Referenced by cyg_start().